#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Groups/IActorGroup.h
    Groups/ActorGroup.h
    Groups/ActorGroup.cpp
    Groups/IMotionGroup.h
    Groups/MotionGroup.h
    Groups/MotionGroup.cpp
    Behaviors/ActorGroupBehavior.h
    Behaviors/ActorGroupBehavior.cpp
    Behaviors/MotionGroupBehavior.h
    Behaviors/MotionGroupBehavior.cpp
    Behaviors/MotionRangeRuleBehavior.h
    Behaviors/MotionRangeRuleBehavior.cpp
    Behaviors/MorphTargetRuleBehavior.h
    Behaviors/MorphTargetRuleBehavior.cpp
    Behaviors/LodRuleBehavior.h
    Behaviors/LodRuleBehavior.cpp
    Behaviors/SkeletonOptimizationRuleBehavior.h
    Behaviors/SkeletonOptimizationRuleBehavior.cpp
    Behaviors/RootMotionExtractionRuleBehavior.h
    Behaviors/RootMotionExtractionRuleBehavior.cpp
    Rules/ActorPhysicsSetupRule.h
    Rules/ActorPhysicsSetupRule.cpp
    Rules/ExternalToolRule.h
    Rules/ExternalToolRule.inl
    Rules/MetaDataRule.h
    Rules/MetaDataRule.cpp
    Rules/MetaDataRule.inl
    Rules/IMotionCompressionSettingsRule.h
    Rules/MotionCompressionSettingsRule.h
    Rules/MotionCompressionSettingsRule.cpp
    Rules/MotionMetaDataRule.h
    Rules/MotionMetaDataRule.cpp
    Rules/MotionSamplingRule.cpp
    Rules/MotionSamplingRule.h
    Rules/SimulatedObjectSetupRule.h
    Rules/SimulatedObjectSetupRule.cpp
    Rules/MotionRangeRule.h
    Rules/MotionRangeRule.cpp
    Rules/MorphTargetRule.h
    Rules/MorphTargetRule.cpp
    Rules/LodRule.h
    Rules/LodRule.cpp
    Rules/MotionAdditiveRule.h
    Rules/MotionAdditiveRule.cpp
    Rules/RootMotionExtractionRule.h
    Rules/RootMotionExtractionRule.cpp
    Rules/SkeletonOptimizationRule.h
    Rules/SkeletonOptimizationRule.cpp
    Data/LodNodeSelectionList.h
    Data/LodNodeSelectionList.cpp
    Utilities/LODSelector.h
    Utilities/LODSelector.cpp
)
