#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Source/StandaloneToolsApplication.cpp
    Source/StandaloneToolsApplication.h
    Source/LuaIDEApplication.h
    Source/LuaIDEApplication.cpp
    Source/AssetDatabaseLocationListener.h
    Source/AssetDatabaseLocationListener.cpp
    Source/Editor/LuaEditor.cpp
    Source/LUA/BreakpointPanel.cpp
    Source/LUA/BreakpointPanel.hxx
    Source/LUA/ClassReferenceFilter.cpp
    Source/LUA/ClassReferenceFilter.hxx
    Source/LUA/ClassReferencePanel.cpp
    Source/LUA/ClassReferencePanel.hxx
    Source/LUA/DebugAttachmentButton.cpp
    Source/LUA/DebugAttachmentButton.hxx
    Source/LUA/LUABreakpointTrackerMessages.cpp
    Source/LUA/LUABreakpointTrackerMessages.h
    Source/LUA/LUAContextControlMessages.h
    Source/LUA/LUADebuggerComponent.cpp
    Source/LUA/LUADebuggerComponent.h
    Source/LUA/LUAEditorBlockState.h
    Source/LUA/LUAEditorBreakpointWidget.cpp
    Source/LUA/LUAEditorBreakpointWidget.hxx
    Source/LUA/LUAEditorContext.cpp
    Source/LUA/LUAEditorContext.h
    Source/LUA/LUAEditorContextInterface.h
    Source/LUA/LUAEditorContextMessages.h
    Source/LUA/LUAEditorDebuggerMessages.h
    Source/LUA/LUAEditorFindDialog.cpp
    Source/LUA/LUAEditorFindDialog.hxx
    Source/LUA/LUAEditorFindDialog.ui
    Source/LUA/LUAEditorSettingsDialog.cpp
    Source/LUA/LUAEditorSettingsDialog.hxx
    Source/LUA/LUAEditorSettingsDialog.ui
    Source/LUA/LUAEditorFindResults.cpp
    Source/LUA/LUAEditorFindResults.hxx
    Source/LUA/LUAEditorFindResults.ui
    Source/LUA/LUAEditorFoldingWidget.cpp
    Source/LUA/LUAEditorFoldingWidget.hxx
    Source/LUA/LUAEditorGoToLineDialog.cpp
    Source/LUA/LUAEditorGoToLineDialog.hxx
    Source/LUA/LUAEditorGoToLineDialog.ui
    Source/LUA/LUAEditorMainWindow.cpp
    Source/LUA/LUAEditorMainWindow.hxx
    Source/LUA/LUAEditorMainWindow.ui
    Source/LUA/LUAEditorPlainTextEdit.cpp
    Source/LUA/LUAEditorPlainTextEdit.hxx
    Source/LUA/LUAEditorStyleMessages.cpp
    Source/LUA/LUAEditorStyleMessages.h
    Source/LUA/LUAEditorSyntaxHighlighter.cpp
    Source/LUA/LUAEditorSyntaxHighlighter.hxx
    Source/LUA/LUAEditorView.cpp
    Source/LUA/LUAEditorView.hxx
    Source/LUA/LUAEditorView.ui
    Source/LUA/LUAEditorViewMessages.h
    Source/LUA/LUALocalsTrackerMessages.h
    Source/LUA/LUAStackTrackerMessages.h
    Source/LUA/LUATargetContextTrackerMessages.h
    Source/LUA/LUAWatchesDebuggerMessages.h
    Source/LUA/RecentFiles.cpp
    Source/LUA/RecentFiles.h
    Source/LUA/StackPanel.cpp
    Source/LUA/StackPanel.hxx
    Source/LUA/TargetContextButton.cpp
    Source/LUA/TargetContextButton.hxx
    Source/LUA/WatchesPanel.cpp
    Source/LUA/WatchesPanel.hxx
    Source/LUA/CodeCompletion/LUACompleter.cpp
    Source/LUA/CodeCompletion/LUACompleter.hxx
    Source/LUA/CodeCompletion/LUACompletionModel.cpp
    Source/LUA/CodeCompletion/LUACompletionModel.hxx
)
