#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Source/Ai/NavigationSystemComponent.h
    Source/Ai/NavigationSystemComponent.cpp
    Source/Audio/AudioAreaEnvironmentComponent.h
    Source/Audio/AudioAreaEnvironmentComponent.cpp
    Source/Audio/AudioEnvironmentComponent.h
    Source/Audio/AudioEnvironmentComponent.cpp
    Source/Audio/AudioListenerComponent.h
    Source/Audio/AudioListenerComponent.cpp
    Source/Audio/AudioMultiPositionComponent.h
    Source/Audio/AudioMultiPositionComponent.cpp
    Source/Audio/AudioPreloadComponent.h
    Source/Audio/AudioPreloadComponent.cpp
    Source/Audio/AudioProxyComponent.h
    Source/Audio/AudioProxyComponent.cpp
    Source/Audio/AudioRtpcComponent.h
    Source/Audio/AudioRtpcComponent.cpp
    Source/Audio/AudioSwitchComponent.h
    Source/Audio/AudioSwitchComponent.cpp
    Source/Audio/AudioSystemComponent.h
    Source/Audio/AudioSystemComponent.cpp
    Source/Audio/AudioTriggerComponent.h
    Source/Audio/AudioTriggerComponent.cpp
    Source/Asset/AssetSystemDebugComponent.h
    Source/Asset/AssetSystemDebugComponent.cpp
    Source/Bundling/BundlingSystemComponent.h
    Source/Bundling/BundlingSystemComponent.cpp
    Source/Events/ReflectScriptableEvents.h
    Source/Events/ReflectScriptableEvents.cpp
    Source/Geometry/GeometrySystemComponent.h
    Source/Geometry/GeometrySystemComponent.cpp
    Source/Rendering/EntityDebugDisplayComponent.h
    Source/Rendering/EntityDebugDisplayComponent.cpp
    Source/Scripting/LookAtComponent.h
    Source/Scripting/LookAtComponent.cpp
    Source/Scripting/RandomTimedSpawnerComponent.cpp
    Source/Scripting/RandomTimedSpawnerComponent.h
    Source/Scripting/SimpleStateComponent.h
    Source/Scripting/SimpleStateComponent.cpp
    Source/Scripting/TagComponent.h
    Source/Scripting/TagComponent.cpp
    Source/Shape/ShapeDisplay.h
    Source/Shape/ShapeComponent.cpp
    Source/Shape/SphereShape.h
    Source/Shape/SphereShape.cpp
    Source/Shape/SphereShapeComponent.h
    Source/Shape/SphereShapeComponent.cpp
    Source/Shape/AxisAlignedBoxShape.h
    Source/Shape/AxisAlignedBoxShape.cpp
    Source/Shape/AxisAlignedBoxShapeComponent.h
    Source/Shape/AxisAlignedBoxShapeComponent.cpp
    Source/Shape/BoxShape.h
    Source/Shape/BoxShape.cpp
    Source/Shape/BoxShapeComponent.h
    Source/Shape/BoxShapeComponent.cpp
    Source/Shape/CylinderShape.h
    Source/Shape/CylinderShape.cpp
    Source/Shape/CylinderShapeComponent.h
    Source/Shape/CylinderShapeComponent.cpp
    Source/Shape/CapsuleShape.h
    Source/Shape/CapsuleShape.cpp
    Source/Shape/CapsuleShapeComponent.h
    Source/Shape/CapsuleShapeComponent.cpp
    Source/Shape/DiskShape.h
    Source/Shape/DiskShape.cpp
    Source/Shape/DiskShapeComponent.h
    Source/Shape/DiskShapeComponent.cpp
    Source/Shape/CompoundShapeComponent.h
    Source/Shape/CompoundShapeComponent.cpp
    Source/Shape/QuadShape.h
    Source/Shape/QuadShape.cpp
    Source/Shape/QuadShapeComponent.h
    Source/Shape/QuadShapeComponent.cpp
    Source/Shape/SplineComponent.h
    Source/Shape/SplineComponent.cpp
    Source/Shape/PolygonPrismShape.h
    Source/Shape/PolygonPrismShape.cpp
    Source/Shape/PolygonPrismShapeComponent.h
    Source/Shape/PolygonPrismShapeComponent.cpp
    Source/Shape/TubeShapeComponent.h
    Source/Shape/TubeShapeComponent.cpp
    Source/Shape/ShapeComponentConverters.h
    Source/Shape/ShapeComponentConverters.cpp
    Source/Shape/ShapeComponentConverters.inl
    Source/Shape/ShapeGeometryUtil.h
    Source/Shape/ShapeGeometryUtil.cpp
    Source/Unhandled/Other/AudioAssetTypeInfo.cpp
    Source/Unhandled/Other/AudioAssetTypeInfo.h
    Source/Unhandled/Other/CharacterPhysicsAssetTypeInfo.cpp
    Source/Unhandled/Other/CharacterPhysicsAssetTypeInfo.h
    Source/Unhandled/Other/EntityPrototypeLibraryAssetTypeInfo.cpp
    Source/Unhandled/Other/EntityPrototypeLibraryAssetTypeInfo.h
    Source/Unhandled/Other/GameTokenAssetTypeInfo.cpp
    Source/Unhandled/Other/GameTokenAssetTypeInfo.h
    Source/Unhandled/Other/GroupAssetTypeInfo.cpp
    Source/Unhandled/Other/GroupAssetTypeInfo.h
    Source/Unhandled/Other/PrefabsLibraryAssetTypeInfo.cpp
    Source/Unhandled/Other/PrefabsLibraryAssetTypeInfo.h
    Source/Unhandled/Texture/SubstanceAssetTypeInfo.cpp
    Source/Unhandled/Texture/SubstanceAssetTypeInfo.h
    Source/Unhandled/Texture/TextureAssetTypeInfo.cpp
    Source/Unhandled/Texture/TextureAssetTypeInfo.h
    Source/Unhandled/Hidden/TextureMipmapAssetTypeInfo.cpp
    Source/Unhandled/Hidden/TextureMipmapAssetTypeInfo.h
    Source/Unhandled/UI/EntityIconAssetTypeInfo.cpp
    Source/Unhandled/UI/EntityIconAssetTypeInfo.h
    Source/Unhandled/UI/FontAssetTypeInfo.cpp
    Source/Unhandled/UI/FontAssetTypeInfo.h
    Source/Unhandled/UI/UICanvasAssetTypeInfo.cpp
    Source/Unhandled/UI/UICanvasAssetTypeInfo.h
)

set(SKIP_UNITY_BUILD_INCLUSION_FILES
    Source/Shape/ShapeComponent.cpp
)
