#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#

set(FILES
    Woodpecker/ProfilerApplication.h
    Woodpecker/ProfilerApplication.cpp
    Woodpecker/Editor/ProfilerEditor.h
    Woodpecker/Editor/ProfilerEditor.cpp
    Woodpecker/Driller/Axis.cpp
    Woodpecker/Driller/Axis.hxx
    Woodpecker/Driller/AreaChart.cpp
    Woodpecker/Driller/AreaChart.hxx
    Woodpecker/Driller/ChannelConfigurationDialog.cpp
    Woodpecker/Driller/ChannelConfigurationDialog.hxx
    Woodpecker/Driller/ChannelConfigurationWidget.cpp
    Woodpecker/Driller/ChannelConfigurationWidget.hxx
    Woodpecker/Driller/ChannelControl.cpp
    Woodpecker/Driller/ChannelControl.hxx
    Woodpecker/Driller/ChannelControl.ui
    Woodpecker/Driller/ChannelProfilerWidget.cpp
    Woodpecker/Driller/ChannelProfilerWidget.hxx
    Woodpecker/Driller/ChannelProfilerWidget.ui
    Woodpecker/Driller/ChannelDataView.cpp
    Woodpecker/Driller/ChannelDataView.hxx
    Woodpecker/Driller/ChartNumberFormats.cpp
    Woodpecker/Driller/ChartNumberFormats.h
    Woodpecker/Driller/ChartTypes.cpp
    Woodpecker/Driller/ChartTypes.hxx
    Woodpecker/Driller/CollapsiblePanel.cpp
    Woodpecker/Driller/CollapsiblePanel.hxx
    Woodpecker/Driller/CollapsiblePanel.ui
    Woodpecker/Driller/CombinedEventsControl.cpp
    Woodpecker/Driller/CombinedEventsControl.hxx
    Woodpecker/Driller/CustomizeCSVExportWidget.cpp
    Woodpecker/Driller/CustomizeCSVExportWidget.hxx
    Woodpecker/Driller/CSVExportSettings.h
    Woodpecker/Driller/DoubleListSelector.cpp
    Woodpecker/Driller/DoubleListSelector.hxx
    Woodpecker/Driller/DoubleListSelector.ui
    Woodpecker/Driller/DrillerAggregator.cpp
    Woodpecker/Driller/DrillerAggregator.hxx
    Woodpecker/Driller/DrillerAggregatorOptions.hxx
    Woodpecker/Driller/DrillerCaptureWindow.cpp
    Woodpecker/Driller/DrillerCaptureWindow.hxx
    Woodpecker/Driller/DrillerCaptureWindow.ui
    Woodpecker/Driller/DrillerContext.cpp
    Woodpecker/Driller/DrillerContext.h
    Woodpecker/Driller/DrillerContextInterface.h
    Woodpecker/Driller/DrillerDataContainer.cpp
    Woodpecker/Driller/DrillerDataContainer.h
    Woodpecker/Driller/DrillerDataTypes.h
    Woodpecker/Driller/DrillerEvent.cpp
    Woodpecker/Driller/DrillerEvent.h
    Woodpecker/Driller/DrillerMainChannelsView.ui
    Woodpecker/Driller/DrillerMainWindow.cpp
    Woodpecker/Driller/DrillerMainWindow.hxx
    Woodpecker/Driller/DrillerMainWindow.ui
    Woodpecker/Driller/DrillerMainWindowMessages.cpp
    Woodpecker/Driller/DrillerMainWindowMessages.h
    Woodpecker/Driller/DrillerNetworkMessages.h
    Woodpecker/Driller/DrillerOperationTelemetryEvent.cpp
    Woodpecker/Driller/DrillerOperationTelemetryEvent.h
    Woodpecker/Driller/FilteredListView.cpp
    Woodpecker/Driller/FilteredListView.hxx
    Woodpecker/Driller/FilteredListView.ui
    Woodpecker/Driller/GenericCustomizeCSVExportWidget.cpp
    Woodpecker/Driller/GenericCustomizeCSVExportWidget.hxx
    Woodpecker/Driller/GenericCustomizeCSVExportWidget.ui
    Woodpecker/Driller/RacetrackChart.cpp
    Woodpecker/Driller/RacetrackChart.hxx
    Woodpecker/Driller/StripChart.cpp
    Woodpecker/Driller/StripChart.hxx
    Woodpecker/Driller/Annotations/AnnotationHeaderView.cpp
    Woodpecker/Driller/Annotations/AnnotationHeaderView.hxx
    Woodpecker/Driller/Annotations/AnnotationHeaderView.ui
    Woodpecker/Driller/Annotations/Annotations.cpp
    Woodpecker/Driller/Annotations/Annotations.hxx
    Woodpecker/Driller/Annotations/AnnotationsDataView.cpp
    Woodpecker/Driller/Annotations/AnnotationsDataView.hxx
    Woodpecker/Driller/Annotations/AnnotationsDataView_Events.cpp
    Woodpecker/Driller/Annotations/AnnotationsDataView_Events.hxx
    Woodpecker/Driller/Annotations/AnnotationsHeaderView_Events.cpp
    Woodpecker/Driller/Annotations/AnnotationsHeaderView_Events.hxx
    Woodpecker/Driller/Annotations/ConfigureAnnotationsDialog.ui
    Woodpecker/Driller/Annotations/ConfigureAnnotationsWindow.cpp
    Woodpecker/Driller/Annotations/ConfigureAnnotationsWindow.hxx
    Woodpecker/Driller/Carrier/CarrierDataAggregator.cpp
    Woodpecker/Driller/Carrier/CarrierDataAggregator.hxx
    Woodpecker/Driller/Carrier/CarrierDataEvents.h
    Woodpecker/Driller/Carrier/CarrierDataParser.cpp
    Woodpecker/Driller/Carrier/CarrierDataParser.h
    Woodpecker/Driller/Carrier/CarrierDataView.cpp
    Woodpecker/Driller/Carrier/CarrierDataView.hxx
    Woodpecker/Driller/Carrier/CarrierDataView.ui
    Woodpecker/Driller/Carrier/CarrierOperationTelemetryEvent.h
    Woodpecker/Driller/EventTrace/EventTraceDataAggregator.cpp
    Woodpecker/Driller/EventTrace/EventTraceDataAggregator.h
    Woodpecker/Driller/EventTrace/EventTraceDataParser.cpp
    Woodpecker/Driller/EventTrace/EventTraceDataParser.h
    Woodpecker/Driller/EventTrace/EventTraceEvents.h
    Woodpecker/Driller/Memory/MemoryDataAggregator.cpp
    Woodpecker/Driller/Memory/MemoryDataAggregator.hxx
    Woodpecker/Driller/Memory/MemoryDataParser.cpp
    Woodpecker/Driller/Memory/MemoryDataParser.h
    Woodpecker/Driller/Memory/MemoryDataView.cpp
    Woodpecker/Driller/Memory/MemoryDataView.hxx
    Woodpecker/Driller/Memory/MemoryDataView.ui
    Woodpecker/Driller/Memory/MemoryEvents.cpp
    Woodpecker/Driller/Memory/MemoryEvents.h
    Woodpecker/Driller/Profiler/ProfilerDataAggregator.cpp
    Woodpecker/Driller/Profiler/ProfilerDataAggregator.hxx
    Woodpecker/Driller/Profiler/ProfilerDataPanel.cpp
    Woodpecker/Driller/Profiler/ProfilerDataPanel.hxx
    Woodpecker/Driller/Profiler/ProfilerDataParser.cpp
    Woodpecker/Driller/Profiler/ProfilerDataParser.h
    Woodpecker/Driller/Profiler/ProfilerDataView.cpp
    Woodpecker/Driller/Profiler/ProfilerDataView.hxx
    Woodpecker/Driller/Profiler/ProfilerDataView.ui
    Woodpecker/Driller/Profiler/ProfilerEvents.cpp
    Woodpecker/Driller/Profiler/ProfilerEvents.h
    Woodpecker/Driller/Profiler/ProfilerOperationTelemetryEvent.h
    Woodpecker/Driller/Rendering/VRAM/VRAMDataAggregator.cpp
    Woodpecker/Driller/Rendering/VRAM/VRAMDataAggregator.hxx
    Woodpecker/Driller/Rendering/VRAM/VRAMDataParser.cpp
    Woodpecker/Driller/Rendering/VRAM/VRAMDataParser.h
    Woodpecker/Driller/Rendering/VRAM/VRAMEvents.cpp
    Woodpecker/Driller/Rendering/VRAM/VRAMEvents.h
    Woodpecker/Driller/Replica/BaseDetailViewSavedState.h
    Woodpecker/Driller/Replica/BaseDetailViewQObject.cpp
    Woodpecker/Driller/Replica/BaseDetailViewQObject.hxx
    Woodpecker/Driller/Replica/BaseDetailView.inl
    Woodpecker/Driller/Replica/BaseDetailView.h
    Woodpecker/Driller/Replica/basedetailview.ui
    Woodpecker/Driller/Replica/OverallReplicaDetailView.cpp
    Woodpecker/Driller/Replica/OverallReplicaDetailView.hxx
    Woodpecker/Driller/Replica/overallreplicadetailview.ui
    Woodpecker/Driller/Replica/ReplicaBandwidthChartData.cpp
    Woodpecker/Driller/Replica/ReplicaBandwidthChartData.h
    Woodpecker/Driller/Replica/ReplicaChunkTypeDetailView.cpp
    Woodpecker/Driller/Replica/ReplicaChunkTypeDetailView.h
    Woodpecker/Driller/Replica/ReplicaChunkUsageDataContainers.cpp
    Woodpecker/Driller/Replica/ReplicaChunkUsageDataContainers.h
    Woodpecker/Driller/Replica/ReplicaDataAggregator.cpp
    Woodpecker/Driller/Replica/ReplicaDataAggregator.hxx
    Woodpecker/Driller/Replica/ReplicaDataAggregatorConfigurationPanel.cpp
    Woodpecker/Driller/Replica/ReplicaDataAggregatorConfigurationPanel.hxx
    Woodpecker/Driller/Replica/ReplicaDataAggregatorConfigurationPanel.ui
    Woodpecker/Driller/Replica/ReplicaDataEvents.h
    Woodpecker/Driller/Replica/ReplicaDataParser.cpp
    Woodpecker/Driller/Replica/ReplicaDataParser.h
    Woodpecker/Driller/Replica/ReplicaDataView.cpp
    Woodpecker/Driller/Replica/ReplicaDataView.hxx
    Woodpecker/Driller/Replica/replicadataview.ui
    Woodpecker/Driller/Replica/ReplicaDataViewConfigDialog.ui
    Woodpecker/Driller/Replica/ReplicaDetailView.cpp
    Woodpecker/Driller/Replica/ReplicaDetailView.h
    Woodpecker/Driller/Replica/ReplicaDisplayHelpers.cpp
    Woodpecker/Driller/Replica/ReplicaDisplayHelpers.h
    Woodpecker/Driller/Replica/ReplicaDisplayTypes.cpp
    Woodpecker/Driller/Replica/ReplicaDisplayTypes.h
    Woodpecker/Driller/Replica/ReplicaDrillerConfigToolbar.cpp
    Woodpecker/Driller/Replica/ReplicaDrillerConfigToolbar.hxx
    Woodpecker/Driller/Replica/ReplicaDrillerConfigToolbar.ui
    Woodpecker/Driller/Replica/ReplicaOperationTelemetryEvent.h
    Woodpecker/Driller/Replica/ReplicaTreeViewModel.cpp
    Woodpecker/Driller/Replica/ReplicaTreeViewModel.hxx
    Woodpecker/Driller/Replica/ReplicaUsageDataContainers.cpp
    Woodpecker/Driller/Replica/ReplicaUsageDataContainers.h
    Woodpecker/Driller/Trace/TraceDrillerDialog.cpp
    Woodpecker/Driller/Trace/TraceDrillerDialog.hxx
    Woodpecker/Driller/Trace/TraceDrillerDialog.ui
    Woodpecker/Driller/Trace/TraceMessageDataAggregator.cpp
    Woodpecker/Driller/Trace/TraceMessageDataAggregator.hxx
    Woodpecker/Driller/Trace/TraceMessageDataParser.cpp
    Woodpecker/Driller/Trace/TraceMessageDataParser.h
    Woodpecker/Driller/Trace/TraceMessageEvents.h
    Woodpecker/Driller/Trace/TraceOperationTelemetryEvent.h
    Woodpecker/Driller/Unsupported/UnsupportedDataAggregator.cpp
    Woodpecker/Driller/Unsupported/UnsupportedDataAggregator.hxx
    Woodpecker/Driller/Unsupported/UnsupportedDataParser.cpp
    Woodpecker/Driller/Unsupported/UnsupportedDataParser.h
    Woodpecker/Driller/Unsupported/UnsupportedEvents.h
    Woodpecker/Driller/Workspaces/Workspace.cpp
    Woodpecker/Driller/Workspaces/Workspace.h
)
