#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Application/ToolsApplication.cpp
    Application/ToolsApplication.h

    ActionManager/Action/ActionManager.cpp
    ActionManager/Action/ActionManager.h
    ActionManager/Action/EditorAction.cpp
    ActionManager/Action/EditorAction.h
    ActionManager/Action/EditorActionContext.cpp
    ActionManager/Action/EditorActionContext.h
    ActionManager/Action/EditorWidgetAction.cpp
    ActionManager/Action/EditorWidgetAction.h
    ActionManager/HotKey/HotKeyManager.cpp
    ActionManager/HotKey/HotKeyManager.h
    ActionManager/HotKey/HotKeyWidgetRegistrationHelper.cpp
    ActionManager/HotKey/HotKeyWidgetRegistrationHelper.h
    ActionManager/Menu/EditorMenu.cpp
    ActionManager/Menu/EditorMenu.h
    ActionManager/Menu/EditorMenuBar.cpp
    ActionManager/Menu/EditorMenuBar.h
    ActionManager/Menu/MenuManager.cpp
    ActionManager/Menu/MenuManager.h
    ActionManager/ToolBar/EditorToolBar.cpp
    ActionManager/ToolBar/EditorToolBar.h
    ActionManager/ToolBar/EditorToolBarArea.cpp
    ActionManager/ToolBar/EditorToolBarArea.h
    ActionManager/ToolBar/ToolBarManager.cpp
    ActionManager/ToolBar/ToolBarManager.h
    ActionManager/ActionManagerSystemComponent.cpp
    ActionManager/ActionManagerSystemComponent.h
    Application/EditorEntityManager.cpp
    Application/EditorEntityManager.h
    Application/Ticker.cpp
    Application/Ticker.h
    Archive/ArchiveComponent.cpp
    Archive/ArchiveComponent.h
    Asset/AssetBundler.cpp
    Asset/AssetBundler.h
    Asset/AssetDebugInfo.cpp
    Asset/AssetDebugInfo.h
    Asset/AssetProcessorMessages.cpp
    Asset/AssetProcessorMessages.h
    Asset/AssetSeedManager.h
    Asset/AssetSeedManager.cpp
    Asset/AssetSystemComponent.cpp
    Asset/AssetSystemComponent.h
    Asset/AssetUtils.cpp
    Asset/AssetUtils.h
    AssetBrowser/AssetPicker/AssetPickerDialog.cpp
    AssetBrowser/AssetPicker/AssetPickerDialog.h
    AssetBrowser/AssetPicker/AssetPickerDialog.ui
    AssetBrowser/Entries/AssetBrowserEntryCache.cpp
    AssetBrowser/Entries/AssetBrowserEntryCache.h
    AssetBrowser/Entries/AssetBrowserEntryUtils.cpp
    AssetBrowser/Entries/AssetBrowserEntryUtils.h
    AssetBrowser/Entries/FolderAssetBrowserEntry.cpp
    AssetBrowser/Entries/FolderAssetBrowserEntry.h
    AssetBrowser/Entries/ProductAssetBrowserEntry.cpp
    AssetBrowser/Entries/ProductAssetBrowserEntry.h
    AssetBrowser/Entries/RootAssetBrowserEntry.cpp
    AssetBrowser/Entries/RootAssetBrowserEntry.h
    AssetBrowser/Entries/SourceAssetBrowserEntry.cpp
    AssetBrowser/Entries/SourceAssetBrowserEntry.h
    AssetBrowser/Favorites/AssetBrowserFavoriteItem.cpp
    AssetBrowser/Favorites/AssetBrowserFavoriteItem.h
    AssetBrowser/Favorites/AssetBrowserFavoritesManager.cpp
    AssetBrowser/Favorites/AssetBrowserFavoritesManager.h
    AssetBrowser/Favorites/AssetBrowserFavoritesModel.cpp
    AssetBrowser/Favorites/AssetBrowserFavoritesModel.h
    AssetBrowser/Favorites/AssetBrowserFavoritesView.cpp
    AssetBrowser/Favorites/AssetBrowserFavoritesView.h
    AssetBrowser/Favorites/EntryAssetBrowserFavoriteItem.cpp
    AssetBrowser/Favorites/EntryAssetBrowserFavoriteItem.h
    AssetBrowser/Favorites/FavoritesEntryDelegate.cpp
    AssetBrowser/Favorites/FavoritesEntryDelegate.h
    AssetBrowser/Favorites/SearchAssetBrowserFavoriteItem.cpp
    AssetBrowser/Favorites/SearchAssetBrowserFavoriteItem.h
    AssetBrowser/Previewer/EmptyPreviewer.cpp
    AssetBrowser/Previewer/EmptyPreviewer.h
    AssetBrowser/Previewer/EmptyPreviewer.ui
    AssetBrowser/Previewer/Previewer.cpp
    AssetBrowser/Previewer/Previewer.h
    AssetBrowser/Previewer/PreviewerFrame.cpp
    AssetBrowser/Previewer/PreviewerFrame.h
    AssetBrowser/Search/Filter.cpp
    AssetBrowser/Search/Filter.h
    AssetBrowser/Search/FilterByWidget.cpp
    AssetBrowser/Search/FilterByWidget.h
    AssetBrowser/Search/FilterByWidget.ui
    AssetBrowser/Search/SearchAssetTypeSelectorWidget.cpp
    AssetBrowser/Search/SearchAssetTypeSelectorWidget.h
    AssetBrowser/Search/SearchAssetTypeSelectorWidget.ui
    AssetBrowser/Search/SearchParametersWidget.cpp
    AssetBrowser/Search/SearchParametersWidget.h
    AssetBrowser/Search/SearchParametersWidget.ui
    AssetBrowser/Search/SearchWidget.cpp
    AssetBrowser/Search/SearchWidget.h
    AssetBrowser/Search/SearchWidget.ui
    AssetBrowser/Thumbnails/FolderThumbnail.cpp
    AssetBrowser/Thumbnails/FolderThumbnail.h
    AssetBrowser/Thumbnails/ProductThumbnail.cpp
    AssetBrowser/Thumbnails/ProductThumbnail.h
    AssetBrowser/Thumbnails/SourceThumbnail.cpp
    AssetBrowser/Thumbnails/SourceThumbnail.h
    AssetBrowser/Views/AssetBrowserFolderWidget.cpp
    AssetBrowser/Views/AssetBrowserFolderWidget.h
    AssetBrowser/Views/AssetBrowserFolderWidget.qrc
    AssetBrowser/Views/AssetBrowserListView.cpp
    AssetBrowser/Views/AssetBrowserListView.h
    AssetBrowser/Views/AssetBrowserTableView.cpp
    AssetBrowser/Views/AssetBrowserTableView.h
    AssetBrowser/Views/AssetBrowserThumbnailView.cpp
    AssetBrowser/Views/AssetBrowserThumbnailView.h
    AssetBrowser/Views/AssetBrowserTreeViewDialog.cpp
    AssetBrowser/Views/AssetBrowserTreeViewDialog.h
    AssetBrowser/Views/AssetBrowserViewUtils.cpp
    AssetBrowser/Views/AssetBrowserViewUtils.h
    AssetBrowser/Views/EntryDelegate.cpp
    AssetBrowser/Views/EntryDelegate.h
    AssetBrowser/AssetBrowserComponent.cpp
    AssetBrowser/AssetBrowserComponent.h
    AssetBrowser/AssetBrowserEntityInspectorWidget.cpp
    AssetBrowser/AssetBrowserEntityInspectorWidget.h
    AssetBrowser/AssetBrowserFilterModel.cpp
    AssetBrowser/AssetBrowserFilterModel.h
    AssetBrowser/AssetBrowserListModel.cpp
    AssetBrowser/AssetBrowserListModel.h
    AssetBrowser/AssetBrowserModel.cpp
    AssetBrowser/AssetBrowserModel.h
    AssetBrowser/AssetBrowserTableViewProxyModel.cpp
    AssetBrowser/AssetBrowserTableViewProxyModel.h
    AssetBrowser/AssetBrowserThumbnailViewProxyModel.cpp
    AssetBrowser/AssetBrowserThumbnailViewProxyModel.h
    AssetBrowser/AssetBrowserTreeToTableProxyModel.cpp
    AssetBrowser/AssetBrowserTreeToTableProxyModel.h
    AssetBrowser/AssetEntryChangeset.cpp
    AssetBrowser/AssetEntryChangeset.h
    AssetBrowser/AssetSelectionModel.cpp
    AssetBrowser/AssetSelectionModel.h
    AssetBundle/AssetBundleComponent.cpp
    AssetBundle/AssetBundleComponent.h
    AssetCatalog/PlatformAddressedAssetCatalog.cpp
    AssetCatalog/PlatformAddressedAssetCatalog.h
    AssetCatalog/PlatformAddressedAssetCatalogManager.cpp
    AssetCatalog/PlatformAddressedAssetCatalogManager.h
    AssetDatabase/AssetDatabaseConnection.cpp
    AssetDatabase/AssetDatabaseConnection.h
    AssetDatabase/PathOrUuid.cpp
    AssetDatabase/PathOrUuid.h
    AssetEditor/AssetEditorHeader.cpp
    AssetEditor/AssetEditorHeader.h
    AssetEditor/AssetEditorStatusBar.ui
    AssetEditor/AssetEditorTab.cpp
    AssetEditor/AssetEditorTab.h
    AssetEditor/AssetEditorToolbar.ui
    AssetEditor/AssetEditorWidget.cpp
    AssetEditor/AssetEditorWidget.h
    Commands/ComponentModeCommand.cpp
    Commands/ComponentModeCommand.h
    Commands/EntityManipulatorCommand.cpp
    Commands/EntityManipulatorCommand.h
    Commands/SelectionCommand.cpp
    Commands/SelectionCommand.h
    Component/EditorComponentAPIComponent.cpp
    Component/EditorComponentAPIComponent.h
    Component/EditorLevelComponentAPIComponent.cpp
    Component/EditorLevelComponentAPIComponent.h
    ComponentMode/ComponentModeActionHandler.cpp
    ComponentMode/ComponentModeActionHandler.h
    ComponentMode/ComponentModeCollection.cpp
    ComponentMode/ComponentModeCollection.h
    ComponentMode/ComponentModeSwitcher.cpp
    ComponentMode/ComponentModeSwitcher.h
    ComponentMode/ComponentModeViewportUi.cpp
    ComponentMode/ComponentModeViewportUi.h
    ComponentMode/EditorBaseComponentMode.cpp
    ComponentMode/EditorBaseComponentMode.h
    ComponentModes/BaseShapeComponentMode.cpp
    ComponentModes/BaseShapeComponentMode.h
    ComponentModes/BaseShapeViewportEdit.cpp
    ComponentModes/BaseShapeViewportEdit.h
    ComponentModes/BoxComponentMode.cpp
    ComponentModes/BoxComponentMode.h
    ComponentModes/BoxViewportEdit.cpp
    ComponentModes/BoxViewportEdit.h
    ComponentModes/CapsuleComponentMode.cpp
    ComponentModes/CapsuleComponentMode.h
    ComponentModes/CapsuleViewportEdit.cpp
    ComponentModes/CapsuleViewportEdit.h
    ComponentModes/CylinderComponentMode.cpp
    ComponentModes/CylinderComponentMode.h
    ComponentModes/CylinderViewportEdit.cpp
    ComponentModes/CylinderViewportEdit.h
    ComponentModes/ShapeTranslationOffsetViewportEdit.cpp
    ComponentModes/ShapeTranslationOffsetViewportEdit.h
    ComponentModes/SphereComponentMode.cpp
    ComponentModes/SphereComponentMode.h
    ComponentModes/SphereViewportEdit.cpp
    ComponentModes/SphereViewportEdit.h
    ContainerEntity/ContainerEntitySystemComponent.cpp
    ContainerEntity/ContainerEntitySystemComponent.h

    Debug/TraceContextLogFormatter.cpp
    Debug/TraceContextLogFormatter.h
    Debug/TraceContextMultiStackHandler.cpp
    Debug/TraceContextMultiStackHandler.h
    Debug/TraceContextSingleStackHandler.cpp
    Debug/TraceContextSingleStackHandler.h
    Debug/TraceContextStack.cpp
    Debug/TraceContextStack.h
    Editor/ActionManagerUtils.cpp		
    Editor/ActionManagerUtils.h
    Editor/RichTextHighlighter.cpp
    Editor/RichTextHighlighter.h
    Entity/ReadOnly/ReadOnlyEntitySystemComponent.cpp
    Entity/ReadOnly/ReadOnlyEntitySystemComponent.h
    Entity/EditorEntityActionComponent.cpp
    Entity/EditorEntityActionComponent.h
    Entity/EditorEntityFixupComponent.cpp
    Entity/EditorEntityFixupComponent.h
    Entity/EditorEntityHelpers.cpp
    Entity/EditorEntityHelpers.h
    Entity/EditorEntityModel.cpp
    Entity/EditorEntityModel.h
    Entity/EditorEntityModelComponent.cpp
    Entity/EditorEntityModelComponent.h
    Entity/EditorEntitySearchComponent.cpp
    Entity/EditorEntitySearchComponent.h
    Entity/EditorEntitySortComponent.cpp
    Entity/EditorEntitySortComponent.h
    Entity/EditorEntitySortComponentSerializer.cpp
    Entity/EditorEntitySortComponentSerializer.h
    Entity/PrefabEditorEntityOwnershipService.cpp
    Entity/PrefabEditorEntityOwnershipService.h
    Entity/EditorEntityContextComponent.cpp
    Entity/EditorEntityContextComponent.h
    Entity/EntityUtilityComponent.cpp
    Entity/EntityUtilityComponent.h
	Fingerprinting/TypeFingerprinter.cpp
	Fingerprinting/TypeFingerprinter.h
	FocusMode/FocusModeSystemComponent.cpp
	FocusMode/FocusModeSystemComponent.h
	Input/QtEventToAzInputMapper.cpp
	Input/QtEventToAzInputMapper.h
	Logger/TraceLogger.cpp
	Logger/TraceLogger.h
	Manipulators/AngularManipulator.cpp
	Manipulators/AngularManipulator.h
    Manipulators/AngularManipulatorCircleViewFeedback.cpp	
    Manipulators/AngularManipulatorCircleViewFeedback.h
    Manipulators/LinearManipulator.cpp
    Manipulators/LinearManipulator.h	
    Manipulators/LineHoverSelection.cpp
    Manipulators/LineHoverSelection.h
    Manipulators/LineSegmentSelectionManipulator.cpp
    Manipulators/LineSegmentSelectionManipulator.h
    Manipulators/ManipulatorDebug.cpp
    Manipulators/ManipulatorDebug.h
    Manipulators/ManipulatorManager.cpp
    Manipulators/ManipulatorManager.h
    Manipulators/ManipulatorSnapping.cpp
    Manipulators/ManipulatorSnapping.h
    Manipulators/ManipulatorSpace.cpp
    Manipulators/ManipulatorSpace.h
    Manipulators/ManipulatorView.cpp
    Manipulators/ManipulatorView.h
    Manipulators/MultiLinearManipulator.cpp
    Manipulators/MultiLinearManipulator.h
    Manipulators/PaintBrushManipulator.cpp
    Manipulators/PaintBrushManipulator.h	
    Manipulators/PlanarManipulator.cpp
    Manipulators/PlanarManipulator.h
    Manipulators/RotationManipulators.cpp
    Manipulators/RotationManipulators.h
    Manipulators/ScaleManipulators.cpp
    Manipulators/ScaleManipulators.h
    Manipulators/SelectionManipulator.cpp
    Manipulators/SelectionManipulator.h
    Manipulators/SplineHoverSelection.cpp
    Manipulators/SplineHoverSelection.h
    Manipulators/SplineSelectionManipulator.cpp
    Manipulators/SplineSelectionManipulator.h
    Manipulators/SurfaceManipulator.cpp
    Manipulators/SurfaceManipulator.h
    Manipulators/TranslationManipulators.cpp
    Manipulators/TranslationManipulators.h
    Metadata/MetadataManager.cpp
    Metadata/MetadataManager.h
    Metadata/MetaUuidEntry.cpp
    Metadata/MetaUuidEntry.h
    Metadata/UuidUtils.cpp
    Metadata/UuidUtils.h	

    PaintBrush/GlobalPaintBrushSettings.cpp
    PaintBrush/GlobalPaintBrushSettings.h
    PaintBrush/GlobalPaintBrushSettingsSystemComponent.cpp
    PaintBrush/GlobalPaintBrushSettingsSystemComponent.h
    PaintBrush/GlobalPaintBrushSettingsWindow_Internals.h
    PaintBrush/GlobalPaintBrushSettingsWindow.cpp
    PaintBrush/GlobalPaintBrushSettingsWindow.h
    PaintBrush/PaintBrushSubModeCluster.cpp
    PaintBrush/PaintBrushSubModeCluster.h
    Picking/Manipulators/ManipulatorBoundManager.cpp
    Picking/Manipulators/ManipulatorBoundManager.h
    Picking/Manipulators/ManipulatorBounds.cpp
    Picking/Manipulators/ManipulatorBounds.h
    Prefab/DocumentPropertyEditor/PrefabComponentAdapter.cpp
    Prefab/DocumentPropertyEditor/PrefabComponentAdapter.h
    Prefab/DocumentPropertyEditor/PrefabOverrideLabelHandler.cpp
    Prefab/DocumentPropertyEditor/PrefabOverrideLabelHandler.h
    Prefab/Instance/Instance.cpp
    Prefab/Instance/Instance.h
    Prefab/Instance/InstanceDomGenerator.cpp
    Prefab/Instance/InstanceDomGenerator.h
    Prefab/Instance/InstanceEntityIdMapper.cpp
    Prefab/Instance/InstanceEntityIdMapper.h
    Prefab/Instance/InstanceEntityMapper.cpp
    Prefab/Instance/InstanceEntityMapper.h
    Prefab/Instance/InstanceEntityScrubber.cpp
    Prefab/Instance/InstanceEntityScrubber.h
    Prefab/Instance/InstanceSerializer.cpp
    Prefab/Instance/InstanceSerializer.h
    Prefab/Instance/InstanceToTemplatePropagator.cpp
    Prefab/Instance/InstanceToTemplatePropagator.h
    Prefab/Instance/InstanceUpdateExecutor.cpp
    Prefab/Instance/InstanceUpdateExecutor.h
    Prefab/Instance/TemplateInstanceMapper.cpp
    Prefab/Instance/TemplateInstanceMapper.h
    Prefab/Link/Link.cpp
    Prefab/Link/Link.h
    Prefab/Overrides/PrefabOverrideHandler.cpp
    Prefab/Overrides/PrefabOverrideHandler.h
    Prefab/Overrides/PrefabOverridePublicHandler.cpp
    Prefab/Overrides/PrefabOverridePublicHandler.h
    Prefab/EditorPrefabComponent.cpp
    Prefab/EditorPrefabComponent.h
    Prefab/Procedural/ProceduralPrefabAsset.cpp
    Prefab/Procedural/ProceduralPrefabAsset.h
    Prefab/Spawnable/EditorOnlyEntityHandler/EditorOnlyEntityHandler.cpp
    Prefab/Spawnable/EditorOnlyEntityHandler/EditorOnlyEntityHandler.h
    Prefab/Spawnable/EditorOnlyEntityHandler/UiEditorOnlyEntityHandler.cpp
    Prefab/Spawnable/EditorOnlyEntityHandler/UiEditorOnlyEntityHandler.h
    Prefab/Spawnable/EditorOnlyEntityHandler/WorldEditorOnlyEntityHandler.cpp
    Prefab/Spawnable/EditorOnlyEntityHandler/WorldEditorOnlyEntityHandler.h
    Prefab/Spawnable/AssetPlatformComponentRemover.cpp
    Prefab/Spawnable/AssetPlatformComponentRemover.h
    Prefab/Spawnable/ComponentRequirementsValidator.cpp
    Prefab/Spawnable/ComponentRequirementsValidator.h
    Prefab/Spawnable/EditorInfoRemover.cpp
    Prefab/Spawnable/EditorInfoRemover.h
    Prefab/Spawnable/InMemorySpawnableAssetUtils.cpp
    Prefab/Spawnable/InMemorySpawnableAssetUtils.h
    Prefab/Spawnable/PrefabCatchmentProcessor.cpp
    Prefab/Spawnable/PrefabCatchmentProcessor.h
    Prefab/Spawnable/PrefabConversionPipeline.cpp
    Prefab/Spawnable/PrefabConversionPipeline.h
    Prefab/Spawnable/PrefabDocument.cpp
    Prefab/Spawnable/PrefabDocument.h
    Prefab/Spawnable/PrefabDocument.inl
    Prefab/Spawnable/PrefabInMemorySpawnableConverter.cpp
    Prefab/Spawnable/PrefabInMemorySpawnableConverter.h
    Prefab/Spawnable/PrefabProcessorContext.cpp
    Prefab/Spawnable/PrefabProcessorContext.h
    Prefab/Spawnable/ProcesedObjectStore.cpp
    Prefab/Spawnable/ProcesedObjectStore.h
    Prefab/Spawnable/SpawnableMetaDataBuilder.cpp
    Prefab/Spawnable/SpawnableMetaDataBuilder.h
    Prefab/Spawnable/SpawnableUtils.cpp
    Prefab/Spawnable/SpawnableUtils.h
    Prefab/Template/Template.cpp
    Prefab/Template/Template.h
    Prefab/Undo/PrefabUndo.cpp
    Prefab/Undo/PrefabUndo.h
    Prefab/Undo/PrefabUndoAddEntity.cpp
    Prefab/Undo/PrefabUndoAddEntity.h
    Prefab/Undo/PrefabUndoAddEntityAsOverride.cpp
    Prefab/Undo/PrefabUndoAddEntityAsOverride.h
    Prefab/Undo/PrefabUndoApplyOverrides.cpp
    Prefab/Undo/PrefabUndoApplyOverrides.h
    Prefab/Undo/PrefabUndoBase.cpp
    Prefab/Undo/PrefabUndoBase.h
    Prefab/Undo/PrefabUndoComponentPropertyEdit.cpp
    Prefab/Undo/PrefabUndoComponentPropertyEdit.h
    Prefab/Undo/PrefabUndoComponentPropertyOverride.cpp
    Prefab/Undo/PrefabUndoComponentPropertyOverride.h
    Prefab/Undo/PrefabUndoDelete.cpp
    Prefab/Undo/PrefabUndoDelete.h
    Prefab/Undo/PrefabUndoDeleteAsOverride.cpp
    Prefab/Undo/PrefabUndoDeleteAsOverride.h
    Prefab/Undo/PrefabUndoRevertOverrides.cpp
    Prefab/Undo/PrefabUndoRevertOverrides.h
    Prefab/Undo/PrefabUndoUpdateLink.cpp
    Prefab/Undo/PrefabUndoUpdateLink.h
    Prefab/Undo/PrefabUndoUtils.cpp
    Prefab/Undo/PrefabUndoUtils.h
    Prefab/PrefabDomUtils.cpp
    Prefab/PrefabDomUtils.h
    Prefab/PrefabEditorPreferences.cpp
    Prefab/PrefabEditorPreferences.h
    Prefab/PrefabFocusHandler.cpp
    Prefab/PrefabFocusHandler.h
    Prefab/PrefabFocusUndo.cpp
    Prefab/PrefabFocusUndo.h
    Prefab/PrefabInstanceUtils.cpp
    Prefab/PrefabInstanceUtils.h
    Prefab/PrefabLoader.cpp
    Prefab/PrefabLoader.h
    Prefab/PrefabPublicHandler.cpp
    Prefab/PrefabPublicHandler.h
    Prefab/PrefabPublicNotificationHandler.cpp
    Prefab/PrefabPublicNotificationHandler.h
    Prefab/PrefabPublicRequestHandler.cpp
    Prefab/PrefabPublicRequestHandler.h	 
    Prefab/PrefabSystemComponent.cpp
    Prefab/PrefabSystemComponent.h	 
    Prefab/PrefabSystemScriptingHandler.cpp
    Prefab/PrefabSystemScriptingHandler.h
    Prefab/PrefabUndoCache.cpp
    Prefab/PrefabUndoCache.h
    Prefab/PrefabUndoHelpers.cpp
    Prefab/PrefabUndoHelpers.h
    Prefab/ProceduralPrefabSystemComponent.cpp
    Prefab/ProceduralPrefabSystemComponent.h
    Prefab/ScriptingPrefabLoader.cpp
    Prefab/ScriptingPrefabLoader.h
    PropertyTreeEditor/PropertyTreeEditor.cpp
    PropertyTreeEditor/PropertyTreeEditor.h
    PropertyTreeEditor/PropertyTreeEditorComponent.cpp
    PropertyTreeEditor/PropertyTreeEditorComponent.h
    PythonTerminal/ScriptHelpDialog.cpp
    PythonTerminal/ScriptHelpDialog.h
    PythonTerminal/ScriptHelpDialog.ui
    PythonTerminal/ScriptTermDialog.cpp
    PythonTerminal/ScriptTermDialog.h
    PythonTerminal/ScriptTermDialog.ui
    Render/EditorIntersectorComponent.cpp
    Render/EditorIntersectorComponent.h
    Script/LuaEditorSystemComponent.cpp
    Script/LuaEditorSystemComponent.h
    Script/LuaSymbolsReporterSystemComponent.cpp
    Script/LuaSymbolsReporterSystemComponent.h
    Slice/SliceCompilation.cpp
    Slice/SliceCompilation.h
    Slice/SliceDataFlagsCommand.cpp
    Slice/SliceDataFlagsCommand.h
    Slice/SliceDependencyBrowserComponent.cpp
    Slice/SliceDependencyBrowserComponent.h
    Slice/SliceMetadataEntityContextComponent.cpp
    Slice/SliceMetadataEntityContextComponent.h
    Slice/SliceRelationshipNode.cpp
    Slice/SliceRelationshipNode.h
    Slice/SliceRequestComponent.cpp
    Slice/SliceRequestComponent.h
    Slice/SliceTransaction.cpp
    Slice/SliceTransaction.h
    Slice/SliceUtilities.cpp
    Slice/SliceUtilities.h

    PropertyTreeEditor/PropertyTreeEditor.cpp
    PropertyTreeEditor/PropertyTreeEditor.h
    PropertyTreeEditor/PropertyTreeEditorComponent.cpp
    PropertyTreeEditor/PropertyTreeEditorComponent.h
    PythonTerminal/ScriptHelpDialog.cpp
    PythonTerminal/ScriptHelpDialog.h
    PythonTerminal/ScriptHelpDialog.ui
    PythonTerminal/ScriptTermDialog.cpp
    PythonTerminal/ScriptTermDialog.h
    PythonTerminal/ScriptTermDialog.ui
    Render/EditorIntersectorComponent.cpp
    Render/EditorIntersectorComponent.h
    Script/LuaEditorSystemComponent.cpp
    Script/LuaEditorSystemComponent.h
    Script/LuaSymbolsReporterSystemComponent.cpp
    Script/LuaSymbolsReporterSystemComponent.h
    Slice/SliceCompilation.cpp
    Slice/SliceCompilation.h
    Slice/SliceDataFlagsCommand.cpp
    Slice/SliceDataFlagsCommand.h
    Slice/SliceDependencyBrowserComponent.cpp
    Slice/SliceDependencyBrowserComponent.h
    Slice/SliceMetadataEntityContextComponent.cpp
    Slice/SliceMetadataEntityContextComponent.h
    Slice/SliceRelationshipNode.cpp
    Slice/SliceRelationshipNode.h
    Slice/SliceRequestComponent.cpp
    Slice/SliceRequestComponent.h
    Slice/SliceTransaction.cpp
    Slice/SliceTransaction.h
    Slice/SliceUtilities.cpp
    Slice/SliceUtilities.h
    SourceControl/PerforceConnection.cpp
    SourceControl/PerforceConnection.h
    SourceControl/LocalFileSCComponent.cpp
    SourceControl/LocalFileSCComponent.h
    SourceControl/PerforceComponent.cpp
    SourceControl/PerforceComponent.h
    SourceControl/PerforceSettings.cpp
    SourceControl/PerforceSettings.h
    SourceControl/PerforceSettings.ui
    SourceControl/QtSourceControlNotificationHandler.cpp
    SourceControl/QtSourceControlNotificationHandler.h
    SQLite/SQLiteConnection.cpp
    SQLite/SQLiteConnection.h
    SQLite/SQLiteQuery.cpp
    SQLite/SQLiteQuery.h
    Thumbnails/LoadingThumbnail.cpp
    Thumbnails/LoadingThumbnail.h
    Thumbnails/MissingThumbnail.cpp
    Thumbnails/MissingThumbnail.h 
    Thumbnails/SourceControlThumbnail.cpp
    Thumbnails/SourceControlThumbnail.h
    Thumbnails/Thumbnail.cpp
    Thumbnails/Thumbnail.h
    Thumbnails/Thumbnail.inl
    Thumbnails/ThumbnailerComponent.cpp
    Thumbnails/ThumbnailerComponent.h
    Thumbnails/ThumbnailerNullComponent.cpp
    Thumbnails/ThumbnailerNullComponent.h
    Thumbnails/ThumbnailWidget.cpp
    Thumbnails/ThumbnailWidget.h
    ToolsComponents/AzToolsFrameworkConfigurationSystemComponent.cpp
    ToolsComponents/AzToolsFrameworkConfigurationSystemComponent.h
    ToolsComponents/ComponentAssetMimeDataContainer.cpp
    ToolsComponents/ComponentAssetMimeDataContainer.h
    ToolsComponents/ComponentMimeData.cpp
    ToolsComponents/ComponentMimeData.h
    ToolsComponents/EditorAssetMimeDataContainer.cpp
    ToolsComponents/EditorAssetMimeDataContainer.h
    ToolsComponents/EditorAssetReference.cpp
    ToolsComponents/EditorAssetReference.h
    ToolsComponents/EditorComponentBase.cpp
    ToolsComponents/EditorComponentBase.h
    ToolsComponents/EditorDisabledCompositionComponent.cpp
    ToolsComponents/EditorDisabledCompositionComponent.h
    ToolsComponents/EditorEntityIconComponent.cpp
    ToolsComponents/EditorEntityIconComponent.h
    ToolsComponents/EditorEntityIdContainer.cpp
    ToolsComponents/EditorEntityIdContainer.h
    ToolsComponents/EditorInspectorComponent.cpp
    ToolsComponents/EditorInspectorComponent.h
    ToolsComponents/EditorLockComponent.cpp
    ToolsComponents/EditorLockComponent.h
    ToolsComponents/EditorNonUniformScaleComponent.cpp
    ToolsComponents/EditorNonUniformScaleComponent.h
    ToolsComponents/EditorNonUniformScaleComponentMode.cpp
    ToolsComponents/EditorNonUniformScaleComponentMode.h
    ToolsComponents/EditorOnlyEntityComponent.cpp
    ToolsComponents/EditorOnlyEntityComponent.h
    ToolsComponents/EditorPendingCompositionComponent.cpp
    ToolsComponents/EditorPendingCompositionComponent.h
    ToolsComponents/EditorSelectionAccentSystemComponent.cpp
    ToolsComponents/EditorSelectionAccentSystemComponent.h
    ToolsComponents/EditorVisibilityComponent.cpp
    ToolsComponents/EditorVisibilityComponent.h
    ToolsComponents/GenericComponentWrapper.cpp
    ToolsComponents/GenericComponentWrapper.h
    ToolsComponents/ScriptEditorComponent.cpp
    ToolsComponents/ScriptEditorComponent.h
    ToolsComponents/SelectionComponent.cpp
    ToolsComponents/SelectionComponent.h
    ToolsComponents/ToolsAssetCatalogComponent.cpp
    ToolsComponents/ToolsAssetCatalogComponent.h
    ToolsComponents/TransformComponent.cpp
    ToolsComponents/TransformComponent.h
    ToolsComponents/TransformComponentSerializer.cpp
    ToolsComponents/TransformComponentSerializer.h

        
    AzToolsFrameworkModule.cpp
    AzToolsFrameworkModule.h
)

# Prevent the following files from being grouped in UNITY builds
set(SKIP_UNITY_BUILD_INCLUSION_FILES
    # The following files are skipped from unity to avoid duplicated symbols related to an ebus
    AzToolsFrameworkModule.cpp
    Application/ToolsApplication.cpp
#    UI/PropertyEditor/PropertyEntityIdCtrl.cpp
#    UI/PropertyEditor/PropertyManagerComponent.cpp
#    ViewportSelection/EditorDefaultSelection.cpp
#    ViewportSelection/EditorInteractionSystemComponent.cpp
#    ViewportSelection/EditorTransformComponentSelection.cpp
)
