#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    ActionManager/Action/ActionManagerInterface.h
    ActionManager/Action/ActionManagerInternalInterface.h
    ActionManager/Action/EditorActionUtils.h
    ActionManager/HotKey/HotKeyManagerInterface.h
    ActionManager/HotKey/HotKeyManagerInternalInterface.h
    ActionManager/HotKey/HotKeyWidgetRegistrationInterface.h
    ActionManager/Menu/MenuManagerInterface.h
    ActionManager/Menu/MenuManagerInternalInterface.h
    ActionManager/ToolBar/ToolBarManagerInterface.h
    ActionManager/ToolBar/ToolBarManagerInternalInterface.h
    AssetEditor/AssetEditorWindowSettings.cpp
    AssetEditor/AssetEditorWindowSettings.h
    AssetEditor/AssetEditorUtils.h
    AssetEditor/Resources/AssetEditorResources.qrc
    UI/LegacyFramework/Resources/sharedResources.qrc
    UI/PropertyEditor/Resources/Icons.qrc
    API/AssetSystemJobInfo.cpp
    API/AssetSystemJobInfo.h
    API/EditorAssetSystemAPI.h
    API/ComponentModeCollectionInterface.h
    API/EntityCompositionRequest.cpp
    API/EntityCompositionRequest.h    
    API/EditorEntityAPI.h
    API/EditorPythonInterface.h
    API/EditorViewportIconDisplayInterface.h
    API/PythonLoader.h
    API/PythonLoader.cpp
    API/SettingsRegistryUtils.h
    API/ViewPaneOptions.h
    API/ViewportEditorModeTrackerInterface.h
    AssetBundle/AssetBundleAPI.h
    Debug/TraceContext.inl
    Debug/TraceContext.h
    Debug/TraceContextStackInterface.h
    Component/EditorComponentAPIBus.h
    Component/EditorLevelComponentAPIBus.h
    ContainerEntity/ContainerEntityInterface.h
    ContainerEntity/ContainerEntityNotificationBus.h
    Editor/ActionManagerIdentifiers/EditorActionUpdaterIdentifiers.h
    Editor/ActionManagerIdentifiers/EditorContextIdentifiers.h
    Editor/ActionManagerIdentifiers/EditorMenuIdentifiers.h
    Editor/ActionManagerIdentifiers/EditorToolBarIdentifiers.h
    Entity/EditorEntityStartStatus.h
    Entity/EditorEntityContextBus.h
    Entity/EditorEntityContextPickingBus.h
    Entity/EditorEntityModelBus.h
    Entity/EditorEntityRuntimeActivationBus.h
    Entity/EditorEntitySearchBus.h
    Entity/EditorEntitySortBus.h
    Entity/EditorEntityTransformBus.h
    Entity/PrefabEditorEntityOwnershipInterface.h
    Entity/EntityTypes.h
    Entity/ReadOnly/ReadOnlyEntityInterface.h
    Entity/ReadOnly/ReadOnlyEntityBus.h
    FocusMode/FocusModeInterface.h
    FocusMode/FocusModeNotificationBus.h
    Manipulators/BoxManipulatorRequestBus.h
    Manipulators/CapsuleManipulatorRequestBus.h
    Manipulators/CylinderManipulatorRequestBus.h
    Manipulators/EditorVertexSelectionBus.h
    Manipulators/HoverSelection.h
    Manipulators/ManipulatorBus.h
    Manipulators/RadiusManipulatorRequestBus.h
    Manipulators/ShapeManipulatorRequestBus.h
    Maths/TransformUtils.h
    PaintBrush/GlobalPaintBrushSettingsNotificationBus.h
    PaintBrush/GlobalPaintBrushSettingsRequestBus.h
    Picking/BoundInterface.h
    Picking/ContextBoundAPI.h
    SourceControl/SourceControlAPI.h
    ToolsComponents/EditorComponentAdapter.inl
    ToolsComponents/EditorComponentAdapter.h
    UI/DocumentPropertyEditor/IPropertyEditor.h
    UI/DocumentPropertyEditor/PropertyEditorToolsSystemInterface.h
    UI/Logging/LoggingCommon.h
    UI/PropertyEditor/QtWidgetLimits.h
    UI/PropertyEditor/PropertyIntCtrlCommon.h
    UI/PropertyEditor/PropertyQTConstants.h
    UI/LegacyFramework/CustomMenus/CustomMenusAPI.h
    UI/LegacyFramework/CustomMenus/CustomMenusComponent.cpp
    Viewport/ActionBus.h
    Viewport/VertexContainerDisplayDefaults.cpp
    Viewport/VertexContainerDisplayDefaults.h
    Viewport/ViewBookmarkLoaderInterface.h
    ViewportUi/ViewportUiRequestBus.h
    ComponentMode/ComponentModeDelegate.h
    ComponentMode/ComponentModeDelegate.cpp
    ComponentMode/ComponentModeViewportUiRequestBus.h
    ComponentModes/ShapeComponentModeBus.h
    ComponentModes/ViewportEditUtilities.h
    ViewportSelection/EditorInteractionSystemViewportSelectionRequestBus.h
    ViewportSelection/EditorTransformComponentSelectionRequestBus.h
    ViewportSelection/EditorTransformComponentSelectionRequestBus.cpp
    ViewportSelection/EditorVisibleEntityDataCache.h
    ViewportSelection/EditorVisibleEntityDataCache.cpp
    ToolsFileUtils/ToolsFileUtils.h
     AssetBrowser/AssetBrowserEntry.h
    AssetBrowser/AssetBrowserFilterModel.cpp
    AssetBrowser/AssetBrowserFilterModel.h
    AssetBrowser/AssetEntryChange.h
    AssetBrowser/EBusFindAssetTypeByName.h
    AssetBrowser/Search/search.qrc
    AssetBrowser/Previewer/PreviewerFactory.h
    Archive/ArchiveAPI.h
    Prefab/DocumentPropertyEditor/PrefabPropertyEditorNodes.h
    Prefab/DocumentPropertyEditor/Resources/OverrideResources.qrc
    Prefab/PrefabDomTypes.h
    Prefab/PrefabFocusInterface.h
    Prefab/PrefabFocusNotificationBus.h
    Prefab/PrefabFocusPublicInterface.h
    Prefab/PrefabIdTypes.h
    Prefab/PrefabLoaderInterface.cpp    
    Prefab/PrefabLoaderInterface.h
    Prefab/PrefabLoaderScriptingBus.h
    Prefab/PrefabSystemComponentInterface.h
    Prefab/ProceduralPrefabSystemComponentInterface.h
    Prefab/Instance/InstanceDomGeneratorInterface.h
    Prefab/Instance/InstanceEntityMapperInterface.h
    Prefab/Instance/InstanceToTemplateInterface.h
    Prefab/Instance/InstanceUpdateExecutorInterface.h
    Prefab/Instance/TemplateInstanceMapperInterface.h
    Prefab/Overrides/PrefabOverridePublicInterface.h
    Prefab/Overrides/PrefabOverrideTypes.h
    Prefab/PrefabPublicInterface.h
    Prefab/PrefabPublicRequestBus.h
    Prefab/PrefabSettings.h
    Prefab/Spawnable/EntityAliasTypes.h
    Prefab/Spawnable/EntityIdPathMapperInterface.h
    Prefab/Spawnable/PrefabConverterStackProfileNames.h
    Prefab/Spawnable/PrefabProcessor.h
    Prefab/Undo/PrefabUndoEntityOverrides.h
    Prefab/Undo/PrefabUndoEntityOverrides.cpp
    UI/Outliner/EntityOutlinerDragAndDropContext.h
    UI/Outliner/resources.qrc
    UI/EditorEntityUi/EditorEntityUiInterface.h
    UI/Prefab/ActionManagerIdentifiers/PrefabActionUpdaterIdentifiers.h
    UI/Prefab/PrefabIntegrationInterface.h
    UI/Prefab/Constants.h
    Script/LuaSymbolsReporter.cpp
    Script/LuaSymbolsReporter.h
)
