#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
	ActionManager/Action/ActionManagerNotificationBus.cpp
	ActionManager/Action/ActionManagerNotificationBus.h
	ActionManager/ActionManagerRegistrationNotificationBus.cpp
    ActionManager/ActionManagerRegistrationNotificationBus.h
    API/AssetDatabaseBus.cpp
    API/AssetDatabaseBus.h
    API/ComponentEntityObjectBus.cpp
    API/ComponentEntityObjectBus.h
    API/ComponentEntitySelectionBus.cpp
    API/ComponentEntitySelectionBus.h 
	API/EditorAnimationSystemRequestBus.cpp
    API/EditorAnimationSystemRequestBus.h
	API/EditorAssetSystemBus.cpp
	API/EditorAssetSystemBus.h
    API/EditorCameraBus.cpp
    API/EditorCameraBus.h
    API/EditorLevelNotificationBus.cpp
    API/EditorLevelNotificationBus.h
    API/EditorPythonConsoleBus.cpp
    API/EditorPythonConsoleBus.h
    API/EditorPythonRunnerRequestsBus.cpp
    API/EditorPythonRunnerRequestsBus.h
    API/EditorPythonScriptNotificationsBus.cpp
    API/EditorPythonScriptNotificationsBus.h
    API/EditorWindowRequestBus.cpp
    API/EditorWindowRequestBus.h
    API/EntityCompositionNotificationBus.cpp
    API/EntityCompositionNotificationBus.h
    API/EntityCompositionRequestBus.cpp
    API/EntityCompositionRequestBus.h
    API/EntityPropertyEditorNotificationBus.cpp
    API/EntityPropertyEditorNotificationBus.h
    API/EntityPropertyEditorRequestsBus.cpp
    API/EntityPropertyEditorRequestsBus.h
    API/ToolsApplicationBus.cpp
    API/ToolsApplicationBus.h
    API/ViewportEditorModeTrackerNotificationBus.cpp
    API/ViewportEditorModeTrackerNotificationBus.h
    AssetBrowser/AssetBrowserBus.cpp
    AssetBrowser/AssetBrowserBus.h
	AssetBrowser/Previewer/PreviewerBus.cpp
	AssetBrowser/Previewer/PreviewerBus.h
    AssetCatalog/PlatformAddressedAssetCatalogBus.cpp
    AssetCatalog/PlatformAddressedAssetCatalogBus.h
    AssetEditor/AssetEditorBus.cpp
    AssetEditor/AssetEditorBus.h
	Component/EditorComponentAPIBus.cpp
	Component/EditorComponentAPIBus.h
	Component/EditorLevelComponentAPIBus.cpp
	Component/EditorLevelComponentAPIBus.h
	ComponentMode/ComponentModeDelegateBus.cpp
	ComponentMode/ComponentModeDelegateBus.h
	ComponentMode/ComponentModeViewportUiRequestBus.cpp
	ComponentMode/ComponentModeViewportUiRequestBus.h
    ComponentMode/EditorComponentModeBus.cpp
    ComponentMode/EditorComponentModeBus.h
	ContainerEntity/ContainerEntityNotificationBus.cpp
	ContainerEntity/ContainerEntityNotificationBus.h
	Editor/EditorSettingsAPIBus.cpp
	Editor/EditorSettingsAPIBus.h
	Entity/EditorEntityAPIBus.cpp
	Entity/EditorEntityAPIBus.h
	Entity/EditorEntityContextPickingBus.cpp
	Entity/EditorEntityContextPickingBus.h
    Entity/EditorEntityContextBus.cpp
    Entity/EditorEntityContextBus.h
    Entity/EditorEntityInfoBus.cpp
    Entity/EditorEntityInfoBus.h
	Entity/EditorEntityModelBus.cpp
	Entity/EditorEntityModelBus.h
	Entity/EditorEntityRuntimeActivationBus.cpp
	Entity/EditorEntityRuntimeActivationBus.h
	Entity/EditorEntitySearchBus.cpp
	Entity/EditorEntitySearchBus.h
	Entity/EditorEntitySortBus.cpp
	Entity/EditorEntitySortBus.h
	Entity/EditorEntityTransformBus.cpp
	Entity/EditorEntityTransformBus.h
	FocusMode/FocusModeNotificationBus.cpp
	FocusMode/FocusModeNotificationBus.h
	Manipulators/BoxManipulatorRequestBus.cpp
	Manipulators/BoxManipulatorRequestBus.h
	Manipulators/CapsuleManipulatorRequestBus.cpp
	Manipulators/CapsuleManipulatorRequestBus.h
	Manipulators/CylinderManipulatorRequestBus.cpp
	Manipulators/CylinderManipulatorRequestBus.h
	Manipulators/EditorVertexSelectionBus.cpp
	Manipulators/EditorVertexSelectionBus.h
	Manipulators/ManipulatorBus.cpp
	Manipulators/ManipulatorBus.h
	Manipulators/RadiusManipulatorRequestBus.cpp
	Manipulators/RadiusManipulatorRequestBus.h
	Manipulators/ShapeManipulatorRequestBus.cpp
	Manipulators/ShapeManipulatorRequestBus.h
	PaintBrush/GlobalPaintBrushSettingsNotificationBus.cpp
	PaintBrush/GlobalPaintBrushSettingsNotificationBus.h
	PaintBrush/GlobalPaintBrushSettingsRequestBus.cpp
	PaintBrush/GlobalPaintBrushSettingsRequestBus.h	
	Prefab/PrefabFocusNotificationBus.cpp
	Prefab/PrefabFocusNotificationBus.h
	Prefab/PrefabLoaderScriptingBus.cpp
	Prefab/PrefabLoaderScriptingBus.h
    Prefab/PrefabPublicNotificationBus.cpp
    Prefab/PrefabPublicNotificationBus.h
	Prefab/PrefabPublicRequestBus.cpp
	Prefab/PrefabPublicRequestBus.h
	Prefab/PrefabSystemScriptingBus.cpp
	Prefab/PrefabSystemScriptingBus.h
	Prefab/Spawnable/PrefabToInMemorySpawnableNotificationBus.cpp
	Prefab/Spawnable/PrefabToInMemorySpawnableNotificationBus.h
	Script/LuaSymbolsReporterBus.cpp
	Script/LuaSymbolsReporterBus.h
	
	Slice/SliceDependencyBrowserBus.cpp
	Slice/SliceDependencyBrowserBus.h
	Slice/SliceMetadataEntityContextBus.cpp
	Slice/SliceMetadataEntityContextBus.h
	Slice/SliceRequestBus.cpp
	Slice/SliceRequestBus.h
	SQLite/SQLiteQueryLogBus.cpp
	SQLite/SQLiteQueryLogBus.h
    Thumbnails/SourceControlThumbnailBus.cpp
    Thumbnails/SourceControlThumbnailBus.h
	Thumbnails/ThumbnailerBus.cpp
	Thumbnails/ThumbnailerBus.h
	ToolsComponents/EditorComponentBus.cpp
    ToolsComponents/EditorComponentBus.h
	ToolsComponents/EditorDisabledCompositionBus.cpp
	ToolsComponents/EditorDisabledCompositionBus.h
	ToolsComponents/EditorInspectorComponentBus.cpp
	ToolsComponents/EditorInspectorComponentBus.h
	ToolsComponents/EditorLockComponentBus.cpp
	ToolsComponents/EditorLockComponentBus.h
	ToolsComponents/EditorOnlyEntityComponentBus.cpp
	ToolsComponents/EditorOnlyEntityComponentBus.h
	ToolsComponents/EditorPendingCompositionBus.cpp
	ToolsComponents/EditorPendingCompositionBus.h
	ToolsComponents/EditorSelectionAccentingBus.cpp
	ToolsComponents/EditorSelectionAccentingBus.h
	ToolsComponents/EditorVisibilityBus.cpp
	ToolsComponents/EditorVisibilityBus.h
	ToolsComponents/ToolsAssetCatalogBus.cpp
	ToolsComponents/ToolsAssetCatalogBus.h
	ToolsComponents/TransformComponentBus.cpp
	ToolsComponents/TransformComponentBus.h
	ToolsMessaging/EntityHighlightBus.cpp
	ToolsMessaging/EntityHighlightBus.h
	UI/Outliner/EntityOutlinerCacheBus.cpp
	UI/Outliner/EntityOutlinerCacheBus.h
	UI/Outliner/EntityOutlinerRequestBus.cpp
	UI/Outliner/EntityOutlinerRequestBus.h
	UI/Prefab/PrefabIntegrationBus.cpp
	UI/Prefab/PrefabIntegrationBus.h
	UI/Notifications/ToastBus.cpp
	UI/Notifications/ToastBus.h
	Viewport/ActionBus.cpp
	Viewport/ActionBus.h
	Viewport/ViewportMessagesBus.cpp
    Viewport/ViewportMessagesBus.h
	ViewportSelection/EditorTransformComponentSelectionRequestBus.h
    ViewportSelection/EditorTransformComponentSelectionRequestBus.cpp

    AzToolsFrameworkEBus.cpp    
)

# Prevent the following files from being grouped in UNITY builds
set(SKIP_UNITY_BUILD_INCLUSION_FILES
)
