/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */
#pragma once

#include <AzCore/PlatformDef.h> ///< Platform/compiler specific defines

#if defined(AZ_MONOLITHIC_BUILD)
    #define AZTF_API
    #define AZTF_TEMPLATE_EXTERN
    #define AZTF_API_EXTERN           extern
#else
    #if defined(AZTF_EXPORTS)
        #define AZTF_API        AZ_DLL_EXPORT
        #define AZTF_TEMPLATE_EXTERN  AZ_TRAIT_OS_TEMPLATE_EXTERN
        #define AZTF_API_EXTERN       AZ_TRAIT_OS_TEMPLATE_EXTERN
        #define AZTF_API_EXPORT       AZ_DLL_EXPORT
    #else
        #define AZTF_API              AZ_DLL_IMPORT
        #define AZTF_TEMPLATE_EXTERN  AZ_TRAIT_OS_TEMPLATE_EXTERN
        #define AZTF_API_EXTERN       AZ_TRAIT_OS_TEMPLATE_EXTERN
        #define AZTF_API_EXPORT       
    #endif
#endif

#if defined(AZ_MONOLITHIC_BUILD)

#define AZTF_DECLARE_EBUS_SINGLE_ADDRESS(a)                     AZ_DECLARE_EBUS_EXTERN_SINGLE_ADDRESS(a)
#define AZTF_INSTANTIATE_EBUS_SINGLE_ADDRESS(a)                 AZ_DECLARE_EBUS_INSTANTIATION_SINGLE_ADDRESS(a)
#define AZTF_DECLARE_EBUS_MULTI_ADDRESS(a)                      AZ_DECLARE_EBUS_EXTERN_MULTI_ADDRESS(a)
#define AZTF_INSTANTIATE_EBUS_MULTI_ADDRESS(a)                  AZ_DECLARE_EBUS_INSTANTIATION_MULTI_ADDRESS(a)
#define AZTF_DECLARE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(a, b)      AZ_DECLARE_EBUS_EXTERN_SINGLE_ADDRESS_WITH_TRAITS(a, b)
#define AZTF_INSTANTIATE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(a, b)  AZ_DECLARE_EBUS_INSTANTIATION_SINGLE_ADDRESS_WITH_TRAITS(a, b)
#define AZTF_DECLARE_EBUS_MULTI_ADDRESS_WITH_TRAITS(a, b)       AZ_DECLARE_EBUS_EXTERN_MULTI_ADDRESS_WITH_TRAITS(a, b)
#define AZTF_INSTANTIATE_EBUS_MULTI_ADDRESS_WITH_TRAITS(a, b)   AZ_DECLARE_EBUS_INSTANTIATION_MULTI_ADDRESS_WITH_TRAITS(a, b) 

#else

#define AZTF_DECLARE_EBUS_SINGLE_ADDRESS(a)                     AZ_DECLARE_EBUS_EXTERN_SINGLE_ADDRESS(AZTF_API, a) 
#define AZTF_INSTANTIATE_EBUS_SINGLE_ADDRESS(a)                 AZ_DECLARE_EBUS_INSTANTIATION_SINGLE_ADDRESS(AZTF_API, a)
#define AZTF_DECLARE_EBUS_MULTI_ADDRESS(a)                      AZ_DECLARE_EBUS_EXTERN_MULTI_ADDRESS(AZTF_API, a)
#define AZTF_INSTANTIATE_EBUS_MULTI_ADDRESS(a)                  AZ_DECLARE_EBUS_INSTANTIATION_MULTI_ADDRESS(AZTF_API, a)
#define AZTF_DECLARE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(a, b)      AZ_DECLARE_EBUS_EXTERN_SINGLE_ADDRESS_WITH_TRAITS(AZTF_API, a, b)
#define AZTF_INSTANTIATE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(a, b)  AZ_DECLARE_EBUS_INSTANTIATION_SINGLE_ADDRESS_WITH_TRAITS(AZTF_API, a, b)
#define AZTF_DECLARE_EBUS_MULTI_ADDRESS_WITH_TRAITS(a, b)       AZ_DECLARE_EBUS_EXTERN_MULTI_ADDRESS_WITH_TRAITS(AZTF_API, a, b)
#define AZTF_INSTANTIATE_EBUS_MULTI_ADDRESS_WITH_TRAITS(a, b)   AZ_DECLARE_EBUS_INSTANTIATION_MULTI_ADDRESS_WITH_TRAITS(AZTF_API, a, b)

#endif //defined(AZ_MONOLITHIC_BUILD)
