#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    AzCore/IO/SystemFile_Platform.h
    AzCore/IO/Streamer/StorageDrive_Windows.h
    AzCore/IO/Streamer/StorageDrive_Windows.cpp
    AzCore/IO/Streamer/StorageDriveConfig_Windows.h
    AzCore/IO/Streamer/StorageDriveConfig_Windows.cpp
    AzCore/IO/Streamer/StreamerConfiguration_Windows.h
    AzCore/IO/Streamer/StreamerConfiguration_Windows.cpp
    AzCore/IO/Streamer/StreamerContext_Platform.h
    AzCore/IPC/SharedMemory_Platform.h
    AzCore/IPC/SharedMemory_Windows.h
    AzCore/IPC/SharedMemory_Windows.cpp
    AzCore/Math/Random_Platform.h
    AzCore/Module/Internal/ModuleManagerSearchPathTool_Windows.cpp
    AzCore/NativeUI/NativeUISystemComponent_Windows.cpp
    AzCore/Socket/AzSocket_Platform.h
    AzCore/Socket/AzSocket_fwd_Platform.h
    AzCore/Socket/AzSocket_fwd_Windows.h
    ../Common/WinAPI/AzCore/Module/DynamicModuleHandle_WinAPI.cpp
    ../Common/WinAPI/AzCore/Process/ProcessInfo_WinAPI.cpp
    ../Common/WinAPI/AzCore/Socket/AzSocket_fwd_WinAPI.h
    ../Common/WinAPI/AzCore/Socket/AzSocket_WinAPI.cpp
    ../Common/WinAPI/AzCore/Socket/AzSocket_WinAPI.h
    ../Common/WinAPI/AzCore/IO/AnsiTerminalUtils_WinAPI.cpp
    AzCore/AzCore_Traits_Platform.h
    AzCore/AzCore_Traits_Windows.h
    AzCore/base_Platform.h
    AzCore/base_Windows.h
    AzCore/PlatformId/PlatformId_Platform.h
    AzCore/PlatformId/PlatformId_Windows.h
    ../Common/VisualStudio/AzCore/Natvis/azcore.natvis
    ../Common/VisualStudio/AzCore/Natvis/azcore.natstepfilter
    ../Common/VisualStudio/AzCore/Natvis/azcore.natjmc
    ../Common/VisualStudio/AzCore/Natvis/rapidjson.natvis
    AzCore/Debug/StackTracer_Windows.cpp
    ../Common/WinAPI/AzCore/Debug/Trace_WinAPI.cpp
    ../Common/WinAPI/AzCore/IO/Streamer/StreamerContext_WinAPI.cpp
    ../Common/WinAPI/AzCore/IO/Streamer/StreamerContext_WinAPI.h
    ../Common/WinAPI/AzCore/Memory/OSAllocator_WinAPI.h
    AzCore/Memory/OSAllocator_Platform.h
    AzCore/Math/Internal/MathTypes_Windows.h
    AzCore/Platform_Windows.cpp
    AzCore/PlatformIncl_Platform.h
    AzCore/PlatformIncl_Windows.h
    AzCore/Serialization/Locale_Platform.h
    AzCore/Settings/CommandLineParser_Platform.h
    ../Common/WinAPI/AzCore/Serialization/Locale_WinAPI.h
    ../Common/WinAPI/AzCore/Serialization/Locale_WinAPI.cpp
    ../Common/WinAPI/AzCore/Settings/CommandLineParser_WinAPI.cpp
    ../Common/WinAPI/AzCore/Settings/CommandLineParser_WinAPI.h
    ../Common/WinAPI/AzCore/Socket/AzSocket_fwd_WinAPI.h
    ../Common/WinAPI/AzCore/Socket/AzSocket_WinAPI.cpp
    ../Common/WinAPI/AzCore/Socket/AzSocket_WinAPI.h
    AzCore/Socket/AzSocket_Platform.h
    AzCore/Socket/AzSocket_fwd_Platform.h
    AzCore/Socket/AzSocket_fwd_Windows.h
    AzCore/Debug/Profiler_Platform.inl
    ../Common/WinAPI/AzCore/Debug/Profiler_WinAPI.inl
    AzCore/Math/Random_Windows.cpp
    AzCore/Math/Random_Windows.h
    ../Common/WinAPI/AzCore/Utils/Utils_WinAPI.cpp
    AzCore/Utils/Utils_Windows.cpp
    ../Common/WinAPI/AzCore/IO/FileIO_WinAPI.cpp
    ../Common/WinAPI/AzCore/IO/SystemFile_WinAPI.cpp

)
