#
# Copyright (c) Contributors to the Open 3D Engine Project. For complete copyright and license terms please see the LICENSE at the root of this distribution.
# 
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    TerrainPainterPanel.cpp
    TerrainPainterPanel.h
    TerrainPainterPanel.ui
    NewTerrainDialog.cpp
    NewTerrainDialog.h
    NewTerrainDialog.ui
    TerrainTextureExport.cpp
    TerrainTextureExport.h
    TerrainTextureExport.ui
    Terrain/Clouds.cpp
    Terrain/GenerationParam.cpp
    Terrain/GenerationParam.ui
    Terrain/Heightmap.cpp
    Terrain/Layer.cpp
    Terrain/Noise.cpp
    Terrain/PythonTerrainFuncs.cpp
    Terrain/PythonTerrainLayerFuncs.cpp
    Terrain/RGBLayer.cpp
    Terrain/SurfaceType.cpp
    Terrain/TerrainConverter.cpp
    Terrain/TerrainGrid.cpp
    Terrain/TerrainLayerTexGen.cpp
    Terrain/TerrainLightGen.cpp
    Terrain/TerrainManager.cpp
    Terrain/TerrainTexGen.cpp
    Terrain/TextureCompression.cpp
    Terrain/MacroTextureExporter.cpp
    Terrain/Clouds.h
    Terrain/GenerationParam.h
    Terrain/Heightmap.h
    Terrain/Layer.h
    Terrain/LayerWeight.h
    Terrain/Noise.h
    Terrain/RGBLayer.h
    Terrain/SurfaceType.h
    Terrain/TerrainConverter.h
    Terrain/TerrainGrid.h
    Terrain/TerrainLayerTexGen.h
    Terrain/TerrainLightGen.h
    Terrain/TerrainManager.h
    Terrain/TerrainTexGen.h
    Terrain/LayerWeight.cpp
    Terrain/TextureCompression.h
    Terrain/MacroTextureExporter.h
    TerrainDialog.cpp
    TerrainDialog.h
    TerrainDialog.ui
    TerrainTexture.cpp
    TerrainTexture.h
    TerrainTexture.ui
    Terrain/SkyAccessibility/HeightmapAccessibility.h
    Terrain/SkyAccessibility/HorizonTracker.h
    TerrainHolePanel.cpp
    TerrainHoleTool.cpp
    TerrainHolePanel.h
    TerrainHolePanel.ui
    TerrainHoleTool.h
    TerrainMiniMapTool.cpp
    TerrainMiniMapTool.h
    TerrainMiniMapPanel.ui
    TerrainModifyPanel.cpp
    TerrainModifyPanel.h
    TerrainModifyPanel.ui
    TerrainModifyTool.cpp
    TerrainModifyTool.h
    TerrainMoveTool.cpp
    TerrainMoveToolPanel.cpp
    TerrainMoveTool.h
    TerrainMoveToolPanel.h
    TerrainMoveToolPanel.ui
    TerrainTexturePainter.cpp
    TerrainTexturePainter.h
    Util/ImagePainter.cpp
    Util/ImagePainter.h
)
