#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    UsedResources.h
    Include/EditorCoreAPI.cpp
    Include/IErrorReport.h
    Include/IFileUtil.h
    Include/EditorCoreAPI.h
    Controls/ReflectedPropertyControl/ReflectedPropertyCtrl.qrc
    Controls/ReflectedPropertyControl/ReflectedPropertyCtrl.cpp
    Controls/ReflectedPropertyControl/ReflectedPropertyCtrl.h
    Controls/ReflectedPropertyControl/ReflectedPropertyItem.cpp
    Controls/ReflectedPropertyControl/ReflectedPropertyItem.h
    Controls/ReflectedPropertyControl/ReflectedVar.cpp
    Controls/ReflectedPropertyControl/ReflectedVar.h
    Controls/ReflectedPropertyControl/ReflectedVarWrapper.cpp
    Controls/ReflectedPropertyControl/ReflectedVarWrapper.h
    UsedResources.cpp
    LyViewPaneNames.h
    QtViewPaneManager.cpp
    QtViewPaneManager.h
    ErrorRecorder.cpp
    ErrorRecorder.h
    ErrorDialog.cpp
    ErrorDialog.h
    ErrorDialog.ui
    Clipboard.cpp
    Util/MemoryBlock.cpp
    Util/Variable.cpp
    Util/UndoUtil.cpp
    Util/VariablePropertyType.cpp
    Clipboard.h
    Util/MemoryBlock.h
    Util/Variable.h
    Util/UndoUtil.h
    Util/VariablePropertyType.h
    Util/RefCountBase.h
    Util/PathUtil.h
    Util/PathUtil.cpp
    Util/Image.cpp
    Util/Image.h
    Undo/Undo.cpp
    Undo/IUndoManagerListener.h
    Undo/IUndoObject.h
    Undo/Undo.h
    Undo/UndoVariableChange.h
    QtUI/ColorButton.cpp
    QtUI/ColorButton.h
    QtUtil.h
    QtUtilWin.h
)
