/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */


#pragma once

#define ID_FILE_NEW       0xE100
#define ID_FILE_SAVE_AS   0xE104
#define ID_FILE_MRU_FIRST 0xE110
#define ID_FILE_MRU_FILE1 0xE110
#define ID_FILE_MRU_LAST  0xE11F
#define ID_EDIT_COPY      0xE122
#define ID_EDIT_CUT       0xE123
#define ID_EDIT_PASTE     0xE125
#define ID_APP_ABOUT      0xE140
#define ID_APP_EXIT       0xE141
#define ID_APP_SHOW_WELCOME    0xE142
#define IDD_TRACKVIEWDIALOG                        19
#define IDD_DATABASE                               140
#define IDR_DB_LIBRARY_ITEM_BAR                    141
#define IDR_DB_MATERIAL_BAR                        142
#define IDR_DB_ENTITY                              147
#define IDD_DB_ENTITY                              149
#define IDI_BALL_ONLINE                            315
#define IDI_BALL_OFFLINE                           316
#define IDI_BALL_PENDING                           395
#define IDI_BALL_DISABLED                          396
#define IDR_DB_PARTICLES_BAR                       410
#define IDR_DB_LIBRARY_BAR                         455
#define IDR_DB_STANDART                            456
#define IDC_ZOOM_INTERNAL                          1052
#define IDC_BRUSH_INTERNAL                         1053
#define IDC_ARRBLCK                                1054
#define IDC_ARRBLCKCROSS                           1055
#define IDC_ARRWHITE                               1056
#define IDC_COLOR_PICKER                           1057
#define IDC_HIT_CURSOR                             1058
#define IDC_ARROW_ADDKEY                           1059
#define IDC_LEFTRIGHT                              1060
#define IDC_POINTER_OBJHIT                         1061
#define IDC_POINTER_LINK                           1062
#define IDC_POINTER_LINKNOW                        1063
#define IDC_POINTER_PLUS                           1064
#define IDC_POINTER_OBJECT_ROTATE                  1065
#define IDC_POINTER_OBJECT_SCALE                   1066
#define IDC_POINTER_OBJECT_MOVE                    1067
#define IDC_POINTER_MINUS                          1068
#define IDC_POINTER_GET_HEIGHT                     1069
#define IDC_POINTER_FLATTEN                        1070
#define IDC_POINTER_SMOOTH                         1071
#define IDC_POINTER_DRAG_ITEM                      1077
#define IDC_CURSOR_HAND_DRAG                       1078
#define IDC_CURSOR_HAND_FINGER                     1079
#define IDC_ARROW_UP                               1080
#define IDC_ARROW_DOWN                             1081
#define IDC_ARROW_DOWNRIGHT                        1082
#define IDC_ARROW_UPRIGHT                          1083
#define IDC_NEW                                    1578
#define IDC_POINTER_SO_SELECT                      1891
#define IDC_HAND_INTERNAL                          1998
#define IDC_POINTER_SO_SELECT_PLUS                 1999
#define IDC_POINTER_SO_SELECT_MINUS                2000
#define IDC_SELECTION                              2634
#define IDC_SELECTION_MASK                         2637
#define IDC_PLATFORM_PROVO                         2758
#define IDC_PLATFORM_SALEM                         2759
#define IDC_GROUPBOX_GLOBALTAGS                    2916
#define IDC_GROUPBOX_FRAGMENTTAGS                  2917
#define ID_RESOURCES_REDUCEWORKINGSET              32896
#define ID_VIEW_CONFIGURELAYOUT                    32906
#define ID_TOOLS_LOGMEMORYUSAGE                    32908
#define ID_TOOLS_CONFIGURETOOLS                    32911
#define ID_TOOLS_TOOL1                             32913
#define ID_TOOLS_CUSTOMIZEKEYBOARD                 32914
#define ID_EXPORT_INDOORS                          32915
#define ID_VIEW_CYCLE2DVIEWPORT                    32916
#define ID_PHYSICS_GETPHYSICSSTATE                 32937
#define ID_PHYSICS_RESETPHYSICSSTATE               32938
#define ID_GAME_SYNCPLAYER                         32941
#define ID_FILE_SAVELEVELRESOURCES                 32942
#define ID_TOOL_FIRST                              32972
#define ID_EDIT_UNFREEZE                           32973
#define ID_EDIT_UNHIDE                             32974
#define ID_TOOL_LAST                               33173
#define ID_TOOL_SHELVE_FIRST                       33174
#define ID_TOOL_SHELVE_LAST                        33375
#define ID_WIREFRAME                               33410
#define ID_GENERATORS_TEXTURE                      33448
#define ID_FILE_IMPORT                             33457
#define ID_EDIT_HOLD                               33464
#define ID_EDIT_FETCH                              33465
#define ID_FILE_EXPORTTOGAMENOSURFACETEXTURE       33473
#define ID_VIEW_SWITCHTOGAME                       33477
#define ID_VIEW_SWITCHTOGAME_FULLSCREEN            33478
#define ID_VIEW_SWITCHTOGAME_VIEWPORT              33479
#define ID_MOVE_OBJECT                             33481
#define ID_RENAME_OBJ                              33483
#define ID_FETCH                                   33496
#define ID_SELECTION_DELETE                        33512
#define ID_EDIT_ESCAPE                             33513
#define ID_UNDO                                    33524
#define ID_GOTO_SELECTED                           33535
#define ID_EDIT_LEVELDATA                          33542
#define ID_FILE_EDITEDITORINI                      33543
#define ID_FILE_EDITLOGFILE                        33544
#define ID_PREFERENCES                             33546
#define ID_REDO                                    33550
#define ID_SWITCH_PHYSICS                          33555
#define ID_REF_COORDS_SYS                          33556
#define ID_TV_ADDKEY                               33557
#define ID_TV_DELKEY                               33558
#define ID_TV_MOVEKEY                              33559
#define ID_TV_SLIDEKEY                             33560
#define ID_TV_SCALEKEY                             33561
#define ID_TV_ADD_SEQUENCE                         33563
#define ID_TV_DEL_SEQUENCE                         33564
#define ID_TV_EDIT_SEQUENCE                        33565
#define ID_TV_RECORD                               33566
#define ID_TV_PLAY                                 33567
#define ID_TV_STOP                                 33568
#define ID_TV_PAUSE                                33569
#define ID_ADDNODE                                 33570
#define ID_ADDSCENETRACK                           33573
#define ID_FIND                                    33574
#define ID_TAG_LOC1                                33576
#define ID_TAG_LOC2                                33577
#define ID_TAG_LOC3                                33578
#define ID_TAG_LOC4                                33579
#define ID_TAG_LOC5                                33580
#define ID_TAG_LOC6                                33581
#define ID_TAG_LOC7                                33582
#define ID_TAG_LOC8                                33583
#define ID_TAG_LOC9                                33584
#define ID_TAG_LOC10                               33585
#define ID_TAG_LOC11                               33586
#define ID_TAG_LOC12                               33587
#define ID_GOTO_LOC1                               33588
#define ID_GOTO_LOC2                               33589
#define ID_GOTO_LOC3                               33590
#define ID_GOTO_LOC4                               33591
#define ID_GOTO_LOC5                               33592
#define ID_GOTO_LOC6                               33593
#define ID_GOTO_LOC7                               33594
#define ID_GOTO_LOC8                               33595
#define ID_GOTO_LOC9                               33596
#define ID_GOTO_LOC10                              33597
#define ID_GOTO_LOC11                              33598
#define ID_GOTO_LOC12                              33599
#define ID_TV_JUMPEND                              33600
#define ID_TV_JUMPSTART                            33601
#define ID_TV_PREVKEY                              33602
#define ID_TV_NEXTKEY                              33603
#define ID_PLAY_LOOP                               33607
#define ID_PANEL_VEG_EXPORT                        33672
#define ID_PANEL_VEG_IMPORT                        33673
#define ID_PANEL_VEG_DISTRIBUTE                    33674
#define ID_PANEL_VEG_SCALE                         33675
#define ID_PANEL_VEG_ADD                           33676
#define ID_PANEL_VEG_REMOVE                        33677
#define ID_PANEL_VEG_CLEAR                         33678
#define ID_PANEL_VEG_CLONE                         33679
#define ID_PANEL_VEG_REPLACE                       33681
#define ID_PANEL_VEG_ADDCATEGORY                   33682
#define ID_PANEL_VEG_RENAMECATEGORY                33683
#define ID_PANEL_VEG_REMOVECATEGORY                33684
#define ID_TOOLS_PREFERENCES                       33691
#define ID_SWITCHCAMERA_DEFAULTCAMERA              33700
#define ID_SWITCHCAMERA_SEQUENCECAMERA             33701
#define ID_SWITCHCAMERA_SELECTEDCAMERA             33702
#define ID_TV_RECORD_AUTO                          33703
#define ID_TV_STOP_HARD_RESET                      33704
#define ID_VIEW_OPENVIEWPANE                       33709
#define ID_VIEW_OPENPANE_FIRST          33712
#define ID_VIEW_OPENPANE_LAST           33811
#define ID_OPEN_EMOTIONFX_EDITOR                   39742
#define ID_BRUSH_CSGSUBSTRUCT                      33837
#define ID_MATERIAL_PICKTOOL                       33842
#define ID_MODIFY_AIPOINT_PICKIMPASSLINK           33865
#define ID_FILE_EXPORTSELECTION                    33875
#define ID_EDIT_PASTE_WITH_LINKS                   33893
#define ID_SPLINE_PREVIOUS_KEY                     33916
#define ID_SPLINE_NEXT_KEY                         33917
#define ID_SPLINE_FLATTEN_ALL                      33918
#define ID_TANGENT_UNIFY                           33920
#define ID_TANGENT_IN_ZERO                         33921
#define ID_TANGENT_IN_STEP                         33923
#define ID_TANGENT_OUT_ZERO                        33924
#define ID_TANGENT_OUT_STEP                        33926
#define ID_TANGENT_AUTO                            33927
#define ID_TANGENT_IN_LINEAR                       33928
#define ID_TANGENT_OUT_LINEAR                      33929
#define ID_FREEZE_KEYS                             33930
#define ID_SPLINE_FIT_X                            33931
#define ID_SPLINE_FIT_Y                            33932
#define ID_SPLINE_SNAP_GRID_X                      33933
#define ID_SPLINE_SNAP_GRID_Y                      33934
#define ID_FREEZE_TANGENTS                         33935
#define ID_PANEL_VEG_CREATE_SEL                    33990
#define ID_TOOLS_UPDATEPROCEDURALVEGETATION        33999
#define ID_DISPLAY_GOTOPOSITION                    34004
#define ID_PHYSICS_SIMULATEOBJECTS                 34007
#define ID_TV_SEQUENCE_NEW                         34049
#define ID_TV_MODE_DOPESHEET                       34052
#define ID_VIEW_LAYOUTS                            34053
#define ID_TV_MODE_CURVEEDITOR                     34054
#define ID_OPEN_TRACKVIEW                          34063
#define ID_SWITCHCAMERA_NEXT                       34065
#define ID_TV_SNAP_NONE                            34068
#define ID_TV_SNAP_MAGNET                          34069
#define ID_TV_SNAP_FRAME                           34070
#define ID_TV_SNAP_TICK                            34071
#define ID_TV_SNAP_FPS                             34072
#define ID_VIEW_TICKINSECONDS                      34075
#define ID_VIEW_TICKINFRAMES                       34076
#define ID_OPEN_ASSET_BROWSER                      34077
#define ID_SNAP_TO_GRID_RANGE_BEGIN     34087
#define ID_SNAP_TO_GRID_RANGE_END       34106
#define ID_TOOLS_EXPORT_SHORTCUTS       34138
#define ID_TOOLS_IMPORT_SHORTCUTS       34139
#define ID_TOOLS_BATCH_RENDER           34151
#define ID_TOOLS_SCRIPTHELP             34152
#define ID_TV_MODE_OPENCURVEEDITOR      34153
#define ID_TOOLS_LUA_EDITOR             34154
#define ID_OPEN_QUICK_ACCESS_BAR                   34177
#define ID_TRACKVIEW_TOGGLE_DISABLE                34178
#define ID_TRACKVIEW_TOGGLE_MUTE                   34179
#define ID_TRACKVIEW_MUTE_ALL                      34180
#define ID_TRACKVIEW_UNMUTE_ALL                    34181
#define ID_TV_TOOLS_CUSTOMIZETRACKCOLORS           34182
#define ID_TOOLS_ENABLEFILECHANGEMONITORING        34185
#define ID_FILE_OPEN_LEVEL                         34196
#define ID_FILE_SAVE_LEVEL                         34197
#define ID_TV_SYNC_TO_BASE                         34199
#define ID_TV_SYNC_FROM_BASE                       34200
#define ID_FILE_SAVESETTINGS                       34204
#define ID_SET_TIME_TO_KEY                         34206
#define ID_TOGGLE_SCRUB_UNITS                      34207
#define ID_TOGGLE_PREVIEW_UNITS                    34208
#define ID_MANN_RELOAD_ANIMS                       34210
#define ID_FILE_ANIMDBEDITOR                       34211
#define ID_SNAP_TO_ANGLE_RANGE_BEGIN    34323
#define ID_SNAP_TO_ANGLE_RANGE_END      34330
#define ID_MODIFY_GOTO_SELECTION        34358
#define ID_VIEW_LAYOUT_FIRST            34363
#define ID_VIEW_LAYOUT_LAST             34377
#define ID_VIEW_SAVELAYOUT                         34438
#define ID_VIEW_LAYOUT_LOAD_DEFAULT                34439
#define ID_GAME_OSXGL_ENABLESPEC                   34449
#define ID_GAME_OSXMETAL_ENABLESPEC                34450
#define ID_CLEAR_REGISTRY                          34470
#define ID_SOUND_STOPALLSOUNDS                     34476
#define ID_AUDIO_REFRESH_AUDIO_SYSTEM              34477
#define ID_OPEN_AUDIO_CONTROLS_BROWSER              34580
#define ID_CREATE_GLOBAL_FG_MODULE_FROM_SELECTION                   35076
#define ID_CREATE_LEVEL_FG_MODULE_FROM_SELECTION                    35077
#define ID_GRAPHVIEW_ADD_BLACK_BOX                                  35078
#define ID_GRAPHVIEW_UNGROUP                                        35079
#define ID_FILE_PROJECT_MANAGER_NEW                                 35080
#define ID_FILE_PROJECT_MANAGER_OPEN                                35081
#define ID_FILE_PROJECT_MANAGER_SETTINGS                            35082
#define ID_TV_TRACKS_TOOLBAR_BASE                                   35083               // range between ID_TV_TRACKS_TOOLBAR_BASE to ID_TV_TRACKS_TOOLBAR_LAST reserved
#define ID_TV_TRACKS_TOOLBAR_LAST                                   35183               // for up to 100 "Add Tracks..." dynamically added Track View Track buttons
#define ID_OPEN_UICANVASEDITOR          36010
#define ID_SKINS_REFRESH                36014
#define ID_DOCUMENTATION_GETTINGSTARTEDGUIDE    36023
#define ID_DOCUMENTATION_TUTORIALS              36024
#define ID_DOCUMENTATION_GLOSSARY               36025
#define ID_DOCUMENTATION_O3DE                   36026
#define ID_DOCUMENTATION_GAMELIFT               36027
#define ID_DOCUMENTATION_RELEASENOTES           36028
#define ID_DOCUMENTATION_GAMEDEVBLOG            36029
#define ID_DOCUMENTATION_TWITCHCHANNEL          36030
#define ID_DOCUMENTATION_FORUMS                 36031
#define ID_DOCUMENTATION_AWSSUPPORT             36032
#define ID_DOCUMENTATION_FEEDBACK                    36043
#define ID_OPEN_SUBSTANCE_EDITOR                     36060
#define ID_IMPORT_ASSET                              36069
#define FIRST_QT_ACTION                      50000
#define ID_VIEW_CONSOLEWINDOW                50001
#define ID_TOOLBAR_SEPARATOR                 50002
#define ID_TOOLBAR_WIDGET_FIRST              50003
#define ID_TOOLBAR_WIDGET_UNDO               50003
#define ID_TOOLBAR_WIDGET_REDO               50004
#define ID_TOOLBAR_WIDGET_SNAP_ANGLE         50007
#define ID_TOOLBAR_WIDGET_SNAP_GRID          50008
#define ID_TOOLBAR_WIDGET_ENVIRONMENT_MODE   50011
#define ID_TOOLBAR_WIDGET_DEBUG_MODE         50012
#define ID_TOOLBAR_WIDGET_SPACER_RIGHT       50013
#define ID_TOOLBAR_WIDGET_PLAYCONSOLE_LABEL  50014
#define ID_TOOLBAR_WIDGET_LAST               50020
#define ID_VIEWPORTUI_VISIBLE                50040
