#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Include/MotionMatching/MotionMatchingBus.h
    Source/MotionMatchingModuleInterface.h
    Source/MotionMatchingSystemComponent.cpp
    Source/MotionMatchingSystemComponent.h
    Source/Allocators.h
    Source/BlendTreeMotionMatchNode.cpp
    Source/BlendTreeMotionMatchNode.h
    Source/CsvSerializers.cpp
    Source/CsvSerializers.h
    Source/EventData.cpp
    Source/EventData.h
    Source/Frame.cpp
    Source/Frame.h
    Source/Feature.cpp
    Source/Feature.h
    Source/FeatureMatrix.cpp
    Source/FeatureMatrix.h
    Source/FeatureMatrixMinMaxScaler.cpp
    Source/FeatureMatrixMinMaxScaler.h
    Source/FeatureMatrixStandardScaler.cpp
    Source/FeatureMatrixStandardScaler.h
    Source/FeatureMatrixTransformer.h
    Source/FeatureAngularVelocity.cpp
    Source/FeatureAngularVelocity.h
    Source/FeaturePosition.cpp
    Source/FeaturePosition.h
    Source/FeatureSchema.cpp
    Source/FeatureSchema.h
    Source/FeatureSchemaDefault.cpp
    Source/FeatureSchemaDefault.h
    Source/FeatureTrajectory.h
    Source/FeatureTrajectory.cpp
    Source/FeatureVelocity.cpp
    Source/FeatureVelocity.h
    Source/PoseDataJointVelocities.cpp
    Source/PoseDataJointVelocities.h
    Source/QueryVector.cpp
    Source/QueryVector.h
    Source/TrajectoryHistory.cpp
    Source/TrajectoryHistory.h
    Source/TrajectoryQuery.cpp
    Source/TrajectoryQuery.h
    Source/FrameDatabase.cpp
    Source/FrameDatabase.h
    Source/ImGuiMonitor.cpp
    Source/ImGuiMonitor.h
    Source/ImGuiMonitorBus.h
    Source/KdTree.cpp
    Source/KdTree.h
    Source/MotionMatchingData.cpp
    Source/MotionMatchingData.h
    Source/MotionMatchingInstance.cpp
    Source/MotionMatchingInstance.h
)
