/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */
#pragma once

#include <AzCore/PlatformDef.h> ///< Platform/compiler specific defines

#if defined(AZ_MONOLITHIC_BUILD)
    #define AZF_API
#else
    #if defined(AZF_EXPORTS)
        #define AZF_API           AZ_DLL_EXPORT
    #else
        #define AZF_API           AZ_DLL_IMPORT
    #endif
#endif

#if defined(AZ_MONOLITHIC_BUILD)

#define AZF_DECLARE_EBUS_SINGLE_ADDRESS(a)                     AZ_DECLARE_EBUS_EXTERN_SINGLE_ADDRESS(a)
#define AZF_INSTANTIATE_EBUS_SINGLE_ADDRESS(a)                 AZ_DECLARE_EBUS_INSTANTIATION_SINGLE_ADDRESS(a)
#define AZF_DECLARE_EBUS_MULTI_ADDRESS(a)                      AZ_DECLARE_EBUS_EXTERN_MULTI_ADDRESS(a)
#define AZF_INSTANTIATE_EBUS_MULTI_ADDRESS(a)                  AZ_DECLARE_EBUS_INSTANTIATION_MULTI_ADDRESS(a)
#define AZF_DECLARE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(a, b)      AZ_DECLARE_EBUS_EXTERN_SINGLE_ADDRESS_WITH_TRAITS(a, b)
#define AZF_INSTANTIATE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(a, b)  AZ_DECLARE_EBUS_INSTANTIATION_SINGLE_ADDRESS_WITH_TRAITS(a, b)
#define AZF_DECLARE_EBUS_MULTI_ADDRESS_WITH_TRAITS(a, b)       AZ_DECLARE_EBUS_EXTERN_MULTI_ADDRESS_WITH_TRAITS(a, b)
#define AZF_INSTANTIATE_EBUS_MULTI_ADDRESS_WITH_TRAITS(a, b)   AZ_DECLARE_EBUS_INSTANTIATION_MULTI_ADDRESS_WITH_TRAITS(a, b) 

#else

#define AZF_DECLARE_EBUS_SINGLE_ADDRESS(a)                     AZ_DECLARE_EBUS_EXTERN_SINGLE_ADDRESS(AZF_API, a) 
#define AZF_INSTANTIATE_EBUS_SINGLE_ADDRESS(a)                 AZ_DECLARE_EBUS_INSTANTIATION_SINGLE_ADDRESS(AZF_API, a)
#define AZF_DECLARE_EBUS_MULTI_ADDRESS(a)                      AZ_DECLARE_EBUS_EXTERN_MULTI_ADDRESS(AZF_API, a)
#define AZF_INSTANTIATE_EBUS_MULTI_ADDRESS(a)                  AZ_DECLARE_EBUS_INSTANTIATION_MULTI_ADDRESS(AZF_API, a)
#define AZF_DECLARE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(a, b)      AZ_DECLARE_EBUS_EXTERN_SINGLE_ADDRESS_WITH_TRAITS(AZF_API, a, b)
#define AZF_INSTANTIATE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(a, b)  AZ_DECLARE_EBUS_INSTANTIATION_SINGLE_ADDRESS_WITH_TRAITS(AZF_API, a, b)
#define AZF_DECLARE_EBUS_MULTI_ADDRESS_WITH_TRAITS(a, b)       AZ_DECLARE_EBUS_EXTERN_MULTI_ADDRESS_WITH_TRAITS(AZF_API, a, b)
#define AZF_INSTANTIATE_EBUS_MULTI_ADDRESS_WITH_TRAITS(a, b)   AZ_DECLARE_EBUS_INSTANTIATION_MULTI_ADDRESS_WITH_TRAITS(AZF_API, a, b)

#endif //defined(AZ_MONOLITHIC_BUILD)
