#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Source/Actor.cpp
    Source/Actor.h
    Source/ActorBus.h
    Source/ActorInstance.cpp
    Source/ActorInstance.h
    Source/ActorInstanceBus.h
    Source/ActorManager.cpp
    Source/ActorManager.h
    Source/ActorUpdateScheduler.h
    Source/Algorithms.h
    Source/Allocators.cpp
    Source/Allocators.h
    Source/Attachment.cpp
    Source/Attachment.h
    Source/AttachmentNode.cpp
    Source/AttachmentNode.h
    Source/AttachmentSkin.cpp
    Source/AttachmentSkin.h
    Source/CompressedKeyFrames.h
    Source/Constraint.h
    Source/ConstraintTransform.h
    Source/ConstraintTransformRotationAngles.h
    Source/ConstraintTransformRotationAngles.cpp
    Source/DebugDraw.h
    Source/DebugDraw.cpp
    Source/DualQuatSkinDeformer.cpp
    Source/DualQuatSkinDeformer.h
    Source/EMotionFXConfig.h
    Source/EMotionFXManager.cpp
    Source/EMotionFXManager.h
    Source/JointSelectionBus.h
    Source/KeyFrame.h
    Source/KeyFrame.inl
    Source/KeyFrameFinder.h
    Source/KeyFrameFinder.inl
    Source/KeyTrackLinearDynamic.h
    Source/KeyTrackLinearDynamic.inl
    Source/LayerPass.h
    Source/MemoryCategories.h
    Source/Mesh.cpp
    Source/Mesh.h
    Source/Mesh.inl
    Source/MeshDeformer.cpp
    Source/MeshDeformer.h
    Source/MeshDeformerStack.cpp
    Source/MeshDeformerStack.h
    Source/MorphMeshDeformer.cpp
    Source/MorphMeshDeformer.h
    Source/MorphSetup.cpp
    Source/MorphSetup.h
    Source/MorphSetupInstance.cpp
    Source/MorphSetupInstance.h
    Source/MorphTarget.cpp
    Source/MorphTarget.h
    Source/MorphTargetStandard.cpp
    Source/MorphTargetStandard.h
    Source/Motion.cpp
    Source/Motion.h
    Source/MotionInstance.cpp
    Source/MotionInstance.h
    Source/MotionInstancePool.cpp
    Source/MotionInstancePool.h
    Source/MotionLayerSystem.cpp
    Source/MotionLayerSystem.h
    Source/MotionManager.cpp
    Source/MotionManager.h
    Source/MotionQueue.cpp
    Source/MotionQueue.h
    Source/MotionSet.cpp
    Source/MotionSet.h
    Source/MotionSystem.cpp
    Source/MotionSystem.h
    Source/MultiThreadScheduler.cpp
    Source/MultiThreadScheduler.h
    Source/Node.cpp
    Source/Node.h
    Source/NodeAttribute.h
    Source/NodeGroup.cpp
    Source/NodeGroup.h
    Source/NodeMap.cpp
    Source/NodeMap.h
    Source/ObjectId.cpp
    Source/ObjectId.h
    Source/PlayBackInfo.h
    Source/PhysicsSetup.cpp
    Source/PhysicsSetup.h
    Source/Pose.cpp
    Source/Pose.h
    Source/PoseData.cpp
    Source/PoseData.h
    Source/PoseDataFactory.cpp
    Source/PoseDataFactory.h
    Source/PoseDataRagdoll.cpp
    Source/PoseDataRagdoll.h
    Source/RagdollInstance.cpp
    Source/RagdollInstance.h
    Source/RagdollVelocityEvaluators.cpp
    Source/RagdollVelocityEvaluators.h
    Source/Recorder.cpp
    Source/Recorder.h
    Source/RecorderBus.h
    Source/RepositioningLayerPass.cpp
    Source/RepositioningLayerPass.h
    Source/SimulatedObjectBus.h
    Source/SimulatedObjectSetup.cpp
    Source/SimulatedObjectSetup.h
    Source/SimulatedObjectSetup_Impl.inl
    Source/SimulatedObjectSetup_Interface.inl
    Source/SingleThreadScheduler.cpp
    Source/SingleThreadScheduler.h
    Source/Skeleton.cpp
    Source/Skeleton.h
    Source/SkinningInfoVertexAttributeLayer.cpp
    Source/SkinningInfoVertexAttributeLayer.h
    Source/SoftSkinDeformer.cpp
    Source/SoftSkinDeformer.h
    Source/SoftSkinManager.cpp
    Source/SoftSkinManager.h
    Source/SpringSolver.cpp
    Source/SpringSolver.h
    Source/SubMesh.cpp
    Source/SubMesh.h
    Source/ThreadData.cpp
    Source/ThreadData.h
    Source/Transform.cpp
    Source/Transform.h
    Source/TransformData.cpp
    Source/TransformData.h
    Source/TriggerActionSetup.cpp
    Source/TriggerActionSetup.h
    Source/Velocity.cpp
    Source/Velocity.h
    Source/VertexAttributeLayer.cpp
    Source/VertexAttributeLayer.h
    Source/VertexAttributeLayerAbstractData.cpp
    Source/VertexAttributeLayerAbstractData.h
    Source/AnimGraph.cpp
    Source/AnimGraph.h
    Source/AnimGraphBus.h
    Source/AnimGraphAttributeTypes.cpp
    Source/AnimGraphAttributeTypes.h
    Source/AnimGraphBindPoseNode.cpp
    Source/AnimGraphBindPoseNode.h
    Source/AnimGraphEntryNode.cpp
    Source/AnimGraphEntryNode.h
    Source/AnimGraphEventBuffer.cpp
    Source/AnimGraphEventBuffer.h
    Source/AnimGraphExitNode.cpp
    Source/AnimGraphExitNode.h
    Source/AnimGraphHubNode.cpp
    Source/AnimGraphHubNode.h
    Source/AnimGraphInstance.cpp
    Source/AnimGraphInstance.h
    Source/AnimGraphManager.cpp
    Source/AnimGraphManager.h
    Source/AnimGraphMotionNode.cpp
    Source/AnimGraphMotionNode.h
    Source/AnimGraphNetworkSerializer.cpp
    Source/AnimGraphNetworkSerializer.h
    Source/AnimGraphNode.cpp
    Source/AnimGraphNode.h
    Source/AnimGraphNodeData.cpp
    Source/AnimGraphNodeData.h
    Source/AnimGraphNodeGroup.cpp
    Source/AnimGraphNodeGroup.h
    Source/AnimGraphObject.cpp
    Source/AnimGraphObject.h
    Source/AnimGraphObjectData.cpp
    Source/AnimGraphObjectData.h
    Source/AnimGraphObjectFactory.cpp
    Source/AnimGraphObjectFactory.h
    Source/AnimGraphObjectIds.h
    Source/AnimGraphPose.cpp
    Source/AnimGraphPose.h
    Source/AnimGraphPosePool.cpp
    Source/AnimGraphPosePool.h
    Source/AnimGraphRefCountedData.h
    Source/AnimGraphRefCountedDataPool.cpp
    Source/AnimGraphRefCountedDataPool.h
    Source/AnimGraphReferenceNode.cpp
    Source/AnimGraphReferenceNode.h
    Source/AnimGraphStateMachine.cpp
    Source/AnimGraphStateMachine.h
    Source/AnimGraphStateTransition.cpp
    Source/AnimGraphStateTransition.h
    Source/AnimGraphSnapshot.cpp
    Source/AnimGraphSnapshot.h
    Source/AnimGraphSyncTrack.cpp
    Source/AnimGraphSyncTrack.h
    Source/BlendTree.cpp
    Source/BlendTree.h
    Source/BlendTreeAccumTransformNode.cpp
    Source/BlendTreeAccumTransformNode.h
    Source/BlendTreeBlend2Node.cpp
    Source/BlendTreeBlend2Node.h
    Source/BlendTreeBlend2NodeBase.cpp
    Source/BlendTreeBlend2NodeBase.h
    Source/BlendTreeBlend2AdditiveNode.cpp
    Source/BlendTreeBlend2AdditiveNode.h
    Source/BlendTreeBlend2LegacyNode.cpp
    Source/BlendTreeBlend2LegacyNode.h
    Source/BlendTreeBlendNNode.cpp
    Source/BlendTreeBlendNNode.h
    Source/BlendTreeBoolLogicNode.cpp
    Source/BlendTreeBoolLogicNode.h
    Source/BlendTreeConnection.cpp
    Source/BlendTreeConnection.h
    Source/BlendTreeDirectionToWeightNode.cpp
    Source/BlendTreeDirectionToWeightNode.h
    Source/BlendTreeFinalNode.cpp
    Source/BlendTreeFinalNode.h
    Source/BlendTreeFloatConditionNode.cpp
    Source/BlendTreeFloatConditionNode.h
    Source/BlendTreeFloatConstantNode.cpp
    Source/BlendTreeFloatConstantNode.h
    Source/BlendTreeFloatMath1Node.cpp
    Source/BlendTreeFloatMath1Node.h
    Source/BlendTreeFloatMath2Node.cpp
    Source/BlendTreeFloatMath2Node.h
    Source/BlendTreeFloatSwitchNode.cpp
    Source/BlendTreeFloatSwitchNode.h
    Source/BlendTreeFootIKNode.cpp
    Source/BlendTreeFootIKNode.h
    Source/BlendTreeGetTransformNode.cpp
    Source/BlendTreeGetTransformNode.h
    Source/BlendTreeLookAtNode.cpp
    Source/BlendTreeLookAtNode.h
    Source/BlendTreeMaskNode.cpp
    Source/BlendTreeMaskNode.h
    Source/BlendTreeMaskLegacyNode.cpp
    Source/BlendTreeMaskLegacyNode.h
    Source/BlendTreeMirrorPoseNode.cpp
    Source/BlendTreeMirrorPoseNode.h
    Source/BlendTreeMorphTargetNode.cpp
    Source/BlendTreeMorphTargetNode.h
    Source/BlendTreeMotionFrameNode.cpp
    Source/BlendTreeMotionFrameNode.h
    Source/BlendTreeParameterNode.cpp
    Source/BlendTreeParameterNode.h
    Source/BlendTreePoseSubtractNode.cpp
    Source/BlendTreePoseSubtractNode.h
    Source/BlendTreePoseSwitchNode.cpp
    Source/BlendTreePoseSwitchNode.h
    Source/BlendTreeRagdollNode.cpp
    Source/BlendTreeRagdollNode.h
    Source/BlendTreeRagdollStrengthModifierNode.cpp
    Source/BlendTreeRagdollStrengthModifierNode.h
    Source/BlendTreeRangeRemapperNode.cpp
    Source/BlendTreeRangeRemapperNode.h
    Source/BlendTreeSimulatedObjectNode.cpp
    Source/BlendTreeSimulatedObjectNode.h
    Source/BlendTreeSmoothingNode.cpp
    Source/BlendTreeSmoothingNode.h
    Source/BlendTreeTransformNode.cpp
    Source/BlendTreeTransformNode.h
    Source/BlendTreeTwoLinkIKNode.cpp
    Source/BlendTreeTwoLinkIKNode.h
    Source/BlendTreeSetTransformNode.cpp
    Source/BlendTreeSetTransformNode.h
    Source/BlendTreeVector2ComposeNode.cpp
    Source/BlendTreeVector2ComposeNode.h
    Source/BlendTreeVector2DecomposeNode.cpp
    Source/BlendTreeVector2DecomposeNode.h
    Source/BlendTreeVector3ComposeNode.cpp
    Source/BlendTreeVector3ComposeNode.h
    Source/BlendTreeVector3DecomposeNode.cpp
    Source/BlendTreeVector3DecomposeNode.h
    Source/BlendTreeVector3Math1Node.cpp
    Source/BlendTreeVector3Math1Node.h
    Source/BlendTreeVector3Math2Node.cpp
    Source/BlendTreeVector3Math2Node.h
    Source/BlendTreeVector4ComposeNode.cpp
    Source/BlendTreeVector4ComposeNode.h
    Source/BlendTreeVector4DecomposeNode.cpp
    Source/BlendTreeVector4DecomposeNode.h
    Source/BlendTreeRaycastNode.cpp
    Source/BlendTreeRaycastNode.h
    Source/BlendTreeRotationMath2Node.cpp
    Source/BlendTreeRotationMath2Node.h
    Source/BlendTreeRotationLimitNode.cpp
    Source/BlendTreeRotationLimitNode.h
    Source/BlendSpaceParamEvaluator.h
    Source/BlendSpaceParamEvaluator.cpp
    Source/BlendSpaceManager.h
    Source/BlendSpaceManager.cpp
    Source/BlendSpaceNode.cpp
    Source/BlendSpaceNode.h
    Source/BlendSpace1DNode.cpp
    Source/BlendSpace1DNode.h
    Source/BlendSpace2DNode.cpp
    Source/BlendSpace2DNode.h
    Source/ObjectAffectedByParameterChanges.h
    Source/ObjectAffectedByParameterChanges.cpp
    Source/TransformSpace.h
    Source/TransformSpace.cpp
    Source/AnimGraphMotionCondition.cpp
    Source/AnimGraphMotionCondition.h
    Source/AnimGraphParameterCondition.cpp
    Source/AnimGraphParameterCondition.h
    Source/AnimGraphPlayTimeCondition.cpp
    Source/AnimGraphPlayTimeCondition.h
    Source/AnimGraphStateCondition.cpp
    Source/AnimGraphStateCondition.h
    Source/AnimGraphTagCondition.cpp
    Source/AnimGraphTagCondition.h
    Source/AnimGraphTimeCondition.cpp
    Source/AnimGraphTimeCondition.h
    Source/AnimGraphTransitionCondition.cpp
    Source/AnimGraphTransitionCondition.h
    Source/AnimGraphTriggerAction.cpp
    Source/AnimGraphTriggerAction.h
    Source/AnimGraphParameterAction.cpp
    Source/AnimGraphParameterAction.h
    Source/AnimGraphSimpleStateAction.cpp
    Source/AnimGraphSimpleStateAction.h
    Source/AnimGraphVector2Condition.cpp
    Source/AnimGraphVector2Condition.h
    Source/AnimGraphFollowerParameterAction.cpp
    Source/AnimGraphFollowerParameterAction.h
    Source/AnimGraphSymbolicFollowerParameterAction.cpp
    Source/AnimGraphSymbolicFollowerParameterAction.h
    Source/Event.cpp
    Source/Event.h
    Source/EventData.cpp
    Source/EventData.h
    Source/EventDataFootIK.cpp
    Source/EventDataFootIK.h
    Source/EventDataFloatArray.h
    Source/EventDataFloatArray.cpp
    Source/EventDataSyncable.cpp
    Source/EventDataSyncable.h
    Source/EventHandler.cpp
    Source/EventHandler.h
    Source/EventInfo.h
    Source/EventManager.cpp
    Source/EventManager.h
    Source/MotionData/MotionData.cpp
    Source/MotionData/MotionData.h
    Source/MotionData/MotionDataFactory.cpp
    Source/MotionData/MotionDataFactory.h
    Source/MotionData/MotionDataSampleSettings.h
    Source/MotionData/NonUniformMotionData.cpp
    Source/MotionData/NonUniformMotionData.h
    Source/MotionData/UniformMotionData.cpp
    Source/MotionData/UniformMotionData.h
    Source/MotionData/RootMotionExtractionData.h
    Source/MotionData/RootMotionExtractionData.cpp
    Source/MotionEvent.cpp
    Source/MotionEvent.h
    Source/MotionEventTable.cpp
    Source/MotionEventTable.h
    Source/MotionEventTrack.cpp
    Source/MotionEventTrack.h
    Source/TwoStringEventData.cpp
    Source/TwoStringEventData.h
    Source/Importer/ChunkProcessors.cpp
    Source/Importer/ChunkProcessors.h
    Source/Importer/Importer.cpp
    Source/Importer/Importer.h
    Source/Importer/NodeMapFileFormat.h
    Source/Importer/SharedFileFormatStructs.h
    Source/Importer/ActorFileFormat.h
    Source/Importer/MotionFileFormat.h
    Source/Parameter/BoolParameter.cpp
    Source/Parameter/BoolParameter.h
    Source/Parameter/ColorParameter.cpp
    Source/Parameter/ColorParameter.h
    Source/Parameter/DefaultValueParameter.h
    Source/Parameter/FloatParameter.cpp
    Source/Parameter/FloatParameter.h
    Source/Parameter/FloatSliderParameter.cpp
    Source/Parameter/FloatSliderParameter.h
    Source/Parameter/FloatSpinnerParameter.cpp
    Source/Parameter/FloatSpinnerParameter.h
    Source/Parameter/GroupParameter.cpp
    Source/Parameter/GroupParameter.h
    Source/Parameter/IntParameter.cpp
    Source/Parameter/IntParameter.h
    Source/Parameter/IntSliderParameter.cpp
    Source/Parameter/IntSliderParameter.h
    Source/Parameter/IntSpinnerParameter.cpp
    Source/Parameter/IntSpinnerParameter.h
    Source/Parameter/Parameter.cpp
    Source/Parameter/Parameter.h
    Source/Parameter/ParameterFactory.cpp
    Source/Parameter/ParameterFactory.h
    Source/Parameter/RangedValueParameter.h
    Source/Parameter/RotationParameter.cpp
    Source/Parameter/RotationParameter.h
    Source/Parameter/StringParameter.cpp
    Source/Parameter/StringParameter.h
    Source/Parameter/TagParameter.cpp
    Source/Parameter/TagParameter.h
    Source/Parameter/ValueParameter.cpp
    Source/Parameter/ValueParameter.h
    Source/Parameter/Vector2Parameter.cpp
    Source/Parameter/Vector2Parameter.h
    Source/Parameter/Vector3GizmoParameter.cpp
    Source/Parameter/Vector3GizmoParameter.h
    Source/Parameter/Vector3Parameter.cpp
    Source/Parameter/Vector3Parameter.h
    Source/Parameter/Vector4Parameter.cpp
    Source/Parameter/Vector4Parameter.h
)
