  Prism/AddEditGemsButton[m
  Prism/AddLicenseToGemCatalog[m
  Prism/AddRemoveRepoWorkingUI[m
  Prism/AddRepoDialog[m
* [32mPrism/CmakeVariablesPerProject[m
  Prism/CreateRepositoryScreen[m
  Prism/CustomBuildParameters[m
  Prism/CustomTabWidgetForEngine[m
  Prism/DeleteUpdateGemsUI[m
  Prism/DisplayAddGemInfo[m
  Prism/EnterInFileDialog[m
  Prism/ExternalLinkWarning[m
  Prism/FasterBuildTimes[m
  Prism/FixGemCart[m
  Prism/FixGemCatalogHyperlinks[m
  Prism/FixGemSelectedFilter[m
  Prism/FixRemovedProjectStillShown[m
  Prism/FixTabOverlayOnStartup[m
  Prism/GemCatalogMenu[m
  Prism/GemCatalogTests[m
  Prism/GemCatalogWithoutProject[m
  Prism/GemRepoInspector[m
  Prism/RefreshAfterDownload[m
  Prism/RefreshGemRepos[m
  Prism/RefreshOnDownload[m
  Prism/RefreshRepoButtonDisablesRepo[m
  Prism/RemoteGemWarning[m
  Prism/RemoveTabFocus[m
  Prism/ResetBuildAndCacheAfterProjectMove[m
  Prism/SearchForGemsFromTags[m
  Prism/ShowGemDownloadStatus[m
  Prism/ShowGemPreview[m
  Prism/ShowGemRepoGems[m
  Prism/ShowGemsInRepo[m
  Prism/ShowRepoGems[m
  Prism/ShowRepoList[m
  Prism/UpdateTemplatePics[m
  Prism/UseGemDisplayNames[m
  Prism/VS2019InstallInstructions[m
  Prism/WarnExternalLink[m
  Prism/WarnVSNotInstalled[m
  Prism/cherry-pick-gem-catalog-fix[m
  Prism/gitRepos[m
  development[m
  new-feature[m
  racoonteurs[m
  stabilization/2110[m
  stabilization/2111RTE[m
