/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */
#pragma once

#define AZ_TRAIT_AZTEST_ATTACH_RESULT_LISTENER 0

#define AZ_TRAIT_UNIT_TEST_ASSET_MANAGER_TEST_DEFAULT_TIMEOUT_SECS 5
#define AZ_TRAIT_UNIT_TEST_ENTITY_ID_GEN_TEST_COUNT 10000
#define AZ_TRAIT_UNIT_TEST_DILLER_TRIGGER_EVENT_COUNT 100000

#define AZ_TRAIT_TEST_APPEND_ROOT_FOLDER_TO_PATH true

#define AZ_TRAIT_DISABLE_FAILED_ALLOCATOR_LEAK_DETECTION_TESTS true
#define AZ_TRAIT_DISABLE_FAILED_ASSET_MANAGER_TESTS true
#define AZ_TRAIT_DISABLE_FAILED_AUDIO_SYSTEM_TESTS true
#define AZ_TRAIT_DISABLE_FAILED_AUDIO_WWISE_TESTS true
#define AZ_TRAIT_DISABLE_FAILED_DEATH_TESTS true
#define AZ_TRAIT_DISABLE_FAILED_DLL_TESTS true
#define AZ_TRAIT_DISABLE_FAILED_EMOTION_FX_TESTS true
#define AZ_TRAIT_DISABLE_FAILED_GRIDMATE_TESTS true
#define AZ_TRAIT_DISABLE_FAILED_JOB_BASIC_TESTS true
#define AZ_TRAIT_DISABLE_FAILED_MERGESETTINGSFOLDER_CONFLICTINGSPECIALIZATIONS true
#define AZ_TRAIT_DISABLE_FAILED_NETWORKING_TESTS true
#define AZ_TRAIT_DISABLE_FAILED_SAVE_DATA_TESTS true
#define AZ_TRAIT_DISABLE_FAILED_SERIALIZE_BASIC_TEST true
#define AZ_TRAIT_DISABLE_FAILED_STREAMER_TESTS true
#define AZ_TRAIT_DISABLE_FAILED_SURFACE_DATA_TESTS true
#define AZ_TRAIT_DISABLE_FAILED_SYSTEM_FILE_TESTS true
#define AZ_TRAIT_DISABLE_FAILED_TOUCH_BENDING_TESTS true
#define AZ_TRAIT_DISABLE_FAILED_VEGETATION_TESTS true

#define AZ_TRAIT_DISABLE_LOG_ALWAYS_FUZZ_TEST true
