#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Source/Cinematics/ShadowsSetupNode.h
    Source/Cinematics/ShadowsSetupNode.cpp
    Include/Maestro/MaestroBus.h
    Source/MaestroSystemComponent.cpp
    Source/MaestroSystemComponent.h
    Source/Cinematics/AnimSerializer.cpp
    Source/Cinematics/AnimSequence.cpp
    Source/Cinematics/CharacterTrackAnimator.cpp
    Source/Cinematics/Movie.cpp
    Source/Cinematics/2DSpline.h
    Source/Cinematics/AnimSerializer.h
    Source/Cinematics/AnimSequence.h
    Source/Cinematics/CharacterTrackAnimator.h
    Source/Cinematics/Movie.h
    Source/Cinematics/AssetBlendTrack.cpp
    Source/Cinematics/BoolTrack.cpp
    Source/Cinematics/CaptureTrack.cpp
    Source/Cinematics/CharacterTrack.cpp
    Source/Cinematics/CommentTrack.cpp
    Source/Cinematics/CompoundSplineTrack.cpp
    Source/Cinematics/ConsoleTrack.cpp
    Source/Cinematics/EventTrack.cpp
    Source/Cinematics/GotoTrack.cpp
    Source/Cinematics/LookAtTrack.cpp
    Source/Cinematics/TimeRangesTrack.h
    Source/Cinematics/TimeRangesTrack.cpp
    Source/Cinematics/ScreenFaderTrack.cpp
    Source/Cinematics/SelectTrack.cpp
    Source/Cinematics/SequenceTrack.cpp
    Source/Cinematics/SoundTrack.cpp
    Source/Cinematics/TrackEventTrack.cpp
    Source/Cinematics/AnimSplineTrack.h
    Source/Cinematics/AnimSplineTrack_Vec2Specialization.cpp
    Source/Cinematics/AnimTrack.h
    Source/Cinematics/AssetBlendTrack.h
    Source/Cinematics/BoolTrack.h
    Source/Cinematics/CaptureTrack.h
    Source/Cinematics/CharacterTrack.h
    Source/Cinematics/CommentTrack.h
    Source/Cinematics/CompoundSplineTrack.h
    Source/Cinematics/ConsoleTrack.h
    Source/Cinematics/EventTrack.h
    Source/Cinematics/GotoTrack.h
    Source/Cinematics/LookAtTrack.h
    Source/Cinematics/ScreenFaderTrack.h
    Source/Cinematics/SelectTrack.h
    Source/Cinematics/SequenceTrack.h
    Source/Cinematics/SoundTrack.h
    Source/Cinematics/TrackEventTrack.h
    Source/Cinematics/AnimAZEntityNode.cpp
    Source/Cinematics/AnimNode.cpp
    Source/Cinematics/AnimNodeGroup.cpp
    Source/Cinematics/AnimPostFXNode.cpp
    Source/Cinematics/AnimScreenFaderNode.cpp
    Source/Cinematics/CommentNode.cpp
    Source/Cinematics/AnimComponentNode.cpp
    Source/Cinematics/CVarNode.cpp
    Source/Cinematics/EventNode.cpp
    Source/Cinematics/LayerNode.cpp
    Source/Cinematics/SceneNode.cpp
    Source/Cinematics/ScriptVarNode.cpp
    Source/Cinematics/AnimAZEntityNode.h
    Source/Cinematics/AnimNode.h
    Source/Cinematics/AnimPostFXNode.h
    Source/Cinematics/AnimScreenFaderNode.h
    Source/Cinematics/CommentNode.h
    Source/Cinematics/AnimComponentNode.h
    Source/Cinematics/CVarNode.h
    Source/Cinematics/EventNode.h
    Source/Cinematics/LayerNode.h
    Source/Cinematics/SceneNode.h
    Source/Components/SequenceComponent.h
    Source/Components/SequenceComponent.cpp
    Source/Components/SequenceAgent.h
    Source/Components/SequenceAgent.cpp
    Source/Components/SequenceAgentComponent.h
    Source/Components/SequenceAgentComponent.cpp
)
