
set(FILES
    Include/MotionMatching/MotionMatchingBus.h
    Source/MotionMatchingModuleInterface.h
    Source/MotionMatchingSystemComponent.cpp
    Source/MotionMatchingSystemComponent.h
    Source/Allocators.cpp
    Source/Allocators.h
    Source/Behavior.cpp
    Source/Behavior.h
    Source/BehaviorInstance.cpp
    Source/BehaviorInstance.h
    Source/BlendTreeMotionMatchNode.cpp
    Source/BlendTreeMotionMatchNode.h
    Source/Frame.cpp
    Source/Frame.h
    Source/Feature.cpp
    Source/Feature.h
    Source/FeatureDatabase.cpp
    Source/FeatureDatabase.h
    Source/FeatureDirection.cpp
    Source/FeatureDirection.h
    Source/FeatureMatrix.cpp
    Source/FeatureMatrix.h
    Source/FeaturePosition.cpp
    Source/FeaturePosition.h
    Source/FeatureTrajectory.h
    Source/FeatureTrajectory.cpp
    Source/FeatureVelocity.cpp
    Source/FeatureVelocity.h
    Source/TrajectoryHistory.cpp
    Source/TrajectoryHistory.h
    Source/FrameDatabase.cpp
    Source/FrameDatabase.h
    Source/KdTree.cpp
    Source/KdTree.h
    Source/LocomotionBehavior.cpp
    Source/LocomotionBehavior.h
    Source/MotionMatchEventData.cpp
    Source/MotionMatchEventData.h
    Source/MotionMatchSystem.cpp
    Source/MotionMatchSystem.h
)
