
########################################################################################
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
########################################################################################

def build(bld):
    bld.DefineGem(
        # Add custom build options here
        includes    =     [bld.Path('Code/CryEngine/CryAction'),
                           bld.Path('Code/CryEngine/CryCommon')],
        export_includes = [bld.Path('Gems/MultiplayerCompression/Code/Include')],
        uselib      =     ['LZ4'],
        defines     =     ['ENABLE_MULTIPLAYER_COMPRESSION'],
        file_list   =     ['multiplayercompression.waf_files'],
    )
