#
# Copyright (c) Contributors to the Open 3D Engine Project. For complete copyright and license terms please see the LICENSE at the root of this distribution.
# 
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    AZCrySystemInitLogSink.cpp
    CmdLine.cpp
    CmdLineArg.cpp
    ConsoleBatchFile.cpp
    ConsoleHelpGen.cpp
    DebugCallStack.cpp
    IDebugCallStack.cpp
    Log.cpp
    System.cpp
    SystemCFG.cpp
    SystemEventDispatcher.cpp
    SystemInit.cpp
    SystemWin32.cpp
    Timer.cpp
    XConsole.cpp
    XConsoleVariable.cpp
    XML/ReadWriteXMLSink.h
    AZCrySystemInitLogSink.h
    AZCoreLogSink.h
    CmdLine.h
    CmdLineArg.h
    ConsoleBatchFile.h
    ConsoleHelpGen.h
    DebugCallStack.h
    IDebugCallStack.h
    Log.h
    SimpleStringPool.h
    CrySystem_precompiled.h
    System.h
    SystemCFG.h
    SystemEventDispatcher.h
    Timer.h
    XConsole.h
    XConsoleVariable.h
    XML/SerializeXMLReader.cpp
    XML/SerializeXMLWriter.cpp
    XML/xml.cpp
    XML/XMLPatcher.cpp
    XML/XmlUtils.cpp
    XML/SerializeXMLReader.h
    XML/SerializeXMLWriter.h
    XML/xml.h
    XML/XMLPatcher.h
    XML/xml_string.h
    XML/XmlUtils.h
    XML/ReadXMLSink.cpp
    XML/WriteXMLSource.cpp
    LocalizedStringManager.cpp
    LocalizedStringManager.h
    Huffman.cpp
    Huffman.h
    RemoteConsole/RemoteConsole.cpp
    RemoteConsole/RemoteConsole.h
    RemoteConsole/RemoteConsole_impl.inl
    RemoteConsole/RemoteConsole_none.inl
    LevelSystem/LevelSystem.cpp
    LevelSystem/LevelSystem.h
    LevelSystem/SpawnableLevelSystem.cpp
    LevelSystem/SpawnableLevelSystem.h
    ViewSystem/DebugCamera.cpp
    ViewSystem/DebugCamera.h
    ViewSystem/View.cpp
    ViewSystem/View.h
    ViewSystem/ViewSystem.cpp
    ViewSystem/ViewSystem.h
    WindowsErrorReporting.cpp
)
