#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#

set(FILES
    Source/ImageProcessing_precompiled.cpp
    Source/ImageProcessing_precompiled.h
    Source/Compressors/CryTextureSquisher/CryTextureSquisher.cpp
    Source/Compressors/CryTextureSquisher/CryTextureSquisher.h
    Include/ImageProcessing/ImageProcessingBus.h
    Include/ImageProcessing/ImageProcessingEditorBus.h
    Include/ImageProcessing/PixelFormats.h
    Include/ImageProcessing/ImageObject.h
    Source/ImageProcessingSystemComponent.cpp
    Source/ImageProcessingSystemComponent.h
    Source/ImageBuilderComponent.cpp
    Source/ImageBuilderComponent.h
    Source/ImageBuilderBaseType.h
    Source/BuilderSettings/MipmapSettings.h
    Source/BuilderSettings/MipmapSettings.cpp
    Source/BuilderSettings/CubemapSettings.h
    Source/BuilderSettings/CubemapSettings.cpp
    Source/BuilderSettings/PresetSettings.h
    Source/BuilderSettings/PresetSettings.cpp
    Source/BuilderSettings/TextureSettings.h
    Source/BuilderSettings/TextureSettings.cpp
    Source/BuilderSettings/BuilderSettings.cpp
    Source/BuilderSettings/BuilderSettings.h
    Source/BuilderSettings/BuilderSettingManager.cpp
    Source/BuilderSettings/BuilderSettingManager.h
    Source/BuilderSettings/ImageProcessingDefines.h
    Source/BuilderSettings/PlatformSettings.h
    Source/Processing/ImageObjectImpl.h
    Source/Processing/ImageObjectImpl.cpp
    Source/Processing/PixelFormatInfo.h
    Source/Processing/PixelFormatInfo.cpp
    Source/Processing/ImageConvert.h
    Source/Processing/ImageConvert.cpp
    Source/Processing/ImageConvertJob.h
    Source/Processing/ImageConvertJob.cpp
    Source/Processing/ImagePreview.h
    Source/Processing/ImagePreview.cpp
    Source/Processing/ImageToProcess.h
    Source/Processing/ImageFlags.h
    Source/Processing/DDSHeader.h
    Source/ImageLoader/ImageLoaders.h
    Source/ImageLoader/ImageLoaders.cpp
    Source/ImageLoader/QtImageLoader.cpp
    Source/ImageLoader/TIFFLoader.cpp
    Source/ImageLoader/BTImageLoader.cpp
    Source/Editor/EditorCommon.h
    Source/Editor/EditorCommon.cpp
    Source/Editor/TexturePropertyEditor.cpp
    Source/Editor/TexturePropertyEditor.h
    Source/Editor/TexturePropertyEditor.ui
    Source/Editor/MipmapSettingWidget.cpp
    Source/Editor/MipmapSettingWidget.h
    Source/Editor/MipmapSettingWidget.ui
    Source/Editor/ResolutionSettingWidget.cpp
    Source/Editor/ResolutionSettingWidget.h
    Source/Editor/ResolutionSettingWidget.ui
    Source/Editor/ResolutionSettingItemWidget.cpp
    Source/Editor/ResolutionSettingItemWidget.h
    Source/Editor/ResolutionSettingItemWidget.ui
    Source/Editor/TexturePresetSelectionWidget.cpp
    Source/Editor/TexturePresetSelectionWidget.h
    Source/Editor/TexturePresetSelectionWidget.ui
    Source/Editor/TexturePreviewWidget.cpp
    Source/Editor/TexturePreviewWidget.h
    Source/Editor/TexturePreviewWidget.ui
    Source/Editor/ImagePopup.cpp
    Source/Editor/ImagePopup.h
    Source/Editor/ImagePopup.ui
    Source/Editor/PresetInfoPopup.cpp
    Source/Editor/PresetInfoPopup.h
    Source/Editor/PresetInfoPopup.ui
    Source/Converters/Gamma.cpp
    Source/Converters/FIR-Filter.cpp
    Source/Converters/FIR-Windows.h
    Source/Converters/FIR-Weights.h
    Source/Converters/FIR-Weights.cpp
    Source/Converters/AlphaCoverage.cpp
    Source/Converters/PixelOperation.h
    Source/Converters/PixelOperation.cpp
    Source/Converters/Normalize.cpp
    Source/Converters/ConvertPixelFormat.cpp
    Source/Converters/Cubemap.h
    Source/Converters/Cubemap.cpp
    Source/Converters/ColorChart.cpp
    Source/Converters/HighPass.cpp
    Source/Converters/Histogram.cpp
    Source/Converters/Histogram.h
    ../External/CubeMapGen/CBBoxInt32.cpp
    ../External/CubeMapGen/CBBoxInt32.h
    ../External/CubeMapGen/CCubeMapProcessor.cpp
    ../External/CubeMapGen/CCubeMapProcessor.h
    ../External/CubeMapGen/CImageSurface.cpp
    ../External/CubeMapGen/CImageSurface.h
    ../External/CubeMapGen/VectorMacros.h
    Source/Compressors/Compressor.h
    Source/Compressors/Compressor.cpp
    Source/Compressors/CTSquisher.h
    Source/Compressors/CTSquisher.cpp
    Source/Compressors/PVRTC.cpp
    Source/Compressors/PVRTC.h
    Source/Compressors/ETC2.cpp
    Source/Compressors/ETC2.h
    Source/Compressors/CryTextureSquisher/ColorBlockRGBA4x4f.cpp
    Source/Compressors/CryTextureSquisher/ColorBlockRGBA4x4s.cpp
    Source/Compressors/CryTextureSquisher/ColorBlockRGBA4x4c.cpp
    Source/Compressors/CryTextureSquisher/ColorBlockRGBA4x4f.h
    Source/Compressors/CryTextureSquisher/ColorBlockRGBA4x4s.h
    Source/Compressors/CryTextureSquisher/ColorBlockRGBA4x4c.h
    Source/Compressors/CryTextureSquisher/ColorTypes.h
    Source/AtlasBuilder/AtlasBuilderComponent.h
    Source/AtlasBuilder/AtlasBuilderComponent.cpp
    Source/AtlasBuilder/AtlasBuilderWorker.h
    Source/AtlasBuilder/AtlasBuilderWorker.cpp
)

set(SKIP_UNITY_BUILD_INCLUSION_FILES
    Source/Compressors/PVRTC.cpp
    Source/Compressors/PVRTC.h
)


