#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Common/Camera.cpp
    Common/Camera.h
    Common/Camera.inl
    Common/FirstPersonCamera.cpp
    Common/FirstPersonCamera.h
    Common/LookAtCamera.cpp
    Common/LookAtCamera.h
    Common/MCommonConfig.h
    Common/OrbitCamera.cpp
    Common/OrbitCamera.h
    Common/OrthographicCamera.cpp
    Common/OrthographicCamera.h
    Common/RenderUtil.cpp
    Common/RenderUtil.h
    Common/RotateManipulator.cpp
    Common/RotateManipulator.h
    Common/ScaleManipulator.cpp
    Common/ScaleManipulator.h
    Common/TransformationManipulator.h
    Common/TranslateManipulator.cpp
    Common/TranslateManipulator.h
    OpenGL2/Source/GBuffer.cpp
    OpenGL2/Source/GBuffer.h
    OpenGL2/Source/GLActor.cpp
    OpenGL2/Source/glactor.h
    OpenGL2/Source/GLExtensions.h
    OpenGL2/Source/GLExtensions.cpp
    OpenGL2/Source/GLRenderUtil.cpp
    OpenGL2/Source/GLRenderUtil.h
    OpenGL2/Source/GLSLShader.cpp
    OpenGL2/Source/GLSLShader.h
    OpenGL2/Source/GraphicsManager.cpp
    OpenGL2/Source/GraphicsManager.h
    OpenGL2/Source/IndexBuffer.cpp
    OpenGL2/Source/IndexBuffer.h
    OpenGL2/Source/Light.h
    OpenGL2/Source/Material.cpp
    OpenGL2/Source/Material.h
    OpenGL2/Source/PostProcessShader.cpp
    OpenGL2/Source/PostProcessShader.h
    OpenGL2/Source/RenderGLConfig.h
    OpenGL2/Source/RenderTexture.cpp
    OpenGL2/Source/RenderTexture.h
    OpenGL2/Source/Shader.h
    OpenGL2/Source/ShaderCache.cpp
    OpenGL2/Source/shadercache.h
    OpenGL2/Source/StandardMaterial.cpp
    OpenGL2/Source/StandardMaterial.h
    OpenGL2/Source/TextureCache.cpp
    OpenGL2/Source/TextureCache.h
    OpenGL2/Source/VertexBuffer.cpp
    OpenGL2/Source/VertexBuffer.h
)
