#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#

set(FILES
    ../RenderDll_precompiled.cpp
    ../Common/Renderer_Jobs.cpp
    resource.h
    ../Common/CommonRender.cpp
    ../Common/Renderer.cpp
    ../Common/RenderPipeline.cpp
    ../Common/RenderThread.cpp
    ../Common/ResFile.cpp
    ../Common/ResFileLookupDataMan.cpp
    ../Common/ShadowUtils.cpp
    ../Common/TextMessages.cpp
    ../Common/WaterUtils.cpp
    ../Common/ResFileLookupDataMan.h
    ../Common/TextMessages.h
    ../Common/CommonRender.h
    ../Common/FrameProfiler.h
    ../Common/IColorGradingControllerInt.h
    ../Common/OcclQuery.h
    ../Common/Renderer.h
    ../Common/RenderPipeline.h
    ../Common/RenderThread.h
    ../Common/ResFile.h
    ../Common/ResFile_info.h
    ../Common/Shadow_Renderer.h
    ../Common/ShadowUtils.h
    ../Common/WaterUtils.h
    ../XRenderD3D9/DeviceManager/Enums.h
    ../Common/RendElements/CREBeam.cpp
    ../Common/RendElements/CREClientPoly.cpp
    ../Common/RendElements/CRECloud.cpp
    ../Common/RendElements/CREDeferredShading.cpp
    ../Common/RendElements/CREFogVolume.cpp
    ../Common/RendElements/CREGameEffect.cpp
    ../Common/RendElements/CREHDRProcess.cpp
    ../Common/RendElements/CREImposter.cpp
    ../Common/RendElements/CREMesh.cpp
    ../Common/RendElements/CREOclusionQuery.cpp
    ../Common/RendElements/CREPostProcess.cpp
    ../Common/RendElements/CREPrismObject.cpp
    ../Common/RendElements/CRESky.cpp
    ../Common/RendElements/CREVolumeObject.cpp
    ../Common/RendElements/CREWaterOcean.cpp
    ../Common/RendElements/CREWaterVolume.cpp
    ../Common/RendElements/RendElement.cpp
    ../Common/RendElements/CREGeomCache.cpp
    ../Common/RendElements/CRELensOptics.h
    ../Common/RendElements/CREBeam.h
    ../Common/RendElements/CREClientPoly.h
    ../Common/RendElements/CRECloud.h
    ../Common/RendElements/CREDeferredShading.h
    ../Common/RendElements/CREHDRProcess.h
    ../Common/RendElements/Stars.h
    ../Common/RendElements/Utils/PolygonMath2D.cpp
    ../Common/RendElements/Utils/PolygonMath2D.h
    ../Common/RendElements/Utils/SpatialHashGrid.h
    ../Common/PostProcess/PostEffects.cpp
    ../Common/PostProcess/PostProcess.cpp
    ../Common/PostProcess/PostProcessUtils.cpp
    ../Common/PostProcess/PostEffects.h
    ../Common/PostProcess/PostProcess.h
    ../Common/PostProcess/PostProcessUtils.h
    ../Common/Memory/VRAMDriller.cpp
    ../Common/Memory/VRAMDriller.h
    ../Common/Memory/VRAMDrillerBus.h
    ../Common/RenderMesh_Render.cpp
    ../Common/RenderMesh_SetMesh.cpp
    ../Common/RenderMesh.cpp
    ../Common/RenderMesh.h
    ../Common/Textures/ITextureStreamer.cpp
    ../Common/Textures/PlanningTextureStreamer.cpp
    ../Common/Textures/PlanningTextureStreamer_Jobs.cpp
    ../Common/Textures/DynTexture.cpp
    ../Common/Textures/PowerOf2BlockPacker.cpp
    ../Common/Textures/Texture.cpp
    ../Common/Textures/TextureManager.cpp
    ../Common/Textures/TextureStreaming.cpp
    ../Common/Textures/PlanningTextureStreamer.h
    ../Common/Textures/TextureStreamPool.h
    ../Common/Textures/PowerOf2BlockPacker.h
    ../Common/Textures/Texture.h
    ../Common/Textures/StereoTexture.cpp
    ../Common/Textures/StereoTexture.h
    ../Common/Textures/TextureManager.h
    ../Common/Textures/Image/CImage.cpp
    ../Common/Textures/Image/DDSImage.cpp
    ../Common/Textures/Image/JpgImage.cpp
    ../Common/Textures/Image/TgaImage.cpp
    ../Common/Textures/Image/CImage.h
    ../Common/Textures/Image/DDSImage.h
    ../Common/Shaders/Parser.cpp
    ../Common/Shaders/ParserBin.cpp
    ../Common/Shaders/PoundPoundParser.cpp
    ../Common/Shaders/ShaderCache.cpp
    ../Common/Shaders/ShaderComponents.cpp
    ../Common/Shaders/ShaderCore.cpp
    ../Common/Shaders/ShaderFXParseBin.cpp
    ../Common/Shaders/ShaderParse.cpp
    ../Common/Shaders/ShaderScript.cpp
    ../Common/Shaders/ShaderTemplate.cpp
    ../Common/Shaders/ShaderResources.cpp
    ../Common/Shaders/CShader.h
    ../Common/Shaders/CShaderBin.h
    ../Common/Shaders/Parser.h
    ../Common/Shaders/ParserBin.h
    ../Common/Shaders/PoundPoundParser.h
    ../Common/Shaders/Shader.h
    ../Common/Shaders/ShaderCache.h
    ../Common/Shaders/ShaderComponents.h
    ../Common/Shaders/ShaderResources.h
    ../Common/Shaders/Vertex.h
)
