#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Source/RHI/AliasedHeap.cpp
    Source/RHI/AliasedHeap.h
    Source/RHI/AsyncUploadQueue.cpp
    Source/RHI/AsyncUploadQueue.h    
    Source/RHI/BindGroupLayout.cpp
    Source/RHI/BindGroupLayout.h
    Source/RHI/BindGroup.cpp
    Source/RHI/BindGroup.h    
    Source/RHI/Buffer.cpp
    Source/RHI/Buffer.h
    Source/RHI/BufferView.cpp
    Source/RHI/BufferView.h
    Source/RHI/BufferPool.cpp
    Source/RHI/BufferPool.h
    Source/RHI/BufferPoolResolver.cpp
    Source/RHI/BufferPoolResolver.h
    Source/RHI/CommandList.cpp
    Source/RHI/CommandList.h
    Source/RHI/CommandQueue.cpp
    Source/RHI/CommandQueue.h
    Source/RHI/CommandQueueContext.cpp
    Source/RHI/CommandQueueContext.h
    Source/RHI/ComputePipeline.cpp
    Source/RHI/ComputePipeline.h
    Source/RHI/Conversions.cpp
    Source/RHI/Conversions.h
    Source/RHI/Device.cpp
    Source/RHI/Device.h
    Source/RHI/DispatchRaysIndirectBuffer.h
    Source/RHI/Fence.cpp
    Source/RHI/Fence.h
    Source/RHI/FrameGraphCompiler.cpp
    Source/RHI/FrameGraphCompiler.h
    Source/RHI/FrameGraphExecuter.cpp
    Source/RHI/FrameGraphExecuter.h
    Source/RHI/FrameGraphExecuteGroup.cpp
    Source/RHI/FrameGraphExecuteGroup.h
    Source/RHI/FrameGraphExecuteGroupBase.cpp
    Source/RHI/FrameGraphExecuteGroupBase.h
    Source/RHI/FrameGraphExecuteGroupMerged.cpp
    Source/RHI/FrameGraphExecuteGroupMerged.h
    Source/RHI/Image.cpp
    Source/RHI/Image.h
    Source/RHI/ImagePool.cpp
    Source/RHI/ImagePool.h
    Source/RHI/ImagePoolResolver.cpp
    Source/RHI/ImagePoolResolver.h
    Source/RHI/ImageView.cpp
    Source/RHI/ImageView.h
    Source/RHI/Instance.cpp
    Source/RHI/Instance.h
    Source/RHI/NullDescriptorManager.cpp
    Source/RHI/NullDescriptorManager.h    
    Source/RHI/PhysicalDevice.cpp
    Source/RHI/PhysicalDevice.h
    Source/RHI/Pipeline.cpp
    Source/RHI/Pipeline.h
    Source/RHI/PipelineLayout.cpp
    Source/RHI/PipelineLayout.h
    Source/RHI/PipelineState.cpp
    Source/RHI/PipelineState.h
    Source/RHI/PipelineLibrary.cpp
    Source/RHI/PipelineLibrary.h
    Source/RHI/Query.cpp
    Source/RHI/Query.h
    Source/RHI/QueryPool.cpp
    Source/RHI/QueryPool.h
    Source/RHI/RenderPipeline.cpp
    Source/RHI/RenderPipeline.h
    Source/RHI/ResourcePoolResolver.h
    Source/RHI/RootConstantManager.cpp
    Source/RHI/RootConstantManager.h
    Source/RHI/Sampler.cpp
    Source/RHI/Sampler.h
    Source/RHI/Scope.cpp
    Source/RHI/Scope.h
    Source/RHI/ShaderModule.cpp
    Source/RHI/ShaderModule.h
    Source/RHI/ShaderResourceGroup.cpp
    Source/RHI/ShaderResourceGroup.h
    Source/RHI/ShaderResourceGroupPool.cpp
    Source/RHI/ShaderResourceGroupPool.h
    Source/RHI/StreamingImagePool.cpp
    Source/RHI/StreamingImagePool.h
    Source/RHI/SwapChain.cpp
    Source/RHI/SwapChain.h
    Source/RHI/SystemComponent.cpp
    Source/RHI/SystemComponent.h
    Source/RHI/TransientAttachmentPool.cpp
    Source/RHI/TransientAttachmentPool.h
    Source/RHI/TextureFormats.inl
    Source/RHI/VertexFormats.inl
    Source/RHI/RayTracingBufferPools.h
    Source/RHI/RayTracingBlas.cpp
    Source/RHI/RayTracingBlas.h
    Source/RHI/RayTracingTlas.cpp
    Source/RHI/RayTracingTlas.h
    Source/RHI/RayTracingPipelineState.cpp
    Source/RHI/RayTracingPipelineState.h
    Source/RHI/RayTracingShaderTable.cpp
    Source/RHI/RayTracingShaderTable.h
    Source/RHI/WebGPU.cpp
    Source/RHI/WebGPU.h
)
