<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>StartingPointInput</name>
    <message>
        <location filename="../../../Code/Source/InputConfigurationComponent.cpp" line="48"/>
        <source>InputEventGroup</source>
        <translation>输入事件组</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputConfigurationComponent.cpp" line="49"/>
        <source>Groups input bindings by the event they generate</source>
        <translation>按生成的事件对输入绑定进行分组</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputConfigurationComponent.cpp" line="54"/>
        <source>Event Name</source>
        <translation>事件名称</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputConfigurationComponent.cpp" line="55"/>
        <source>The event generated by the collection of Input Bindings</source>
        <translation>由输入绑定集合生成的事件</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputConfigurationComponent.cpp" line="58"/>
        <source>Event Generators</source>
        <translation>事件生成器</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputConfigurationComponent.cpp" line="59"/>
        <source>Handlers that generate named events</source>
        <translation>生成命名事件的处理器</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputConfigurationComponent.cpp" line="61"/>
        <source>Exclude from release</source>
        <translation>从发布版本中排除</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputConfigurationComponent.cpp" line="62"/>
        <source>This input binding will not activate in release builds</source>
        <translation>此输入绑定在发布版本中不会激活</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputConfigurationComponent.cpp" line="107"/>
        <source>Input</source>
        <translation>输入</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputConfigurationComponent.cpp" line="108"/>
        <source>The Input component allows an entity to bind a set of inputs to an event by referencing a .inputbindings file</source>
        <translation>输入组件允许实体通过引用 .inputbindings 文件将一组输入绑定到事件</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputConfigurationComponent.cpp" line="117"/>
        <source>Input to event bindings</source>
        <translation>输入到事件的绑定</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputConfigurationComponent.cpp" line="118"/>
        <source>Asset containing input to event binding information.</source>
        <translation>包含输入到事件绑定信息的资产。</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputConfigurationComponent.cpp" line="126"/>
        <source>Local player index</source>
        <translation>本地玩家索引</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputConfigurationComponent.cpp" line="127"/>
        <source>The player index that this component will receive input from (0 based, -1 means all controllers).
Will only work on platforms such as PC where the local user id corresponds to the local player index.
For other platforms, SetLocalUserId must be called at runtime with the id of a logged in user.</source>
        <translation>此组件接收输入的玩家索引（从 0 开始，-1 表示所有控制器）。
仅在本地用户 ID 与本地玩家索引对应的平台（如 PC）上有效。
对于其他平台，必须在运行时使用已登录用户的 ID 调用 SetLocalUserId。</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="43"/>
        <source>InputEventMap</source>
        <translation>输入事件映射</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="44"/>
        <source>Maps raw input to a game specific input event</source>
        <translation>将原始输入映射到游戏特定的输入事件</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="49"/>
        <source>Input Device Type</source>
        <translation>输入设备类型</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="50"/>
        <source>The type of input device, ex keyboard</source>
        <translation>输入设备的类型，例如键盘</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="54"/>
        <source>Input Name</source>
        <translation>输入名称</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="55"/>
        <source>The name of the input you want to hold ex. space</source>
        <translation>要按住的输入名称，例如空格键</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="59"/>
        <source>Event value multiplier</source>
        <translation>事件值乘数</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="60"/>
        <source>When the event fires, the value will be scaled by this multiplier</source>
        <translation>当事件触发时，值将按此乘数进行缩放</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="63"/>
        <source>Dead zone</source>
        <translation>死区</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="64"/>
        <source>An event will only be sent out if the value is above this threshold</source>
        <translation>只有当值超过此阈值时才会发送事件</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="229"/>
        <source>ThumbstickInputEventMap</source>
        <translation>摇杆输入事件映射</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="230"/>
        <source>Generate events from thumbstick input</source>
        <translation>从摇杆输入生成事件</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="235"/>
        <source>Inner Dead Zone Radius</source>
        <translation>内死区半径</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="236"/>
        <source>The thumbstick axes vector (x,y) will be normalized between this value and Outer Dead Zone Radius</source>
        <translation>摇杆轴向量 (x,y) 将在此值与外死区半径之间进行归一化</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="240"/>
        <source>Outer Dead Zone Radius</source>
        <translation>外死区半径</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="241"/>
        <source>The thumbstick axes vector (x,y) will be normalized between Inner Dead Zone Radius and this value</source>
        <translation>摇杆轴向量 (x,y) 将在内死区半径与此值之间进行归一化</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="245"/>
        <source>Axis Dead Zone Value</source>
        <translation>轴死区值</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="246"/>
        <source>The individual axis values will be normalized between this and 1.0f</source>
        <translation>各个轴的值将在此值与 1.0 之间进行归一化</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="250"/>
        <source>Sensitivity Exponent</source>
        <translation>灵敏度指数</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="251"/>
        <source>The sensitivity exponent to apply to the normalized thumbstick components</source>
        <translation>应用于归一化摇杆分量的灵敏度指数</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="253"/>
        <source>Output Axis</source>
        <translation>输出轴</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="254"/>
        <source>The axis value to output after peforming the dead-zone and sensitivity calculations</source>
        <translation>在执行死区和灵敏度计算后输出的轴值</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="258"/>
        <source>x</source>
        <translation>x</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventMap.cpp" line="259"/>
        <source>y</source>
        <translation>y</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/StartingPointInputGem.cpp" line="136"/>
        <source>Starting point input</source>
        <translation>起始点输入</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/StartingPointInputGem.cpp" line="137"/>
        <source>Manages input bindings and events</source>
        <translation>管理输入绑定和事件</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventBindings.h" line="47"/>
        <source>Input Event Bindings</source>
        <translation>输入事件绑定</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventBindings.h" line="48"/>
        <source>Holds InputEventBindings</source>
        <translation>保存输入事件绑定</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventBindings.h" line="51"/>
        <location filename="../../../Code/Source/InputEventBindings.h" line="52"/>
        <source>Input Event Groups</source>
        <translation>输入事件组</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventBindings.h" line="119"/>
        <source>Input to Event Bindings Asset</source>
        <translation>输入到事件绑定资产</translation>
    </message>
    <message>
        <location filename="../../../Code/Source/InputEventBindings.h" line="121"/>
        <source>Bindings</source>
        <translation>绑定</translation>
    </message>
</context>
</TS>
