#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#

set(FILES
    AutoDetectSpec.cpp
    AZCrySystemInitLogSink.cpp
    ClientHandler.cpp
    CmdLine.cpp
    CmdLineArg.cpp
    CompressedFile.cpp
    ConsoleBatchFile.cpp
    ConsoleHelpGen.cpp
    CryAsyncMemcpy.cpp
    HandlerBase.cpp
    Log.cpp
    SystemRender.cpp
    PhysRenderer.cpp
    ServerHandler.cpp
    ServerThrottle.cpp
    SyncLock.cpp
    System.cpp
    SystemCFG.cpp
    SystemEventDispatcher.cpp
    SystemInit.cpp
    SystemWin32.cpp
    Timer.cpp
    UnixConsole.cpp
    WindowsConsole.cpp
    XConsole.cpp
    XConsoleVariable.cpp
    AutoDetectSpec.h
    ClientHandler.h
    HandlerBase.h
    PhysRenderer.h
    ServerHandler.h
    ServerThrottle.h
    SyncLock.h
    UnixConsole.h
    SystemInit.h
    XML/ReadWriteXMLSink.h
    AZCrySystemInitLogSink.h
    AZCoreLogSink.h
    CmdLine.h
    CmdLineArg.h
    ConsoleBatchFile.h
    ConsoleHelpGen.h
    CryWaterMark.h
    Log.h
    resource.h
    SimpleStringPool.h
    CrySystem_precompiled.h
    System.h
    SystemCFG.h
    SystemEventDispatcher.h
    Timer.h
    Validator.h
    WindowsConsole.h
    XConsole.h
    XConsoleVariable.h
    XML/SerializeXMLReader.cpp
    XML/SerializeXMLWriter.cpp
    XML/xml.cpp
    XML/XMLPatcher.cpp
    XML/XmlUtils.cpp
    XML/SerializeXMLReader.h
    XML/SerializeXMLWriter.h
    XML/xml.h
    XML/XMLPatcher.h
    XML/xml_string.h
    XML/XmlUtils.h
    XML/ReadXMLSink.cpp
    XML/WriteXMLSource.cpp
    ZipFile.h
    ZipFileFormat_info.h
    Sampler.cpp
    Sampler.h
    LocalizedStringManager.cpp
    LocalizedStringManager.h
    ZLibCompressor.cpp
    ZLibCompressor.h
    Huffman.cpp
    Huffman.h
    RemoteConsole/RemoteConsole.cpp
    RemoteConsole/RemoteConsole.h
    RemoteConsole/RemoteConsole_impl.inl
    RemoteConsole/RemoteConsole_none.inl
    ZLibDecompressor.h
    ZLibDecompressor.cpp
    LZ4Decompressor.h
    LZ4Decompressor.cpp
    LevelSystem/LevelSystem.cpp
    LevelSystem/LevelSystem.h
    LevelSystem/SpawnableLevelSystem.cpp
    LevelSystem/SpawnableLevelSystem.h
    ViewSystem/DebugCamera.cpp
    ViewSystem/DebugCamera.h
    ViewSystem/View.cpp
    ViewSystem/View.h
    ViewSystem/ViewSystem.cpp
    ViewSystem/ViewSystem.h
    ZStdDecompressor.h
    ZStdDecompressor.cpp
    CrySystem_precompiled.cpp
    CPUDetect.cpp
    CPUDetect.h
    WindowsErrorReporting.cpp
)
