#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Source/Editor/ATLControlsPanel.ui
    Source/Editor/AudioControlsEditorMainWindow.ui
    Source/Editor/AudioControlsEditorUI.qrc
    Source/Editor/AudioSystemPanel.ui
    Source/Editor/ConnectionsWidget.ui
    Source/Editor/InspectorPanel.ui
    Source/Editor/QATLControlsTreeModel.cpp
    Source/Editor/QATLControlsTreeModel.h
    Source/Editor/QAudioControlEditorIcons.h
    Source/Editor/QAudioControlTreeWidget.cpp
    Source/Editor/QAudioControlTreeWidget.h
    Source/Editor/QConnectionListWidget.h
    Source/Editor/QConnectionsWidget.cpp
    Source/Editor/QConnectionsWidget.h
    Source/Editor/QSimpleAudioControlListWidget.cpp
    Source/Editor/QSimpleAudioControlListWidget.h
    Source/Editor/QTreeWidgetFilter.cpp
    Source/Editor/QTreeWidgetFilter.h
    Source/Editor/ATLControlsModel.cpp
    Source/Editor/ATLControlsPanel.cpp
    Source/Editor/ATLControlsResourceDialog.cpp
    Source/Editor/AudioControl.cpp
    Source/Editor/AudioControlFilters.cpp
    Source/Editor/AudioControlsEditorPlugin.cpp
    Source/Editor/AudioControlsEditorUndo.cpp
    Source/Editor/AudioControlsEditorWindow.cpp
    Source/Editor/AudioControlsLoader.cpp
    Source/Editor/AudioControlsWriter.cpp
    Source/Editor/AudioResourceSelectors.cpp
    Source/Editor/AudioSystemPanel.cpp
    Source/Editor/ImplementationManager.cpp
    Source/Editor/InspectorPanel.cpp
    Source/Editor/ACEEnums.h
    Source/Editor/ATLControlsModel.h
    Source/Editor/ATLControlsPanel.h
    Source/Editor/ATLControlsResourceDialog.h
    Source/Editor/AudioControl.h
    Source/Editor/AudioControlFilters.h
    Source/Editor/AudioControlsEditorPlugin.h
    Source/Editor/AudioControlsEditorUndo.h
    Source/Editor/AudioControlsEditorWindow.h
    Source/Editor/AudioControlsLoader.h
    Source/Editor/AudioControlsWriter.h
    Source/Editor/AudioResourceSelectors.h
    Source/Editor/AudioSystemPanel.h
    Source/Editor/ImplementationManager.h
    Source/Editor/InspectorPanel.h
)
