#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

# Based on the linux window manager trait, perform the appropriate additional build configurations
# Only 'xcb' and 'wayland' are recognized
if(PAL_TRAIT_LINUX_WINDOW_MANAGER_XCB)

    set(LY_COMPILE_DEFINITIONS PUBLIC PAL_TRAIT_LINUX_WINDOW_MANAGER_XCB)
    set(LY_INCLUDE_DIRECTORIES
        PUBLIC
            Platform/Common/Xcb
    )
    set(LY_FILES_CMAKE
        Platform/Common/Xcb/azframework_xcb_files.cmake
    )
    set(LY_BUILD_DEPENDENCIES
        PRIVATE
            3rdParty::X11::xcb
            3rdParty::X11::xcb_xkb
            3rdParty::X11::xcb_xfixes
            3rdParty::X11::xcb_randr
            3rdParty::X11::xkbcommon
            3rdParty::X11::xkbcommon_X11
            xcb-xinput
            xcb-keysyms
    )
endif()

if(PAL_TRAIT_LINUX_WINDOW_MANAGER_WAYLAND)
    # Protocol files to generate
    # Paths are relative to the pkgdatadir of wayland-protocols, .xml is automatically appended
    # Update gen_license.py when adding or removing protocols
    set(WAYLAND_PROTOCOLS
            stable/xdg-shell/xdg-shell
            unstable/xdg-decoration/xdg-decoration-unstable-v1
            staging/cursor-shape/cursor-shape-v1
            stable/tablet/tablet-v2
            unstable/pointer-constraints/pointer-constraints-unstable-v1
            unstable/relative-pointer/relative-pointer-unstable-v1
    )

    execute_process(
            COMMAND pkg-config --variable=pkgdatadir wayland-protocols
            OUTPUT_VARIABLE WAYLAND_PROTOCOLS_PKGDATADIR
            OUTPUT_STRIP_TRAILING_WHITESPACE
    )

    if(${WAYLAND_PROTOCOLS_PKGDATADIR} STREQUAL "")
        message(FATAL_ERROR "Failed to get pkgdatadir for wayland-protocols. Ensure wayland-protocols is installed.")
    endif()

    find_program(WAYLAND_SCANNER wayland-scanner)
    if(NOT WAYLAND_SCANNER)
        message(FATAL_ERROR "wayland-scanner not found")
    endif()

    set(WAYLAND_PROTOCOL_GENERATED_DIR "${CMAKE_CURRENT_BINARY_DIR}/AutoGenerated/${CMAKE_BUILD_TYPE}/WaylandProtocols")
    set(WAYLAND_PROTOCOL_INCLUDE_DIR "${WAYLAND_PROTOCOL_GENERATED_DIR}/Include")
    set(WAYLAND_PROTOCOL_SRC_DIR "${WAYLAND_PROTOCOL_GENERATED_DIR}/Source")

    foreach(PROTOCOL ${WAYLAND_PROTOCOLS})
        get_filename_component(PROTOCOL_NAME "${PROTOCOL}" NAME)
        set(PROTO_XML "${WAYLAND_PROTOCOLS_PKGDATADIR}/${PROTOCOL}.xml")
        set(PROTO_H "${WAYLAND_PROTOCOL_INCLUDE_DIR}/${PROTOCOL_NAME}-client-protocol.h")
        set(PROTO_C "${WAYLAND_PROTOCOL_SRC_DIR}/${PROTOCOL_NAME}-client-protocol.c")

        list(APPEND LY_FILES ${PROTO_C} ${PROTO_H})

        add_custom_command(
                OUTPUT ${PROTO_H} ${PROTO_C}
                COMMAND ${CMAKE_COMMAND} -E make_directory "${WAYLAND_PROTOCOL_INCLUDE_DIR}"
                COMMAND ${CMAKE_COMMAND} -E make_directory "${WAYLAND_PROTOCOL_SRC_DIR}"
                COMMAND ${WAYLAND_SCANNER} client-header ${PROTO_XML} ${PROTO_H}
                COMMAND ${WAYLAND_SCANNER} private-code ${PROTO_XML} ${PROTO_C}
                DEPENDS ${PROTO_XML}
                VERBATIM
        )
    endforeach()

    list(APPEND LY_COMPILE_DEFINITIONS PUBLIC PAL_TRAIT_LINUX_WINDOW_MANAGER_WAYLAND)
    list(APPEND LY_INCLUDE_DIRECTORIES
        PUBLIC
            Platform/Common/Wayland
            ${WAYLAND_PROTOCOL_INCLUDE_DIR}
    )
    list(APPEND LY_FILES_CMAKE
            Platform/Common/Wayland/azframework_wayland_files.cmake
    )
    list(APPEND LY_BUILD_DEPENDENCIES
        PRIVATE
            3rdParty::X11::xkbcommon
            wayland-client
            wayland-cursor
    )
endif()
