#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Source/ActorCommands.cpp
    Source/ActorCommands.h
    Source/ActorInstanceCommands.cpp
    Source/ActorInstanceCommands.h
    Source/AnimGraphCommands.cpp
    Source/AnimGraphCommands.h
    Source/AnimGraphConditionCommands.cpp
    Source/AnimGraphConditionCommands.h
    Source/AnimGraphConnectionCommands.cpp
    Source/AnimGraphConnectionCommands.h
    Source/AnimGraphCopyPasteData.cpp
    Source/AnimGraphCopyPasteData.h
    Source/AnimGraphNodeCommands.cpp
    Source/AnimGraphNodeCommands.h
    Source/AnimGraphNodeGroupCommands.cpp
    Source/AnimGraphNodeGroupCommands.h
    Source/AnimGraphParameterCommands.cpp
    Source/AnimGraphParameterCommands.h
    Source/AnimGraphGroupParameterCommands.cpp
    Source/AnimGraphGroupParameterCommands.h
    Source/AnimGraphTriggerActionCommands.cpp
    Source/AnimGraphTriggerActionCommands.h
    Source/CommandManager.cpp
    Source/CommandManager.h
    Source/ColliderCommands.cpp
    Source/ColliderCommands.h
    Source/CommandSystemConfig.h
    Source/ImporterCommands.cpp
    Source/ImporterCommands.h
    Source/MetaData.cpp
    Source/MetaData.h
    Source/MiscCommands.cpp
    Source/MiscCommands.h
    Source/MorphTargetCommands.cpp
    Source/MorphTargetCommands.h
    Source/MotionCommands.cpp
    Source/MotionCommands.h
    Source/MotionEventCommands.cpp
    Source/MotionEventCommands.h
    Source/MotionSetCommands.cpp
    Source/MotionSetCommands.h
    Source/NodeGroupCommands.cpp
    Source/NodeGroupCommands.h
    Source/ParameterMixins.cpp
    Source/ParameterMixins.h
    Source/RagdollCommands.cpp
    Source/RagdollCommands.h
    Source/SelectionCommands.cpp
    Source/SelectionCommands.h
    Source/SelectionList.cpp
    Source/SelectionList.h
    Source/SimulatedObjectCommands.cpp
    Source/SimulatedObjectCommands.h
)
