/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

#pragma once

#include <AzCore/PlatformDef.h>

#if defined(AZ_MONOLITHIC_BUILD)
    #define ATOM_RPI_PUBLIC_API
#else
    #if defined(ATOM_RPI_PUBLIC_EXPORTS)
        #define ATOM_RPI_PUBLIC_API AZ_DLL_EXPORT
    #else
        #define ATOM_RPI_PUBLIC_API AZ_DLL_IMPORT
    #endif
#endif

#if defined(AZ_MONOLITHIC_BUILD)

#define ATOMRPI_PUBLIC_DECLARE_EBUS_SINGLE_ADDRESS(a)                       AZ_DECLARE_EBUS_SINGLE_ADDRESS(a)
#define ATOMRPI_PUBLIC_INSTANTIATE_EBUS_SINGLE_ADDRESS(a)                   AZ_INSTANTIATE_EBUS_SINGLE_ADDRESS(a)
#define ATOMRPI_PUBLIC_DECLARE_EBUS_MULTI_ADDRESS(a)                        AZ_DECLARE_EBUS_MULTI_ADDRESS(a)
#define ATOMRPI_PUBLIC_INSTANTIATE_EBUS_MULTI_ADDRESS(a)                    AZ_INSTANTIATE_EBUS_MULTI_ADDRESS(a)
#define ATOMRPI_PUBLIC_DECLARE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(a, b)        AZ_DECLARE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(a, b)
#define ATOMRPI_PUBLIC_INSTANTIATE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(a, b)    AZ_INSTANTIATE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(a, b)
#define ATOMRPI_PUBLIC_DECLARE_EBUS_MULTI_ADDRESS_WITH_TRAITS(a, b)         AZ_DECLARE_EBUS_MULTI_ADDRESS_WITH_TRAITS(a, b)
#define ATOMRPI_PUBLIC_INSTANTIATE_EBUS_MULTI_ADDRESS_WITH_TRAITS(a, b)     AZ_INSTANTIATE_EBUS_MULTI_ADDRESS_WITH_TRAITS(a, b) 

#else

#define ATOMRPI_PUBLIC_DECLARE_EBUS_SINGLE_ADDRESS(a)                        AZ_DECLARE_EBUS_SINGLE_ADDRESS(ATOM_RPI_PUBLIC_API, a)
#define ATOMRPI_PUBLIC_INSTANTIATE_EBUS_SINGLE_ADDRESS(a)                    AZ_INSTANTIATE_EBUS_SINGLE_ADDRESS(ATOM_RPI_PUBLIC_API, a)
#define ATOMRPI_PUBLIC_DECLARE_EBUS_MULTI_ADDRESS(a)                         AZ_DECLARE_EBUS_MULTI_ADDRESS(ATOM_RPI_PUBLIC_API, a)
#define ATOMRPI_PUBLIC_INSTANTIATE_EBUS_MULTI_ADDRESS(a)                     AZ_INSTANTIATE_EBUS_MULTI_ADDRESS(ATOM_RPI_PUBLIC_API, a)
#define ATOMRPI_PUBLIC_DECLARE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(a, b)         AZ_DECLARE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(ATOM_RPI_PUBLIC_API, a, b)
#define ATOMRPI_PUBLIC_INSTANTIATE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(a, b)     AZ_INSTANTIATE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(ATOM_RPI_PUBLIC_API, a, b)
#define ATOMRPI_PUBLIC_DECLARE_EBUS_MULTI_ADDRESS_WITH_TRAITS(a, b)          AZ_DECLARE_EBUS_MULTI_ADDRESS_WITH_TRAITS(ATOM_RPI_PUBLIC_API, a, b)
#define ATOMRPI_PUBLIC_INSTANTIATE_EBUS_MULTI_ADDRESS_WITH_TRAITS(a, b)      AZ_INSTANTIATE_EBUS_MULTI_ADDRESS_WITH_TRAITS(ATOM_RPI_PUBLIC_API, a, b)

#endif //defined(AZ_MONOLITHIC_BUILD)
