/*
* All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
* its licensors.
*
* For complete copyright and license terms please see the LICENSE at the root of this
* distribution (the "License"). All use of this software is governed by the License,
* or, if provided, by the license below or the license accompanying this file. Do not
* remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*
*/
#pragma once

#include "IConsole.h"

// Auto-generated by gmock_gen.py

class IRemoteConsoleMock 
    : public IRemoteConsole 
{
public:
    MOCK_METHOD0(RegisterConsoleVariables, void());
    MOCK_METHOD0(UnregisterConsoleVariables, void());
    MOCK_METHOD0(Start, void());
    MOCK_METHOD0(Stop, void());
    MOCK_CONST_METHOD0(IsStarted, bool());
    MOCK_METHOD1(AddLogMessage, void(const char* log));
    MOCK_METHOD1(AddLogWarning, void(const char* log));
    MOCK_METHOD1(AddLogError, void(const char* log));
    MOCK_METHOD0(Update, void());
    MOCK_METHOD2(RegisterListener, void(IRemoteConsoleListener* pListener, const char* name));
    MOCK_METHOD1(UnregisterListener, void(IRemoteConsoleListener* pListener));
};
