#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Include/TestImpactFramework/TestImpactException.h
    Include/TestImpactFramework/TestImpactRepoPath.h
    Include/TestImpactFramework/TestImpactRuntime.h
    Include/TestImpactFramework/TestImpactRuntimeException.h
    Include/TestImpactFramework/TestImpactConfiguration.h
    Include/TestImpactFramework/TestImpactConfigurationException.h
    Include/TestImpactFramework/TestImpactChangelist.h
    Include/TestImpactFramework/TestImpactChangelistSerializer.h
    Include/TestImpactFramework/TestImpactChangelistException.h
    Include/TestImpactFramework/TestImpactPolicy.h
    Include/TestImpactFramework/TestImpactTestSequence.h
    Include/TestImpactFramework/TestImpactClientTestSelection.h
    Include/TestImpactFramework/TestImpactClientTestRun.h
    Include/TestImpactFramework/TestImpactClientSequenceReport.h
    Include/TestImpactFramework/TestImpactUtils.h
    Include/TestImpactFramework/TestImpactClientSequenceReportSerializer.h
    Include/TestImpactFramework/TestImpactSequenceReportException.h
    Source/Artifact/TestImpactArtifactException.h
    Source/Artifact/Factory/TestImpactNativeTargetDescriptorFactory.cpp
    Source/Artifact/Factory/TestImpactNativeTargetDescriptorFactory.h
    Source/Artifact/Factory/TestImpactPythonTestTargetDescriptorFactory.cpp
    Source/Artifact/Factory/TestImpactPythonTestTargetDescriptorFactory.h
    Source/Artifact/Factory/TestImpactTestEnumerationSuiteFactory.cpp
    Source/Artifact/Factory/TestImpactTestEnumerationSuiteFactory.h
    Source/Artifact/Factory/TestImpactTestRunSuiteFactory.cpp
    Source/Artifact/Factory/TestImpactTestRunSuiteFactory.h
    Source/Artifact/Factory/TestImpactNativeTestTargetMetaMapFactory.cpp
    Source/Artifact/Factory/TestImpactNativeTestTargetMetaMapFactory.h
    Source/Artifact/Factory/TestImpactModuleCoverageFactory.cpp
    Source/Artifact/Factory/TestImpactModuleCoverageFactory.h
    Source/Artifact/Factory/TestImpactDependencyGraphDataFactory.cpp
    Source/Artifact/Factory/TestImpactDependencyGraphDataFactory.h
    Source/Artifact/Static/TestImpactNativeTargetDescriptor.cpp
    Source/Artifact/Static/TestImpactNativeTargetDescriptor.h
    Source/Artifact/Static/TestImpactNativeTargetDescriptorCompiler.cpp
    Source/Artifact/Static/TestImpactNativeTargetDescriptorCompiler.h
    Source/Artifact/Static/TestImpactNativeProductionTargetDescriptor.cpp
    Source/Artifact/Static/TestImpactNativeProductionTargetDescriptor.h
    Source/Artifact/Static/TestImpactTestSuiteMeta.h
    Source/Artifact/Static/TestImpactNativeTestTargetMeta.h
    Source/Artifact/Static/TestImpactNativeTestTargetDescriptor.cpp
    Source/Artifact/Static/TestImpactNativeTestTargetDescriptor.h
    Source/Artifact/Static/TestImpactTargetDescriptor.h
    Source/Artifact/Static/TestImpactPythonTestTargetDescriptor.cpp
    Source/Artifact/Static/TestImpactPythonTestTargetDescriptor.h
    Source/Artifact/Static/TestImpactDependencyGraphData.h
    Source/Artifact/Dynamic/TestImpactTestEnumerationSuite.h
    Source/Artifact/Dynamic/TestImpactTestRunSuite.h
    Source/Artifact/Dynamic/TestImpactTestSuite.h
    Source/Artifact/Dynamic/TestImpactCoverage.h
    Source/BuildTarget/Common/TestImpactBuildTargetTraits.h
    Source/BuildTarget/Common/TestImpactBuildTargetList.h
    Source/BuildTarget/Common/TestImpactBuildTarget.h
    Source/BuildTarget/Native/TestImpactNativeBuildTargetTraits.h
    Source/BuildTarget/Python/TestImpactPythonBuildTargetTraits.h
    Source/Process/TestImpactProcess.cpp
    Source/Process/TestImpactProcess.h
    Source/Process/TestImpactProcessException.h
    Source/Process/TestImpactProcessInfo.cpp
    Source/Process/TestImpactProcessInfo.h
    Source/Process/TestImpactProcessLauncher.h
    Source/Process/JobRunner/TestImpactProcessJob.h
    Source/Process/JobRunner/TestImpactProcessJobInfo.h
    Source/Process/JobRunner/TestImpactProcessJobMeta.cpp
    Source/Process/JobRunner/TestImpactProcessJobMeta.h
    Source/Process/JobRunner/TestImpactProcessJobRunner.h
    Source/Process/Scheduler/TestImpactProcessScheduler.cpp
    Source/Process/Scheduler/TestImpactProcessScheduler.h
    Source/Dependency/TestImpactDynamicDependencyMap.h
    Source/Dependency/TestImpactChangeDependencyList.h
    Source/Dependency/TestImpactDependencyException.h
    Source/Dependency/TestImpactSourceDependency.h
    Source/Dependency/TestImpactTestSelectorAndPrioritizer.h
    Source/Dependency/TestImpactSourceCoveringTestsList.h
    Source/Dependency/TestImpactSourceCoveringTestsList.cpp
    Source/Dependency/TestImpactSourceCoveringTestsSerializer.cpp
    Source/Dependency/TestImpactSourceCoveringTestsSerializer.h
    Source/Target/Common/TestImpactTarget.cpp
    Source/Target/Common/TestImpactTarget.h
    Source/Target/Common/TestImpactTargetList.h
    Source/Target/Common/TestImpactTargetException.h
    Source/Target/Native/TestImpactNativeTarget.cpp
    Source/Target/Native/TestImpactNativeTarget.h
    Source/Target/Native/TestImpactNativeProductionTarget.cpp
    Source/Target/Native/TestImpactNativeProductionTarget.h
    Source/Target/Native/TestImpactNativeProductionTargetList.h
    Source/Target/Native/TestImpactNativeTestTarget.cpp
    Source/Target/Native/TestImpactNativeTestTarget.h
    Source/Target/Native/TestImpactNativeTestTargetList.h
    Source/Target/Python/TestImpactPythonTestTarget.cpp
    Source/Target/Python/TestImpactPythonTestTarget.h
    Source/Target/Python/TestImpactPythonTestTargetList.h
    Source/TestRunner/Common/TestImpactTestRunnerException.h
    Source/TestRunner/Common/TestImpactTestSuiteContainer.h
    Source/TestRunner/Common/TestImpactErrorCodeChecker.cpp
    Source/TestRunner/Common/TestImpactErrorCodeChecker.h
    Source/TestRunner/Common/Job/TestImpactTestJobRunner.h
    Source/TestRunner/Common/Job/TestImpactTestRunWithCoverageJobData.cpp
    Source/TestRunner/Common/Job/TestImpactTestRunWithCoverageJobData.h
    Source/TestRunner/Common/Job/TestImpactTestEnumerationJobData.cpp
    Source/TestRunner/Common/Job/TestImpactTestEnumerationJobData.h
    Source/TestRunner/Common/Job/TestImpactTestRunJobData.cpp
    Source/TestRunner/Common/Job/TestImpactTestRunJobData.h
    Source/TestRunner/Common/Enumeration/TestImpactTestEnumerator.h
    Source/TestRunner/Common/Enumeration/TestImpactTestEnumeration.h
    Source/TestRunner/Common/Enumeration/TestImpactTestEnumerationSerializer.cpp
    Source/TestRunner/Common/Enumeration/TestImpactTestEnumerationSerializer.h
    Source/TestRunner/Common/Run/TestImpactTestRunnerBase.h
    Source/TestRunner/Common/Run/TestImpactTestRunner.h
    Source/TestRunner/Common/Run/TestImpactTestRunnerWithCoverage.h
    Source/TestRunner/Common/Run/TestImpactTestCoverage.cpp
    Source/TestRunner/Common/Run/TestImpactTestCoverage.h
    Source/TestRunner/Common/Run/TestImpactTestRun.cpp
    Source/TestRunner/Common/Run/TestImpactTestRun.h
    Source/TestRunner/Common/Run/TestImpactTestRunSerializer.cpp
    Source/TestRunner/Common/Run/TestImpactTestRunSerializer.h
    Source/TestRunner/Native/TestImpactNativeErrorCodeHandler.cpp
    Source/TestRunner/Native/TestImpactNativeErrorCodeHandler.h
    Source/TestRunner/Native/Enumeration/TestImpactNativeTestEnumerator.h
    Source/TestRunner/Native/Job/TestImpactNativeTestJobInfoGenerator.cpp
    Source/TestRunner/Native/Job/TestImpactNativeTestJobInfoGenerator.h
    Source/TestRunner/Native/Job/TestImpactNativeTestRunJobData.h
    Source/TestRunner/Native/Job/TestImpactNativeTestTargetExtension.h
    Source/TestRunner/Native/Run/TestImpactNativeInstrumentedTestRunner.h
    Source/TestRunner/Native/Run/TestImpactNativeRegularTestRunner.h
    Source/TestRunner/Python/Job/TestImpactPythonTestJobInfoGenerator.cpp
    Source/TestRunner/Python/Job/TestImpactPythonTestJobInfoGenerator.h
    Source/TestRunner/Python/Run/TestImpactPythonTestRunner.cpp
    Source/TestRunner/Python/Run/TestImpactPythonTestRunner.h
    Source/TestEngine/TestImpactTestEngine.cpp
    Source/TestEngine/TestImpactTestEngine.h
    Source/TestEngine/TestImpactTestEngineJob.cpp
    Source/TestEngine/TestImpactTestEngineJob.h
    Source/TestEngine/TestImpactTestEngineEnumeration.cpp
    Source/TestEngine/TestImpactTestEngineEnumeration.h
    Source/TestEngine/TestImpactTestEngineRegularRun.cpp
    Source/TestEngine/TestImpactTestEngineRegularRun.h
    Source/TestEngine/TestImpactTestEngineInstrumentedRun.cpp
    Source/TestEngine/TestImpactTestEngineInstrumentedRun.h
    Source/TestEngine/TestImpactTestEngineException.h
    Source/TestImpactException.cpp
    Source/TestImpactRuntime.cpp
    Source/TestImpactRuntimeUtils.cpp
    Source/TestImpactRuntimeUtils.h
    Source/TestImpactTestTargetExclusionList.h
    Source/TestImpactTestTargetExclusionList.cpp
    Source/TestImpactClientTestSelection.cpp
    Source/TestImpactClientTestRun.cpp
    Source/TestImpactClientSequenceReport.cpp
    Source/TestImpactChangeListSerializer.cpp
    Source/TestImpactClientSequenceReportSerializer.cpp
    Source/TestImpactRepoPath.cpp
    Source/TestImpactUtils.cpp
)
