#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#

set(FILES
    DXMETAL/CryDXMETAL.cpp
    DXMETAL/RenderCapabilities.cpp
    DXMETAL/CryDXMETAL.hpp
    DXMETAL/Definitions/DXMETAL_D3DX11.h
    DXMETAL/Definitions/DXMETAL_D3D11Shader.h
    DXMETAL/Definitions/DXMETAL_D3DCommon.h
    DXMETAL/Definitions/DXMETAL_D3DCompiler.h
    DXMETAL/Definitions/DXMETAL_D3D11.h
    DXMETAL/Definitions/DXMETAL_D3DX11tex.h
    DXMETAL/Definitions/DXMETAL_DXGIFormat.h
    DXMETAL/Definitions/DXMETAL_ID3D11Device.h
    DXMETAL/Definitions/DXMETAL_ID3D11DeviceContext.h
    DXMETAL/Definitions/DXMETAL_IDXGIFactory1.h
    DXMETAL/Definitions/DXMETAL_IDXGISwapChain.h
    DXMETAL/Definitions/DXMETAL_dxgi.h
    DXMETAL/Definitions/DXMETAL_dxgitype.h
    DXMETAL/Definitions/CryDXMETALGuid.hpp
    DXMETAL/Definitions/CryDXMETALLegacy.hpp
    DXMETAL/Definitions/CryDXMETALMisc.hpp
    DXMETAL/Definitions/ICryDXMETALUnknown.hpp
    DXMETAL/Implementation/AppleGPUInfoUtils.h
    DXMETAL/Implementation/GLFormat.cpp
    DXMETAL/Implementation/GLResource.cpp
    DXMETAL/Implementation/GLShader.cpp
    DXMETAL/Implementation/GLState.cpp
    DXMETAL/Implementation/METALCopyShaders.h
    DXMETAL/Implementation/METALContext.cpp
    DXMETAL/Implementation/METALDevice.cpp
    DXMETAL/Implementation/GLCommon.hpp
    DXMETAL/Implementation/GLCryPlatform.hpp
    DXMETAL/Implementation/GLExtensions.hpp
    DXMETAL/Implementation/GLFormat.hpp
    DXMETAL/Implementation/GLPlatform.hpp
    DXMETAL/Implementation/GLResource.hpp
    DXMETAL/Implementation/GLShader.hpp
    DXMETAL/Implementation/GLState.hpp
    DXMETAL/Implementation/METALContext.hpp
    DXMETAL/Implementation/MetalDevice.hpp
    DXMETAL/Interfaces/CCryDXMETALBase.cpp
    DXMETAL/Interfaces/CCryDXMETALBlendState.cpp
    DXMETAL/Interfaces/CCryDXMETALBlob.cpp
    DXMETAL/Interfaces/CCryDXMETALBuffer.cpp
    DXMETAL/Interfaces/CCryDXMETALDepthStencilState.cpp
    DXMETAL/Interfaces/CCryDXMETALDepthStencilView.cpp
    DXMETAL/Interfaces/CCryDXMETALDevice.cpp
    DXMETAL/Interfaces/CCryDXMETALDeviceChild.cpp
    DXMETAL/Interfaces/CCryDXMETALDeviceContext.cpp
    DXMETAL/Interfaces/CCryDXMETALGIAdapter.cpp
    DXMETAL/Interfaces/CCryDXMETALGIFactory.cpp
    DXMETAL/Interfaces/CCryDXMETALGIObject.cpp
    DXMETAL/Interfaces/CCryDXMETALGIOutput.cpp
    DXMETAL/Interfaces/CCryDXMETALInputLayout.cpp
    DXMETAL/Interfaces/CCryDXMETALQuery.cpp
    DXMETAL/Interfaces/CCryDXMETALRasterizerState.cpp
    DXMETAL/Interfaces/CCryDXMETALRenderTargetView.cpp
    DXMETAL/Interfaces/CCryDXMETALResource.cpp
    DXMETAL/Interfaces/CCryDXMETALSamplerState.cpp
    DXMETAL/Interfaces/CCryDXMETALShader.cpp
    DXMETAL/Interfaces/CCryDXMETALShaderReflection.cpp
    DXMETAL/Interfaces/CCryDXMETALShaderResourceView.cpp
    DXMETAL/Interfaces/CCryDXMETALSwapChain.cpp
    DXMETAL/Interfaces/CCryDXMETALSwitchToRef.cpp
    DXMETAL/Interfaces/CCryDXMETALTexture1D.cpp
    DXMETAL/Interfaces/CCryDXMETALTexture2D.cpp
    DXMETAL/Interfaces/CCryDXMETALTexture3D.cpp
    DXMETAL/Interfaces/CCryDXMETALTextureBase.cpp
    DXMETAL/Interfaces/CCryDXMETALUnorderedAccessView.cpp
    DXMETAL/Interfaces/CCryDXMETALView.cpp
    DXMETAL/Interfaces/CCryDXMETALBase.hpp
    DXMETAL/Interfaces/CCryDXMETALBlendState.hpp
    DXMETAL/Interfaces/CCryDXMETALBlob.hpp
    DXMETAL/Interfaces/CCryDXMETALBuffer.hpp
    DXMETAL/Interfaces/CCryDXMETALDepthStencilState.hpp
    DXMETAL/Interfaces/CCryDXMETALDepthStencilView.hpp
    DXMETAL/Interfaces/CCryDXMETALDevice.hpp
    DXMETAL/Interfaces/CCryDXMETALDeviceChild.hpp
    DXMETAL/Interfaces/CCryDXMETALDeviceContext.hpp
    DXMETAL/Interfaces/CCryDXMETALGIAdapter.hpp
    DXMETAL/Interfaces/CCryDXMETALGIFactory.hpp
    DXMETAL/Interfaces/CCryDXMETALGIObject.hpp
    DXMETAL/Interfaces/CCryDXMETALGIOutput.hpp
    DXMETAL/Interfaces/CCryDXMETALInputLayout.hpp
    DXMETAL/Interfaces/CCryDXMETALQuery.hpp
    DXMETAL/Interfaces/CCryDXMETALRasterizerState.hpp
    DXMETAL/Interfaces/CCryDXMETALRenderTargetView.hpp
    DXMETAL/Interfaces/CCryDXMETALResource.hpp
    DXMETAL/Interfaces/CCryDXMETALSamplerState.hpp
    DXMETAL/Interfaces/CCryDXMETALShader.hpp
    DXMETAL/Interfaces/CCryDXMETALShaderReflection.hpp
    DXMETAL/Interfaces/CCryDXMETALShaderResourceView.hpp
    DXMETAL/Interfaces/CCryDXMETALSwapChain.hpp
    DXMETAL/Interfaces/CCryDXMETALSwitchToRef.hpp
    DXMETAL/Interfaces/CCryDXMETALTexture1D.hpp
    DXMETAL/Interfaces/CCryDXMETALTexture2D.hpp
    DXMETAL/Interfaces/CCryDXMETALTexture3D.hpp
    DXMETAL/Interfaces/CCryDXMETALTextureBase.hpp
    DXMETAL/Interfaces/CCryDXMETALUnorderedAccessView.hpp
    DXMETAL/Interfaces/CCryDXMETALView.hpp
    DXMETAL/Interfaces/DXEmulation.hpp
)
