#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    SceneUIConfiguration.h
    SceneUI.qrc
    ManifestMetaInfoHandler.h
    ManifestMetaInfoHandler.cpp
    GraphMetaInfoHandler.h
    GraphMetaInfoHandler.cpp
    CommonWidgets/OverlayWidget.h
    CommonWidgets/JobWatcher.h
    CommonWidgets/JobWatcher.cpp
    CommonWidgets/SceneSettingsCard.h
    CommonWidgets/SceneSettingsCard.cpp
    CommonWidgets/ExpandCollapseToggler.h
    CommonWidgets/ExpandCollapseToggler.cpp
    Handlers/ProcessingHandlers/ProcessingHandler.h
    Handlers/ProcessingHandlers/ProcessingHandler.cpp
    Handlers/ProcessingHandlers/ExportJobProcessingHandler.h
    Handlers/ProcessingHandlers/ExportJobProcessingHandler.cpp
    Handlers/ProcessingHandlers/AsyncOperationProcessingHandler.h
    Handlers/ProcessingHandlers/AsyncOperationProcessingHandler.cpp
    SceneWidgets/ManifestWidget.h
    SceneWidgets/ManifestWidget.cpp
    SceneWidgets/ManifestWidget.ui
    SceneWidgets/ManifestWidgetPage.h
    SceneWidgets/ManifestWidgetPage.cpp
    SceneWidgets/ManifestWidgetPage.ui
    SceneWidgets/SceneGraphWidget.h
    SceneWidgets/SceneGraphWidget.cpp
    SceneWidgets/SceneGraphWidget.ui
    SceneWidgets/SceneGraphInspectWidget.h
    SceneWidgets/SceneGraphInspectWidget.cpp
    SceneWidgets/SceneGraphInspectWidget.ui
    RowWidgets/HeaderWidget.h
    RowWidgets/HeaderWidget.cpp
    RowWidgets/HeaderWidget.ui
    RowWidgets/HeaderHandler.h
    RowWidgets/HeaderHandler.cpp
    RowWidgets/ManifestVectorHandler.h
    RowWidgets/ManifestVectorHandler.cpp
    RowWidgets/ManifestVectorWidget.ui
    RowWidgets/ManifestVectorWidget.h
    RowWidgets/ManifestVectorWidget.cpp
    RowWidgets/NodeListSelectionHandler.h
    RowWidgets/NodeListSelectionHandler.cpp
    RowWidgets/NodeListSelectionWidget.h
    RowWidgets/NodeListSelectionWidget.cpp
    RowWidgets/NodeTreeSelectionHandler.h
    RowWidgets/NodeTreeSelectionHandler.cpp
    RowWidgets/NodeTreeSelectionWidget.h
    RowWidgets/NodeTreeSelectionWidget.cpp
    RowWidgets/NodeTreeSelectionWidget.ui
    RowWidgets/ManifestNameHandler.h
    RowWidgets/ManifestNameHandler.cpp
    RowWidgets/ManifestNameWidget.h
    RowWidgets/ManifestNameWidget.cpp
    RowWidgets/TransformRowHandler.h
    RowWidgets/TransformRowHandler.cpp
    RowWidgets/TransformRowWidget.h
    RowWidgets/TransformRowWidget.cpp
    DllMain.cpp
)
