#
# Copyright (c) Contributors to the Open 3D Engine Project. For complete copyright and license terms please see the LICENSE at the root of this distribution.
# 
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    NewsShared/LogType.h
    NewsShared/ErrorCodes.h
    NewsShared/Qt/ArticleErrorView.cpp
    NewsShared/Qt/ArticleErrorView.h
    NewsShared/Qt/ArticleErrorView.ui
    NewsShared/Qt/ArticleView.cpp
    NewsShared/Qt/ArticleView.h
    NewsShared/Qt/ArticleView.ui
    NewsShared/Qt/PinnedArticleView.ui
    NewsShared/Qt/ArticleViewContainer.cpp
    NewsShared/Qt/ArticleViewContainer.h
    NewsShared/Qt/ArticleViewContainer.ui
    NewsShared/Qt/KeepInTouchView.cpp
    NewsShared/Qt/KeepInTouchView.h
    NewsShared/Qt/KeepInTouchView.ui
    NewsShared/Qt/NewsShared.qrc
    NewsShared/ResourceManagement/ArticleDescriptor.cpp
    NewsShared/ResourceManagement/ArticleDescriptor.h
    NewsShared/ResourceManagement/Descriptor.cpp
    NewsShared/ResourceManagement/Descriptor.h
    NewsShared/ResourceManagement/JsonDescriptor.cpp
    NewsShared/ResourceManagement/JsonDescriptor.h
    NewsShared/ResourceManagement/QtDownloader.cpp
    NewsShared/ResourceManagement/QtDownloader.h
    NewsShared/ResourceManagement/QtDownloadManager.cpp
    NewsShared/ResourceManagement/QtDownloadManager.h
    NewsShared/ResourceManagement/Resource.cpp
    NewsShared/ResourceManagement/Resource.h
    NewsShared/ResourceManagement/ResourceManifest.cpp
    NewsShared/ResourceManagement/ResourceManifest.h
    NewsShared/Resources/ErrorImage.jpg
    NewsShared/Resources/KeepInTouchBanner.jpg
    NewsShared/Resources/icon_facebook.png
    NewsShared/Resources/icon_twitch.png
    NewsShared/Resources/icon_twitter.png
    NewsShared/Resources/icon_youtube.png
)
