@startuml Spawn Entity from Slice

title How GridMate spawns an entity from a dynamic slice

hide footbox

"NetBinding\nComponentChunk" -> NetBindingSystemImpl: SpawnEntityFromSlice
NetBindingSystemImpl -> "NetBindingSlice\nInstantiationHandler"
NetBindingSystemImpl -> NetBindingSystemImpl :  adds to m_bindRequests


[-> NetBindingSystemImpl: OnTick
NetBindingSystemImpl -> NetBindingSystemImpl: ProcessBindRequests
loop over all in m_bindRequests
    NetBindingSystemImpl -> "NetBindingSlice\nInstantiationHandler" : InstantiateEntities
    NetBindingSystemImpl -> NetBindingSystemImpl : BindAndActivate
    NetBindingSystemImpl -> NetBindingComponent : BindToNetwork
    NetBindingSystemImpl -> Entity : Activate
end

@enduml
