@startuml Marking Level Entities

[-> CLevelSystem: LoadLevel

loop over all Level Entities
    CLevelSystem -> NetBindingSystemImpl:OnEntityContextLoadedFromStream
    NetBindingSystemImpl -> NetBindingComponent:MarkAsLevelSliceEntity
    note left: if it has NetBindingComponent
    NetBindingSystemImpl -> GameEntityContextRequestBus:MarkEntityForNoActivation
    NetBindingSystemImpl -> NetBindingSystemImpl:add internal bind request
end

[-> NetBindingSystemImpl:OnTick
NetBindingSystemImpl -> NetBindingSystemImpl:ProcessBindRequests
loop over all bind requests
    NetBindingSystemImpl -> NetBindingSystemImpl:BindAndActivate
    NetBindingSystemImpl -> NetBindingComponent:BindToNetwork
    NetBindingSystemImpl -> Entity:Activate
end

@enduml
