@startuml GridMate Spawning Entity from Stream

entity OnTick
"NetBinding\nComponentChunk" -> NetBindingSystemImpl: SpawnEntityFromStream
NetBindingSystemImpl -> "NetBindingSlice\nInstantiationHandler"
NetBindingSystemImpl -> NetBindingSystemImpl :  adds to m_spawnRequests

OnTick -> NetBindingSystemImpl: ProcessBindRequests
note right: m_spawnRequests
NetBindingSystemImpl -> "NetBindingSlice\nInstantiationHandler" : InstantiateEntities
NetBindingSystemImpl -> NetBindingSystemImpl : BindAndActivate


@enduml
