@startuml New replica proxy created on client

CSystem -> Network: SyncWithGame
Network -> ReplicaManager: Unmarshal
ReplicaManager -> ReplicaManager: RegisterReplica
ReplicaManager -> Replica: OnActivate

Replica -> NetBindingComponentChunk: OnReplicaActive
NetBindingComponentChunk -> NetBindingSystemBus: SpawnEntityFromSlice
note left: if proxy,\nthen either spawns \nfrom a slice or stream
NetBindingComponentChunk -> NetBindingSystemBus: SpawnEntityFromStream

@enduml
