@startuml Interest Manager Update

title Interest Manager Update Logic

[-> InterestManager : Init
[-> ReplicaManager : SetAutoBroadcast to false

loop for each rule handler
    InterestManager -> BaseRulesHandler : Update
end

loop for each rule handler
    InterestManager -> BaseRulesHandler : GetLastResult
    InterestManager <- BaseRulesHandler : InterestMatchResult
    InterestManager -> InterestManager : process matches
    InterestManager -> ReplicaManager : OnReplicaChanged
    note right: if a replica list \nof peers have changed
    ReplicaManager -> ReplicaManager : Marshal
    note right: removes or adds replicas\nfrom peers as necessary
end

@enduml
