#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Include/GradientSignal/GradientSampler.h
    Include/GradientSignal/GradientTransform.h
    Include/GradientSignal/SmoothStep.h
    Include/GradientSignal/PerlinImprovedNoise.h
    Include/GradientSignal/Util.h
    Include/GradientSignal/Components/ConstantGradientComponent.h
    Include/GradientSignal/Components/DitherGradientComponent.h
    Include/GradientSignal/Components/GradientSurfaceDataComponent.h
    Include/GradientSignal/Components/GradientTransformComponent.h
    Include/GradientSignal/Components/ImageGradientComponent.h
    Include/GradientSignal/Components/ImageGradientModification.h
    Include/GradientSignal/Components/InvertGradientComponent.h
    Include/GradientSignal/Components/LevelsGradientComponent.h
    Include/GradientSignal/Components/MixedGradientComponent.h
    Include/GradientSignal/Components/PerlinGradientComponent.h
    Include/GradientSignal/Components/PosterizeGradientComponent.h
    Include/GradientSignal/Components/RandomGradientComponent.h
    Include/GradientSignal/Components/ReferenceGradientComponent.h
    Include/GradientSignal/Components/ShapeAreaFalloffGradientComponent.h
    Include/GradientSignal/Components/SmoothStepGradientComponent.h
    Include/GradientSignal/Components/SurfaceAltitudeGradientComponent.h
    Include/GradientSignal/Components/SurfaceMaskGradientComponent.h
    Include/GradientSignal/Components/SurfaceSlopeGradientComponent.h
    Include/GradientSignal/Components/ThresholdGradientComponent.h
    Include/GradientSignal/Ebuses/GradientTransformRequestBus.h
    Include/GradientSignal/Ebuses/GradientRequestBus.h
    Include/GradientSignal/Ebuses/GradientPreviewRequestBus.h
    Include/GradientSignal/Ebuses/GradientPreviewContextRequestBus.h
    Include/GradientSignal/Ebuses/SectorDataRequestBus.h
    Include/GradientSignal/Ebuses/RandomGradientRequestBus.h
    Include/GradientSignal/Ebuses/PerlinGradientRequestBus.h
    Include/GradientSignal/Ebuses/DitherGradientRequestBus.h
    Include/GradientSignal/Ebuses/GradientTransformModifierRequestBus.h
    Include/GradientSignal/Ebuses/InvertGradientRequestBus.h
    Include/GradientSignal/Ebuses/LevelsGradientRequestBus.h
    Include/GradientSignal/Ebuses/PosterizeGradientRequestBus.h
    Include/GradientSignal/Ebuses/SmoothStepGradientRequestBus.h
    Include/GradientSignal/Ebuses/ThresholdGradientRequestBus.h
    Include/GradientSignal/Ebuses/ConstantGradientRequestBus.h
    Include/GradientSignal/Ebuses/ImageGradientModificationBus.h
    Include/GradientSignal/Ebuses/ImageGradientRequestBus.h
    Include/GradientSignal/Ebuses/MixedGradientRequestBus.h
    Include/GradientSignal/Ebuses/ReferenceGradientRequestBus.h
    Include/GradientSignal/Ebuses/ShapeAreaFalloffGradientRequestBus.h
    Include/GradientSignal/Ebuses/SurfaceAltitudeGradientRequestBus.h
    Include/GradientSignal/Ebuses/SurfaceMaskGradientRequestBus.h
    Include/GradientSignal/Ebuses/SurfaceSlopeGradientRequestBus.h
    Include/GradientSignal/Ebuses/GradientSurfaceDataRequestBus.h
    Include/GradientSignal/Ebuses/SmoothStepRequestBus.h
    Source/Components/ConstantGradientComponent.cpp
    Source/Components/DitherGradientComponent.cpp
    Source/Components/GradientSurfaceDataComponent.cpp
    Source/Components/GradientTransformComponent.cpp
    Source/Components/ImageGradientComponent.cpp
    Source/Components/ImageGradientModification.cpp
    Source/Components/InvertGradientComponent.cpp
    Source/Components/LevelsGradientComponent.cpp
    Source/Components/MixedGradientComponent.cpp
    Source/Components/PerlinGradientComponent.cpp
    Source/Components/PosterizeGradientComponent.cpp
    Source/Components/RandomGradientComponent.cpp
    Source/Components/ReferenceGradientComponent.cpp
    Source/Components/ShapeAreaFalloffGradientComponent.cpp
    Source/Components/SmoothStepGradientComponent.cpp
    Source/Components/SurfaceAltitudeGradientComponent.cpp
    Source/Components/SurfaceMaskGradientComponent.cpp
    Source/Components/SurfaceSlopeGradientComponent.cpp
    Source/Components/ThresholdGradientComponent.cpp
    Source/GradientSampler.cpp
    Source/GradientSignalSystemComponent.cpp
    Source/GradientSignalSystemComponent.h
    Source/GradientTransform.cpp
    Source/SmoothStep.cpp
    Source/PerlinImprovedNoise.cpp
)
