#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Include/GradientSignal/Editor/EditorGradientBakerComponent.h
    Include/GradientSignal/Editor/EditorGradientBakerRequestBus.h
    Include/GradientSignal/Editor/EditorGradientComponentBase.h
    Include/GradientSignal/Editor/EditorGradientComponentBase.inl
    Include/GradientSignal/Editor/EditorGradientImageCreatorRequestBus.h
    Include/GradientSignal/Editor/EditorGradientImageCreatorUtils.h
    Include/GradientSignal/Editor/EditorGradientPreviewRenderer.h
    Include/GradientSignal/Editor/EditorGradientTypeIds.h
    Include/GradientSignal/Editor/GradientPreviewer.h
    Include/GradientSignal/Editor/PaintableImageAssetHelper.h
    Source/UI/GradientPreviewDataWidget.cpp
    Source/UI/GradientPreviewDataWidget.h
    Source/UI/GradientPreviewWidget.cpp
    Source/UI/GradientPreviewWidget.h
    Source/Editor/EditorConstantGradientComponent.cpp
    Source/Editor/EditorConstantGradientComponent.h
    Source/Editor/EditorDitherGradientComponent.cpp
    Source/Editor/EditorDitherGradientComponent.h
    Source/Editor/EditorGradientBakerComponent.cpp
    Source/Editor/EditorGradientImageCreatorUtils.cpp
    Source/Editor/EditorGradientSurfaceDataComponent.cpp
    Source/Editor/EditorGradientSurfaceDataComponent.h
    Source/Editor/EditorGradientTransformComponent.cpp
    Source/Editor/EditorGradientTransformComponent.h
    Source/Editor/EditorImageGradientComponent.cpp
    Source/Editor/EditorImageGradientComponent.h
    Source/Editor/EditorImageGradientComponentMode.cpp
    Source/Editor/EditorImageGradientComponentMode.h
    Source/Editor/EditorInvertGradientComponent.cpp
    Source/Editor/EditorInvertGradientComponent.h
    Source/Editor/EditorLevelsGradientComponent.cpp
    Source/Editor/EditorLevelsGradientComponent.h
    Source/Editor/EditorMixedGradientComponent.cpp
    Source/Editor/EditorMixedGradientComponent.h
    Source/Editor/EditorPerlinGradientComponent.cpp
    Source/Editor/EditorPerlinGradientComponent.h
    Source/Editor/EditorPosterizeGradientComponent.cpp
    Source/Editor/EditorPosterizeGradientComponent.h
    Source/Editor/EditorRandomGradientComponent.cpp
    Source/Editor/EditorRandomGradientComponent.h
    Source/Editor/EditorReferenceGradientComponent.cpp
    Source/Editor/EditorReferenceGradientComponent.h
    Source/Editor/EditorShapeAreaFalloffGradientComponent.cpp
    Source/Editor/EditorShapeAreaFalloffGradientComponent.h
    Source/Editor/EditorSmoothStepGradientComponent.cpp
    Source/Editor/EditorSmoothStepGradientComponent.h
    Source/Editor/EditorStreamingImageAssetCtrl.cpp
    Source/Editor/EditorStreamingImageAssetCtrl.h
    Source/Editor/EditorSurfaceAltitudeGradientComponent.cpp
    Source/Editor/EditorSurfaceAltitudeGradientComponent.h
    Source/Editor/EditorSurfaceMaskGradientComponent.cpp
    Source/Editor/EditorSurfaceMaskGradientComponent.h
    Source/Editor/EditorSurfaceSlopeGradientComponent.cpp
    Source/Editor/EditorSurfaceSlopeGradientComponent.h
    Source/Editor/EditorThresholdGradientComponent.cpp
    Source/Editor/EditorThresholdGradientComponent.h
    Source/Editor/GradientPreviewer.cpp
    Source/Editor/PaintableImageAssetHelper.cpp
)
