#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Include/Multiplayer/IMultiplayer.h
    Include/Multiplayer/IMultiplayerDebug.h
    Include/Multiplayer/IMultiplayerSpawner.h
    Include/Multiplayer/IMultiplayerTools.h
    Include/Multiplayer/MultiplayerConstants.h
    Include/Multiplayer/MultiplayerDebug.h
    Include/Multiplayer/MultiplayerDebug.inl
    Include/Multiplayer/MultiplayerMetrics.h
    Include/Multiplayer/MultiplayerStats.h
    Include/Multiplayer/MultiplayerTypes.h
    Include/Multiplayer/MultiplayerEditorServerBus.h
    Include/Multiplayer/Components/SimplePlayerSpawnerComponent.h
    Include/Multiplayer/Components/ISimplePlayerSpawner.h
    Include/Multiplayer/Components/MultiplayerComponent.h
    Include/Multiplayer/Components/MultiplayerComponentRegistry.h
    Include/Multiplayer/Components/MultiplayerController.h
    Include/Multiplayer/Components/NetBindComponent.h
    Include/Multiplayer/NetworkInput/NetworkInput.h
    Include/Multiplayer/NetworkInput/NetworkInputArray.h
    Include/Multiplayer/NetworkInput/NetworkInputChild.h
    Include/Multiplayer/NetworkInput/NetworkInputHistory.h
    Include/Multiplayer/NetworkInput/NetworkInputMigrationVector.h
    Include/Multiplayer/NetworkEntity/NetworkEntityHandle.h
    Include/Multiplayer/NetworkEntity/NetworkEntityHandle.inl
    Include/Multiplayer/NetworkEntity/NetworkEntityRpcMessage.h
    Include/Multiplayer/NetworkEntity/NetworkEntityUpdateMessage.h
    Include/Multiplayer/NetworkEntity/EntityReplication/EntityReplicationManager.h
    Include/Multiplayer/NetworkEntity/EntityReplication/EntityReplicator.h
    Include/Multiplayer/NetworkEntity/EntityReplication/EntityReplicator.inl
    Include/Multiplayer/ConnectionData/IConnectionData.h
    Include/Multiplayer/EntityDomains/IEntityDomain.h
    Include/Multiplayer/IMultiplayer.h
    Include/Multiplayer/IMultiplayerTools.h
    Include/Multiplayer/INetworkSpawnableLibrary.h
    Include/Multiplayer/MultiplayerConstants.h
    Include/Multiplayer/MultiplayerStats.h
    Include/Multiplayer/MultiplayerTypes.h
    Include/Multiplayer/NetworkEntity/IFilterEntityManager.h
    Include/Multiplayer/NetworkEntity/INetworkEntityManager.h
    Include/Multiplayer/NetworkEntity/EntityReplication/ReplicationRecord.h
    Include/Multiplayer/NetworkInput/IMultiplayerComponentInput.h
    Include/Multiplayer/NetworkTime/INetworkTime.h
    Include/Multiplayer/NetworkTime/RewindableArray.h
    Include/Multiplayer/NetworkTime/RewindableArray.inl
    Include/Multiplayer/NetworkTime/RewindableFixedVector.h
    Include/Multiplayer/NetworkTime/RewindableFixedVector.inl
    Include/Multiplayer/NetworkTime/RewindableObject.h
    Include/Multiplayer/NetworkTime/RewindableObject.inl
    Include/Multiplayer/ReplicationWindows/IReplicationWindow.h
    Include/Multiplayer/Session/IMatchmakingRequests.h
    Include/Multiplayer/Session/ISessionHandlingRequests.h
    Include/Multiplayer/Session/ISessionRequests.h
    Include/Multiplayer/Session/MatchmakingRequests.h
    Include/Multiplayer/Session/MatchmakingNotifications.h
    Include/Multiplayer/Session/SessionRequests.h
    Include/Multiplayer/Session/SessionConfig.h
    Include/Multiplayer/Session/SessionNotifications.h
    Source/Components/SimplePlayerSpawnerComponent.cpp
    Source/Components/MultiplayerComponent.cpp
    Source/Components/MultiplayerComponentRegistry.cpp
    Source/Components/MultiplayerController.cpp
    Source/Components/NetBindComponent.cpp
    Source/EntityDomains/FullOwnershipEntityDomain.cpp
    Source/EntityDomains/FullOwnershipEntityDomain.h
    Source/EntityDomains/NullEntityDomain.cpp
    Source/EntityDomains/NullEntityDomain.h
    Source/MultiplayerStatSystemComponent.cpp
    Source/MultiplayerStatSystemComponent.h
    Source/MultiplayerStats.cpp
    Source/NetworkEntity/NetworkEntityHandle.cpp
    Source/NetworkEntity/NetworkEntityRpcMessage.cpp
    Source/NetworkEntity/NetworkEntityTracker.cpp
    Source/NetworkEntity/NetworkEntityTracker.h
    Source/NetworkEntity/NetworkEntityTracker.inl
    Source/NetworkEntity/NetworkEntityUpdateMessage.cpp
    Source/NetworkEntity/EntityReplication/ReplicationRecord.cpp
    Source/NetworkInput/NetworkInput.cpp
    Source/NetworkInput/NetworkInputArray.cpp
    Source/NetworkInput/NetworkInputChild.cpp
    Source/NetworkInput/NetworkInputHistory.cpp
    Source/NetworkInput/NetworkInputMigrationVector.cpp
    Source/Session/MatchmakingRequests.cpp
    Source/Session/SessionRequests.cpp
    Source/Session/SessionConfig.cpp
    ${LY_ROOT_FOLDER}/Code/Framework/AzNetworking/AzNetworking/AutoGen/AutoPackets_Header.jinja
    ${LY_ROOT_FOLDER}/Code/Framework/AzNetworking/AzNetworking/AutoGen/AutoPackets_Inline.jinja
    ${LY_ROOT_FOLDER}/Code/Framework/AzNetworking/AzNetworking/AutoGen/AutoPackets_Source.jinja
    ${LY_ROOT_FOLDER}/Code/Framework/AzNetworking/AzNetworking/AutoGen/AutoPacketDispatcher_Header.jinja
    ${LY_ROOT_FOLDER}/Code/Framework/AzNetworking/AzNetworking/AutoGen/AutoPacketDispatcher_Inline.jinja
    Source/AutoGen/Multiplayer.AutoPackets.xml
    Source/AutoGen/MultiplayerEditor.AutoPackets.xml
)
