#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

cmake_policy(SET CMP0012 NEW) # new policy for the if that evaluates a boolean out of "if(NOT ${same_location})"

function(ly_copy source_file target_directory)
    get_filename_component(target_filename "${source_file}" NAME)
    cmake_path(COMPARE "${source_file}" EQUAL "${target_directory}/${target_filename}" same_location)
    if(NOT ${same_location})
        file(LOCK ${target_directory}/${target_filename}.lock GUARD FUNCTION TIMEOUT 300)
        if("${source_file}" IS_NEWER_THAN "${target_directory}/${target_filename}")
            message(STATUS "Copying \"${source_file}\" to \"${target_directory}\"...")
            file(COPY "${source_file}" DESTINATION "${target_directory}" FILE_PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE FOLLOW_SYMLINK_CHAIN)
            file(TOUCH_NOCREATE ${target_directory}/${target_filename})
        endif()
    endif()    
endfunction()

ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_ar.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_bg.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_ca.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_cs.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_da.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_de.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_en.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_es.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_fa.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_fi.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_fr.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_gd.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_gl.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_he.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_ar.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_bg.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_ca.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_cs.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_da.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_de.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_en.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_es.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_fr.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_gl.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_hu.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_it.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_ja.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_ko.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_pl.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_ru.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_sk.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_sl.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_tr.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_uk.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_zh_CN.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_zh_TW.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_hu.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_it.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_ja.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_ko.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_lt.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_lv.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_pl.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_pt.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_ru.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_sk.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_sl.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_sv.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_tr.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_uk.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_zh_CN.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_zh_TW.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Cored.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/iconengines/qsvgicond.dll" "C:/Users/lesaelr/o3de/bin/debug/iconengines")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qgifd.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qicnsd.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qicod.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qjpegd.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qsvgd.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qtgad.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qtiffd.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qwbmpd.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qwebpd.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/platforms/qminimald.dll" "C:/Users/lesaelr/o3de/bin/debug/platforms")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/platforms/qwindowsd.dll" "C:/Users/lesaelr/o3de/bin/debug/platforms")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Guid.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/styles/qwindowsvistastyled.dll" "C:/Users/lesaelr/o3de/bin/debug/styles")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Widgetsd.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Svgd.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Xmld.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/AtomFont.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/ImGui.imguilib.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/boost_filesystem-vc141-mt-x64-1_73.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/boost_thread-vc141-mt-x64-1_73.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/Half-2_5.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/heif.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/Iex-2_5.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/IlmImf-2_5.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/IlmThread-2_5.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/Imath-2_5.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/jpeg62.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/lzma.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/libpng16.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/tiff.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/zlib1.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/yaml-cpp.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/OpenColorIO.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/OpenImageIO.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/OpenImageIO.pyd" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/OpenImageIO_Util.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/iconvert.exe" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/idiff.exe" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/igrep.exe" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/iinfo.exe" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/maketx.exe" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/oiiotool.exe" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/AtomImGuiTools.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/bearer/qgenericbearerd.dll" "C:/Users/lesaelr/o3de/bin/debug/bearer")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Networkd.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/python/runtime/python-3.7.10-rev2-windows/python/python37_d.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/python/runtime/python-3.7.10-rev2-windows/python/python3_d.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/python/runtime/python-3.7.10-rev2-windows/python/python37_d.pdb" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/python/runtime/python-3.7.10-rev2-windows/python/python3_d.pdb" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/AzQtComponents.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/EditorCore.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/Atom_RHI_DX12.Builders.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/Atom_RHI_DX12.Private.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/Atom_RHI_Metal.Builders.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/Atom_RHI_Metal.Private.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/Atom_RHI_Vulkan.Builders.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/Atom_RHI_Vulkan.Private.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/Atom_Feature_Common.Editor.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/Atom_RHI.Private.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/Atom_RPI.Editor.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/EditorCommon.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/AtomLyIntegration_CommonFeatures.Editor.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/AtomToolsFramework.Editor.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/AtomViewportDisplayIcons.Editor.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/AtomViewportDisplayInfo.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/mcpp-2.7.2_az.1-rev1-windows/mcpp/lib/mcpp0.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/DirectXShaderCompilerDxc-1.6.2104-o3de-rev3-windows/DirectXShaderCompilerDxc/bin/Release/dxc.exe" "C:/Users/lesaelr/o3de/bin/debug/Builders/DirectXShaderCompiler")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/DirectXShaderCompilerDxc-1.6.2104-o3de-rev3-windows/DirectXShaderCompilerDxc/bin/Release/dxil.dll" "C:/Users/lesaelr/o3de/bin/debug/Builders/DirectXShaderCompiler")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/DirectXShaderCompilerDxc-1.6.2104-o3de-rev3-windows/DirectXShaderCompilerDxc/bin/Release/dxcompiler.dll" "C:/Users/lesaelr/o3de/bin/debug/Builders/DirectXShaderCompiler")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/SPIRVCross-2021.04.29-rev1-windows/SPIRVCross/bin/Release/spirv-cross.exe" "C:/Users/lesaelr/o3de/bin/debug/Builders/SPIRVCross")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/azslc-1.7.23-rev1-multiplatform/azslc/bin/win_x64/Release/azslc.exe" "C:/Users/lesaelr/o3de/bin/debug/Builders/AZSLc")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/azslc-1.7.23-rev1-multiplatform/azslc/bin/win_x64/Release/boost_regex-vc142-mt-x64-1_70.dll" "C:/Users/lesaelr/o3de/bin/debug/Builders/AZSLc")
ly_copy("C:/Users/lesaelr/o3de/Gems/Atom/Asset/Shader/Code/AZSL/Platform/Windows/DX12/AzslcHeader.azsli" "C:/Users/lesaelr/o3de/bin/debug/Builders/ShaderHeaders/Platform/Windows/DX12")
ly_copy("C:/Users/lesaelr/o3de/Gems/Atom/Asset/Shader/Code/AZSL/Platform/Windows/DX12/PlatformHeader.hlsli" "C:/Users/lesaelr/o3de/bin/debug/Builders/ShaderHeaders/Platform/Windows/DX12")
ly_copy("C:/Users/lesaelr/o3de/Gems/Atom/Asset/Shader/Code/AZSL/Platform/Windows/Vulkan/AzslcHeader.azsli" "C:/Users/lesaelr/o3de/bin/debug/Builders/ShaderHeaders/Platform/Windows/Vulkan")
ly_copy("C:/Users/lesaelr/o3de/Gems/Atom/Asset/Shader/Code/AZSL/Platform/Windows/Vulkan/PlatformHeader.hlsli" "C:/Users/lesaelr/o3de/bin/debug/Builders/ShaderHeaders/Platform/Windows/Vulkan")
ly_copy("C:/Users/lesaelr/o3de/Gems/Atom/Asset/Shader/Code/AZSL/Platform/Windows/Null/AzslcHeader.azsli" "C:/Users/lesaelr/o3de/bin/debug/Builders/ShaderHeaders/Platform/Windows/Null")
ly_copy("C:/Users/lesaelr/o3de/Gems/Atom/Asset/Shader/Code/AZSL/Platform/Mac/Metal/AzslcHeader.azsli" "C:/Users/lesaelr/o3de/bin/debug/Builders/ShaderHeaders/Platform/Mac/Metal")
ly_copy("C:/Users/lesaelr/o3de/Gems/Atom/Asset/Shader/Code/AZSL/Platform/Mac/Metal/PlatformHeader.hlsli" "C:/Users/lesaelr/o3de/bin/debug/Builders/ShaderHeaders/Platform/Mac/Metal")
ly_copy("C:/Users/lesaelr/o3de/Gems/Atom/Asset/Shader/Code/AZSL/Platform/Mac/Null/AzslcHeader.azsli" "C:/Users/lesaelr/o3de/bin/debug/Builders/ShaderHeaders/Platform/Mac/Null")
ly_copy("C:/Users/lesaelr/o3de/Gems/Atom/Asset/Shader/Code/AZSL/Platform/iOS/Metal/AzslcHeader.azsli" "C:/Users/lesaelr/o3de/bin/debug/Builders/ShaderHeaders/Platform/iOS/Metal")
ly_copy("C:/Users/lesaelr/o3de/Gems/Atom/Asset/Shader/Code/AZSL/Platform/iOS/Metal/PlatformHeader.hlsli" "C:/Users/lesaelr/o3de/bin/debug/Builders/ShaderHeaders/Platform/iOS/Metal")
ly_copy("C:/Users/lesaelr/o3de/Gems/Atom/Asset/Shader/Code/AZSL/Platform/Android/Vulkan/AzslcHeader.azsli" "C:/Users/lesaelr/o3de/bin/debug/Builders/ShaderHeaders/Platform/Android/Vulkan")
ly_copy("C:/Users/lesaelr/o3de/Gems/Atom/Asset/Shader/Code/AZSL/Platform/Android/Vulkan/PlatformHeader.hlsli" "C:/Users/lesaelr/o3de/bin/debug/Builders/ShaderHeaders/Platform/Android/Vulkan")
ly_copy("C:/Users/lesaelr/o3de/Gems/Atom/Asset/Shader/Code/AZSL/Platform/Linux/Vulkan/AzslcHeader.azsli" "C:/Users/lesaelr/o3de/bin/debug/Builders/ShaderHeaders/Platform/Linux/Vulkan")
ly_copy("C:/Users/lesaelr/o3de/Gems/Atom/Asset/Shader/Code/AZSL/Platform/Linux/Vulkan/PlatformHeader.hlsli" "C:/Users/lesaelr/o3de/bin/debug/Builders/ShaderHeaders/Platform/Linux/Vulkan")
ly_copy("C:/Users/lesaelr/o3de/Gems/Atom/Asset/Shader/Code/AZSL/Platform/Linux/Null/AzslcHeader.azsli" "C:/Users/lesaelr/o3de/bin/debug/Builders/ShaderHeaders/Platform/Linux/Null")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/Atom_Asset_Shader.Builders.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/Atom_Bootstrap.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/Atom_Component_DebugCamera.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/Atom_Feature_Common.Builders.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/Atom_RHI_Null.Builders.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/Atom_RHI_Null.Private.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/Atom_RPI.Builders.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5OpenGLd.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/lrelease.exe" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Core.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/LmbrCentral.Editor.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/EMotionFX.Editor.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/EMotionFX_Atom.Editor.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/PVRTexTool-4.24.0-rev4-multiplatform/PVRTexTool/Windows_x86_64/PVRTexLib.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/squish-ccr-deb557d-rev1-windows/squish-ccr/bin/squish-ccr.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/ISPCTexComp-36b80aa-rev1-windows/ISPCTexComp/bin/ispc_texcomp.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/ImageProcessingAtom.Editor.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/ImguiAtom.dll" "C:/Users/lesaelr/o3de/bin/debug")


file(TOUCH C:/Users/lesaelr/o3de/runtime_dependencies/debug/Atom_AtomBridge.Editor_debug.stamp)
