#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

cmake_policy(SET CMP0012 NEW) # new policy for the if that evaluates a boolean out of "if(NOT ${same_location})"

function(ly_copy source_file target_directory)
    get_filename_component(target_filename "${source_file}" NAME)
    cmake_path(COMPARE "${source_file}" EQUAL "${target_directory}/${target_filename}" same_location)
    if(NOT ${same_location})
        file(LOCK ${target_directory}/${target_filename}.lock GUARD FUNCTION TIMEOUT 300)
        if("${source_file}" IS_NEWER_THAN "${target_directory}/${target_filename}")
            message(STATUS "Copying \"${source_file}\" to \"${target_directory}\"...")
            file(COPY "${source_file}" DESTINATION "${target_directory}" FILE_PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE FOLLOW_SYMLINK_CHAIN)
            file(TOUCH_NOCREATE ${target_directory}/${target_filename})
        endif()
    endif()    
endfunction()

ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_ar.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_bg.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_ca.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_cs.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_da.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_de.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_en.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_es.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_fa.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_fi.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_fr.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_gd.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_gl.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_he.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_ar.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_bg.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_ca.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_cs.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_da.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_de.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_en.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_es.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_fr.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_gl.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_hu.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_it.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_ja.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_ko.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_pl.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_ru.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_sk.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_sl.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_tr.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_uk.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_zh_CN.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_zh_TW.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_hu.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_it.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_ja.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_ko.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_lt.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_lv.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_pl.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_pt.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_ru.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_sk.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_sl.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_sv.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_tr.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_uk.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_zh_CN.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_zh_TW.qm" "C:/Users/lesaelr/o3de/bin/debug/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Cored.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/iconengines/qsvgicond.dll" "C:/Users/lesaelr/o3de/bin/debug/iconengines")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qgifd.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qicnsd.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qicod.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qjpegd.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qsvgd.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qtgad.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qtiffd.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qwbmpd.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qwebpd.dll" "C:/Users/lesaelr/o3de/bin/debug/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/platforms/qminimald.dll" "C:/Users/lesaelr/o3de/bin/debug/platforms")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/platforms/qwindowsd.dll" "C:/Users/lesaelr/o3de/bin/debug/platforms")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Guid.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/styles/qwindowsvistastyled.dll" "C:/Users/lesaelr/o3de/bin/debug/styles")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Widgetsd.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Svgd.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Xmld.dll" "C:/Users/lesaelr/o3de/bin/debug")
ly_copy("C:/Users/lesaelr/o3de/bin/debug/AzTestRunner.exe" "C:/Users/lesaelr/o3de/bin/debug")


file(TOUCH C:/Users/lesaelr/o3de/runtime_dependencies/debug/GraphModel.Editor.Tests_debug.stamp)
