#
# Copyright (c) Contributors to the Open 3D Engine Project. For complete copyright and license terms please see the LICENSE at the root of this distribution.
# 
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Gallery/AssetBrowserFolderPage.ui
    Gallery/AssetBrowserFolderPage.cpp
    Gallery/AssetBrowserFolderPage.h
    Gallery/AssetBrowserFolderPage.qrc
    Gallery/BreadCrumbsPage.ui
    Gallery/BreadCrumbsPage.cpp
    Gallery/BreadCrumbsPage.h
    Gallery/BrowseEditPage.ui
    Gallery/BrowseEditPage.cpp
    Gallery/BrowseEditPage.h
    Gallery/ButtonPage.ui
    Gallery/ButtonPage.cpp
    Gallery/ButtonPage.h
    Gallery/CardPage.ui
    Gallery/CardPage.cpp
    Gallery/CardPage.h
    Gallery/CheckBoxPage.ui
    Gallery/CheckBoxPage.cpp
    Gallery/CheckBoxPage.h
    Gallery/ColorLabelPage.ui
    Gallery/ColorLabelPage.cpp
    Gallery/ColorLabelPage.h
    Gallery/ColorPickerPage.ui
    Gallery/ColorPickerPage.cpp
    Gallery/ColorPickerPage.h
    Gallery/ComboBoxPage.ui
    Gallery/ComboBoxPage.cpp
    Gallery/ComboBoxPage.h
    Gallery/ComponentDemoWidget.ui
    Gallery/ComponentDemoWidget.cpp
    Gallery/ComponentDemoWidget.h
    Gallery/DragAndDropPage.ui
    Gallery/DragAndDropPage.cpp
    Gallery/DragAndDropPage.h
    Gallery/ExampleWidget.qss
    Gallery/FilteredSearchWidgetPage.ui
    Gallery/FilteredSearchWidgetPage.cpp
    Gallery/FilteredSearchWidgetPage.h
    Gallery/FixedStateButton.h
    Gallery/FixedStateButton.cpp
    Gallery/GradientSliderPage.ui
    Gallery/GradientSliderPage.cpp
    Gallery/GradientSliderPage.h
    Gallery/HyperlinkPage.ui
    Gallery/HyperlinkPage.cpp
    Gallery/HyperlinkPage.h
    Gallery/LineEditPage.ui
    Gallery/LineEditPage.cpp
    Gallery/LineEditPage.h
    Gallery/main.cpp
    Gallery/MenuPage.ui
    Gallery/MenuPage.cpp
    Gallery/MenuPage.h
    Gallery/ProgressIndicatorPage.ui
    Gallery/ProgressIndicatorPage.cpp
    Gallery/ProgressIndicatorPage.h
    Gallery/RadioButtonPage.ui
    Gallery/RadioButtonPage.cpp
    Gallery/RadioButtonPage.h
    Gallery/ReflectedPropertyEditorPage.ui
    Gallery/ReflectedPropertyEditorPage.cpp
    Gallery/ReflectedPropertyEditorPage.h
    Gallery/resources.qrc
    Gallery/ScrollBarPage.ui
    Gallery/ScrollBarPage.cpp
    Gallery/ScrollBarPage.h
    Gallery/SegmentControlPage.ui
    Gallery/SegmentControlPage.cpp
    Gallery/SegmentControlPage.h
    Gallery/SliderPage.ui
    Gallery/SliderPage.cpp
    Gallery/SliderPage.h
    Gallery/SliderComboPage.ui
    Gallery/SliderComboPage.cpp
    Gallery/SliderComboPage.h
    Gallery/SpinBoxPage.ui
    Gallery/SpinBoxPage.cpp
    Gallery/SpinBoxPage.h
    Gallery/SplitterPage.ui
    Gallery/SplitterPage.cpp
    Gallery/SplitterPage.h
    Gallery/StyledDockWidgetPage.ui
    Gallery/StyledDockWidgetPage.cpp
    Gallery/StyledDockWidgetPage.h
    Gallery/StyleSheetLabel.qss
    Gallery/StyleSheetPage.ui
    Gallery/StyleSheetPage.cpp
    Gallery/StyleSheetPage.h
    Gallery/StyleSheetPage.qss
    Gallery/StyleSheetView.qss
    Gallery/SvgLabelPage.ui
    Gallery/SvgLabelPage.cpp
    Gallery/SvgLabelPage.h
    Gallery/TableViewPage.ui
    Gallery/TableViewPage.cpp
    Gallery/TableViewPage.h
    Gallery/TabWidgetPage.ui
    Gallery/TabWidgetPage.cpp
    Gallery/TabWidgetPage.h
    Gallery/TitleBarPage.ui
    Gallery/TitleBarPage.cpp
    Gallery/TitleBarPage.h
    Gallery/ToggleSwitchPage.ui
    Gallery/ToggleSwitchPage.cpp
    Gallery/ToggleSwitchPage.h
    Gallery/ToolBarPage.ui
    Gallery/ToolBarPage.cpp
    Gallery/ToolBarPage.h
    Gallery/TypographyPage.ui
    Gallery/TypographyPage.cpp
    Gallery/TypographyPage.h
    Gallery/TreeViewPage.ui
    Gallery/TreeViewPage.cpp
    Gallery/TreeViewPage.h
    Gallery/Gallery.rc
)
