#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Source/Allocators.h
    Source/Commands.cpp
    Source/Commands.h
    Source/DockWidgetPlugin.cpp
    Source/DockWidgetPlugin.h
    Source/EMStudioConfig.h
    Source/EMStudioManager.cpp
    Source/EMStudioManager.h
    Source/EMStudioPlugin.h
    Source/FileManager.cpp
    Source/FileManager.h
    Source/GUIOptions.cpp
    Source/GUIOptions.h
    Source/KeyboardShortcutsWindow.cpp
    Source/KeyboardShortcutsWindow.h
    Source/LayoutManager.cpp
    Source/LayoutManager.h
    Source/MainWindowEventFilter.h
    Source/MainWindow.cpp
    Source/MainWindow.h
    Source/MotionEventPresetManager.cpp
    Source/MotionEventPresetManager.h
    Source/PersistentPlugin.h
    Source/PluginManager.cpp
    Source/PluginManager.h
    Source/PluginOptions.h
    Source/PluginOptionsBus.h
    Source/PreferencesWindow.cpp
    Source/PreferencesWindow.h
    Source/RecoverFilesWindow.cpp
    Source/RecoverFilesWindow.h
    Source/RemovePluginOnCloseDockWidget.cpp
    Source/RemovePluginOnCloseDockWidget.h
    Source/ResetSettingsDialog.cpp
    Source/ResetSettingsDialog.h
    Source/SaveChangedFilesManager.cpp
    Source/SaveChangedFilesManager.h
    Source/ToolBarPlugin.cpp
    Source/ToolBarPlugin.h
    Source/Workspace.cpp
    Source/Workspace.h
    Source/NotificationWindow.cpp
    Source/NotificationWindow.h
    Source/NotificationWindowManager.cpp
    Source/NotificationWindowManager.h
    Source/LoadActorSettingsWindow.cpp
    Source/LoadActorSettingsWindow.h
    Source/MotionSetHierarchyWidget.cpp
    Source/MotionSetHierarchyWidget.h
    Source/MorphTargetSelectionWindow.cpp
    Source/MorphTargetSelectionWindow.h
    Source/NodeHierarchyWidget.cpp
    Source/NodeHierarchyWidget.h
    Source/NodeSelectionWindow.cpp
    Source/NodeSelectionWindow.h
    Source/MotionSetSelectionWindow.cpp
    Source/MotionSetSelectionWindow.h
    Source/RenderPlugin/RenderOptions.cpp
    Source/RenderPlugin/RenderOptions.h
)
