#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Include/Atom/RHI/Allocator.h
    Include/Atom/RHI/FreeListAllocator.h
    Include/Atom/RHI/LinearAllocator.h
    Include/Atom/RHI/PoolAllocator.h
    Source/RHI/Allocator.cpp
    Source/RHI/FreeListAllocator.cpp
    Source/RHI/LinearAllocator.cpp
    Source/RHI/PoolAllocator.cpp
    Include/Atom/RHI/SingleDeviceBuffer.h
    Include/Atom/RHI/MultiDeviceBuffer.h
    Include/Atom/RHI/SingleDeviceBufferView.h
    Include/Atom/RHI/SingleDeviceIndexBufferView.h
    Include/Atom/RHI/MultiDeviceIndexBufferView.h
    Include/Atom/RHI/SingleDeviceStreamBufferView.h
    Include/Atom/RHI/MultiDeviceStreamBufferView.h
    Source/RHI/SingleDeviceBuffer.cpp
    Source/RHI/MultiDeviceBuffer.cpp
    Source/RHI/SingleDeviceBufferView.cpp
    Source/RHI/SingleDeviceIndexBufferView.cpp
    Source/RHI/MultiDeviceIndexBufferView.cpp
    Source/RHI/SingleDeviceStreamBufferView.cpp
    Source/RHI/MultiDeviceStreamBufferView.cpp
    Include/Atom/RHI/SingleDeviceBufferPool.h
    Include/Atom/RHI/MultiDeviceBufferPool.h
    Include/Atom/RHI/SingleDeviceBufferPoolBase.h
    Include/Atom/RHI/MultiDeviceBufferPoolBase.h
    Source/RHI/SingleDeviceBufferPool.cpp
    Source/RHI/MultiDeviceBufferPool.cpp
    Source/RHI/SingleDeviceBufferPoolBase.cpp
    Source/RHI/MultiDeviceBufferPoolBase.cpp
    Include/Atom/RHI/CommandList.h
    Include/Atom/RHI/CommandListValidator.h
    Include/Atom/RHI/CommandListStates.h
    Include/Atom/RHI/SingleDeviceCopyItem.h
    Include/Atom/RHI/MultiDeviceCopyItem.h
    Include/Atom/RHI/ConstantsData.h
    Include/Atom/RHI/SingleDeviceDispatchItem.h
    Include/Atom/RHI/MultiDeviceDispatchItem.h
    Include/Atom/RHI/DrawFilterTagRegistry.h
    Include/Atom/RHI/SingleDeviceDrawItem.h
    Include/Atom/RHI/MultiDeviceDrawItem.h
    Include/Atom/RHI/DrawList.h
    Include/Atom/RHI/DrawListTagRegistry.h
    Include/Atom/RHI/DrawListContext.h
    Include/Atom/RHI/SingleDeviceDrawPacket.h
    Include/Atom/RHI/MultiDeviceDrawPacket.h
    Include/Atom/RHI/SingleDeviceDrawPacketBuilder.h
    Include/Atom/RHI/MultiDeviceDrawPacketBuilder.h
    Include/Atom/RHI/SingleDeviceIndirectArguments.h
    Include/Atom/RHI/MultiDeviceIndirectArguments.h
    Source/RHI/CommandList.cpp
    Source/RHI/CommandListValidator.cpp
    Source/RHI/ConstantsData.cpp
    Source/RHI/DrawList.cpp
    Source/RHI/DrawListContext.cpp
    Source/RHI/SingleDeviceDrawPacket.cpp
    Source/RHI/MultiDeviceDrawPacket.cpp
    Source/RHI/SingleDeviceDrawPacketBuilder.cpp
    Source/RHI/MultiDeviceDrawPacketBuilder.cpp
    Source/RHI/MultiDeviceDrawItem.cpp
    Include/Atom/RHI/Device.h
    Include/Atom/RHI/DeviceBusTraits.h
    Include/Atom/RHI/DeviceObject.h
    Include/Atom/RHI/MultiDeviceObject.h
    Include/Atom/RHI/CommandQueue.h
    Include/Atom/RHI/ValidationLayer.h
    Source/RHI/Device.cpp
    Source/RHI/DeviceObject.cpp
    Source/RHI/MultiDeviceObject.cpp
    Source/RHI/CommandQueue.cpp
    Source/RHI/ValidationLayer.cpp
    Include/Atom/RHI/Factory.h
    Source/RHI/Factory.cpp
    Include/Atom/RHI/FactoryManagerBus.h
    Include/Atom/RHI/SingleDeviceFence.h
    Include/Atom/RHI/MultiDeviceFence.h
    Source/RHI/SingleDeviceFence.cpp
    Source/RHI/MultiDeviceFence.cpp
    Include/Atom/RHI/BufferFrameAttachment.h
    Include/Atom/RHI/FrameAttachment.h
    Include/Atom/RHI/ImageFrameAttachment.h
    Include/Atom/RHI/SwapChainFrameAttachment.h
    Source/RHI/BufferFrameAttachment.cpp
    Source/RHI/FrameAttachment.cpp
    Source/RHI/ImageFrameAttachment.cpp
    Source/RHI/SwapChainFrameAttachment.cpp
    Include/Atom/RHI/FrameGraph.h
    Include/Atom/RHI/FrameGraphAttachmentInterface.h
    Include/Atom/RHI/FrameGraphAttachmentDatabase.h
    Include/Atom/RHI/FrameGraphBuilder.h
    Include/Atom/RHI/FrameGraphCompileContext.h
    Include/Atom/RHI/FrameGraphCompiler.h
    Include/Atom/RHI/FrameGraphExecuteContext.h
    Include/Atom/RHI/FrameGraphExecuteGroup.h
    Include/Atom/RHI/FrameGraphExecuter.h
    Include/Atom/RHI/FrameGraphLogger.h
    Include/Atom/RHI/FrameGraphInterface.h
    Source/RHI/FrameGraph.cpp
    Source/RHI/FrameGraphAttachmentDatabase.cpp
    Source/RHI/FrameGraphCompileContext.cpp
    Source/RHI/FrameGraphCompiler.cpp
    Source/RHI/FrameGraphExecuteContext.cpp
    Source/RHI/FrameGraphExecuteGroup.cpp
    Source/RHI/FrameGraphExecuter.cpp
    Source/RHI/FrameGraphLogger.cpp
    Include/Atom/RHI/FrameEventBus.h
    Include/Atom/RHI/FrameScheduler.h
    Source/RHI/FrameScheduler.cpp
    Include/Atom/RHI/SingleDeviceImage.h
    Include/Atom/RHI/MultiDeviceImage.h
    Include/Atom/RHI/SingleDeviceImageView.h
    Source/RHI/SingleDeviceImage.cpp
    Source/RHI/MultiDeviceImage.cpp
    Source/RHI/SingleDeviceImageView.cpp
    Include/Atom/RHI/SingleDeviceImagePool.h
    Include/Atom/RHI/MultiDeviceImagePool.h
    Include/Atom/RHI/SingleDeviceImagePoolBase.h
    Include/Atom/RHI/MultiDeviceImagePoolBase.h
    Include/Atom/RHI/SingleDeviceStreamingImagePool.h
    Include/Atom/RHI/MultiDeviceStreamingImagePool.h
    Source/RHI/SingleDeviceImagePool.cpp
    Source/RHI/MultiDeviceImagePool.cpp
    Source/RHI/SingleDeviceImagePoolBase.cpp
    Source/RHI/MultiDeviceImagePoolBase.cpp
    Source/RHI/SingleDeviceStreamingImagePool.cpp
    Source/RHI/MultiDeviceStreamingImagePool.cpp
    Include/Atom/RHI/SingleDeviceIndirectBufferSignature.h
    Include/Atom/RHI/MultiDeviceIndirectBufferSignature.h
    Include/Atom/RHI/SingleDeviceIndirectBufferView.h
    Include/Atom/RHI/MultiDeviceIndirectBufferView.h
    Include/Atom/RHI/SingleDeviceIndirectBufferWriter.h
    Include/Atom/RHI/MultiDeviceIndirectBufferWriter.h
    Source/RHI/SingleDeviceIndirectBufferSignature.cpp
    Source/RHI/MultiDeviceIndirectBufferSignature.cpp
    Source/RHI/SingleDeviceIndirectBufferView.cpp
    Source/RHI/MultiDeviceIndirectBufferView.cpp
    Source/RHI/SingleDeviceIndirectBufferWriter.cpp
    Source/RHI/MultiDeviceIndirectBufferWriter.cpp
    Include/Atom/RHI/Object.h
    Include/Atom/RHI/ObjectCache.h
    Include/Atom/RHI/ObjectCollector.h
    Include/Atom/RHI/ObjectPool.h
    Source/RHI/Object.cpp
    Include/Atom/RHI/PageTileAllocator.h
    Include/Atom/RHI/PageTiles.h
    Source/RHI/PageTileAllocator.cpp
    Include/Atom/RHI/PhysicalDevice.h
    Source/RHI/PhysicalDevice.cpp
    Include/Atom/RHI/SingleDevicePipelineLibrary.h
    Include/Atom/RHI/MultiDevicePipelineLibrary.h
    Include/Atom/RHI/SingleDevicePipelineState.h
    Include/Atom/RHI/MultiDevicePipelineState.h
    Include/Atom/RHI/PipelineStateCache.h
    Include/Atom/RHI/PipelineStateDescriptor.h
    Source/RHI/SingleDevicePipelineLibrary.cpp
    Source/RHI/MultiDevicePipelineLibrary.cpp
    Source/RHI/SingleDevicePipelineState.cpp
    Source/RHI/MultiDevicePipelineState.cpp
    Source/RHI/PipelineStateCache.cpp
    Source/RHI/PipelineStateDescriptor.cpp
    Include/Atom/RHI/SingleDeviceQuery.h
    Include/Atom/RHI/MultiDeviceQuery.h
    Source/RHI/SingleDeviceQuery.cpp
    Source/RHI/MultiDeviceQuery.cpp
    Include/Atom/RHI/SingleDeviceQueryPool.h
    Include/Atom/RHI/MultiDeviceQueryPool.h
    Include/Atom/RHI/QueryPoolSubAllocator.h
    Source/RHI/SingleDeviceQueryPool.cpp
    Source/RHI/MultiDeviceQueryPool.cpp
    Source/RHI/QueryPoolSubAllocator.cpp
    Include/Atom/RHI/SingleDeviceResource.h
    Include/Atom/RHI/MultiDeviceResource.h
    Include/Atom/RHI/ResourceInvalidateBus.h
    Include/Atom/RHI/SingleDeviceResourceView.h
    Source/RHI/SingleDeviceResource.cpp
    Source/RHI/MultiDeviceResource.cpp
    Source/RHI/SingleDeviceResourceView.cpp
    Include/Atom/RHI/SingleDeviceResourcePool.h
    Include/Atom/RHI/MultiDeviceResourcePool.h
    Include/Atom/RHI/ResourcePoolDatabase.h
    Source/RHI/SingleDeviceResourcePool.cpp
    Source/RHI/MultiDeviceResourcePool.cpp
    Source/RHI/ResourcePoolDatabase.cpp
    Include/Atom/RHI/MemoryAllocation.h
    Include/Atom/RHI/MemorySubAllocator.h
    Include/Atom/RHI/MemoryLinearSubAllocator.h
    Include/Atom/RHI/Scope.h
    Include/Atom/RHI/ScopeProducer.h
    Include/Atom/RHI/ScopeProducerEmpty.h
    Include/Atom/RHI/ScopeProducerFunction.h
    Source/RHI/Scope.cpp
    Source/RHI/ScopeProducer.cpp
    Include/Atom/RHI/BufferScopeAttachment.h
    Include/Atom/RHI/ImageScopeAttachment.h
    Include/Atom/RHI/ResolveScopeAttachment.h
    Include/Atom/RHI/ScopeAttachment.h
    Source/RHI/BufferScopeAttachment.cpp
    Source/RHI/ImageScopeAttachment.cpp
    Source/RHI/ResolveScopeAttachment.cpp
    Source/RHI/ScopeAttachment.cpp
    Include/Atom/RHI/SingleDeviceShaderResourceGroup.h
    Include/Atom/RHI/MultiDeviceShaderResourceGroup.h
    Include/Atom/RHI/SingleDeviceShaderResourceGroupData.h
    Include/Atom/RHI/MultiDeviceShaderResourceGroupData.h
    Include/Atom/RHI/ShaderResourceGroupDebug.h
    Include/Atom/RHI/ShaderResourceGroupInvalidateRegistry.h
    Include/Atom/RHI/SingleDeviceShaderResourceGroupPool.h
    Include/Atom/RHI/MultiDeviceShaderResourceGroupPool.h
    Source/RHI/SingleDeviceShaderResourceGroup.cpp
    Source/RHI/MultiDeviceShaderResourceGroup.cpp
    Source/RHI/SingleDeviceShaderResourceGroupData.cpp
    Source/RHI/MultiDeviceShaderResourceGroupData.cpp
    Source/RHI/ShaderResourceGroupDebug.cpp
    Source/RHI/ShaderResourceGroupInvalidateRegistry.cpp
    Source/RHI/SingleDeviceShaderResourceGroupPool.cpp
    Source/RHI/MultiDeviceShaderResourceGroupPool.cpp
    Include/Atom/RHI/MemoryStatisticsBuilder.h
    Include/Atom/RHI/MemoryStatisticsBus.h
    Source/RHI/MemoryStatisticsBuilder.cpp
    Include/Atom/RHI/SingleDeviceSwapChain.h
    Include/Atom/RHI/MultiDeviceSwapChain.h
    Source/RHI/SingleDeviceSwapChain.cpp
    Source/RHI/MultiDeviceSwapChain.cpp
    Include/Atom/RHI/RHISystem.h
    Include/Atom/RHI/RHISystemInterface.h
    Source/RHI/RHISystem.cpp
    Include/Atom/RHI/ThreadLocalContext.h
    Include/Atom/RHI/AsyncWorkQueue.h
    Source/RHI/AsyncWorkQueue.cpp
    Include/Atom/RHI/AliasedHeap.h
    Source/RHI/AliasedHeap.cpp
    Include/Atom/RHI/AliasedAttachmentAllocator.h
    Include/Atom/RHI/AliasingBarrierTracker.h
    Source/RHI/AliasingBarrierTracker.cpp
    Include/Atom/RHI/TileAllocator.h
    Include/Atom/RHI/TileAllocator.inl
    Include/Atom/RHI/SingleDeviceTransientAttachmentPool.h
    Include/Atom/RHI/MultiDeviceTransientAttachmentPool.h
    Source/RHI/SingleDeviceTransientAttachmentPool.cpp
    Source/RHI/MultiDeviceTransientAttachmentPool.cpp
    Include/Atom/RHI/RHIUtils.h
    Source/RHI/RHIUtils.cpp
    Include/Atom/RHI/SingleDeviceRayTracingAccelerationStructure.h
    Include/Atom/RHI/MultiDeviceRayTracingAccelerationStructure.h
    Include/Atom/RHI/SingleDeviceRayTracingPipelineState.h
    Include/Atom/RHI/MultiDeviceRayTracingPipelineState.h
    Include/Atom/RHI/SingleDeviceRayTracingShaderTable.h
    Include/Atom/RHI/MultiDeviceRayTracingShaderTable.h
    Include/Atom/RHI/SingleDeviceRayTracingBufferPools.h
    Include/Atom/RHI/MultiDeviceRayTracingBufferPools.h
    Include/Atom/RHI/SingleDeviceDispatchRaysItem.h
    Include/Atom/RHI/MultiDeviceDispatchRaysItem.h
    Source/RHI/SingleDeviceRayTracingAccelerationStructure.cpp
    Source/RHI/MultiDeviceRayTracingAccelerationStructure.cpp
    Source/RHI/SingleDeviceRayTracingPipelineState.cpp
    Source/RHI/MultiDeviceRayTracingPipelineState.cpp
    Source/RHI/SingleDeviceRayTracingShaderTable.cpp
    Source/RHI/MultiDeviceRayTracingShaderTable.cpp
    Source/RHI/SingleDeviceRayTracingBufferPools.cpp
    Source/RHI/MultiDeviceRayTracingBufferPools.cpp
    Include/Atom/RHI/interval_map.h
    Include/Atom/RHI/ImageProperty.h
    Include/Atom/RHI/BufferProperty.h
    Include/Atom/RHI/TagBitRegistry.h
    Include/Atom/RHI/TagRegistry.h
    Include/Atom/RHI/XRRenderingInterface.h
    Include/Atom/RHI/DispatchRaysIndirectBuffer.h
    Include/Atom/RHI/MultiDeviceDispatchRaysIndirectBuffer.h
)
