#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(ENABLED_GEMS
    ImGui
    ScriptEvents
    ExpressionEvaluation
    Gestures
    CertificateManager
    DebugDraw
    SceneProcessing
    GraphCanvas
    InAppPurchases
    AutomatedTesting
    EditorPythonBindings
    QtForPython
    PythonAssetBuilder
    Metastream
    Camera
    EMotionFX
    AtomTressFX
    PhysX
    CameraFramework
    StartingPointMovement
    StartingPointCamera
    ScriptCanvas
    ScriptCanvasPhysics
    ScriptCanvasTesting
    LyShineExamples
    StartingPointInput
    PhysXDebug
    WhiteBox
    FastNoise
    SurfaceData
    GradientSignal
    Vegetation
    GraphModel
    LandscapeCanvas
    NvCloth
    Blast
    Maestro
    TextureAtlas
    LmbrCentral
    LyShine
    HttpRequestor
    Atom
    AWSCore
    AWSClientAuth
    AWSMetrics
    PrefabBuilder
    AudioSystem
    Profiler
    Multiplayer
)
