#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Editor/Animation/AnimationContext.cpp
    Editor/Animation/AnimationContext.h
    Editor/Animation/Controls/UiSplineCtrlEx.cpp
    Editor/Animation/Controls/UiSplineCtrlEx.h
    Editor/Animation/Controls/UiTimelineCtrl.cpp
    Editor/Animation/Controls/UiTimelineCtrl.h
    Editor/Animation/UiAnimUndo.cpp
    Editor/Animation/UiAnimUndo.h
    Editor/Animation/UiAnimUndoManager.cpp
    Editor/Animation/UiAnimUndoManager.h
    Editor/Animation/UiAnimUndoObject.h
    Editor/Animation/UiAnimViewAnimNode.cpp
    Editor/Animation/UiAnimViewAnimNode.h
    Editor/Animation/UiAnimViewCurveEditor.cpp
    Editor/Animation/UiAnimViewCurveEditor.h
    Editor/Animation/UiAnimViewCurveEditor.ui
    Editor/Animation/UiAnimViewDialog.cpp
    Editor/Animation/UiAnimViewDialog.h
    Editor/Animation/UiAnimViewDialog.qrc
    Editor/Animation/UiAnimViewDopeSheetBase.cpp
    Editor/Animation/UiAnimViewDopeSheetBase.h
    Editor/Animation/UiAnimViewEventNode.cpp
    Editor/Animation/UiAnimViewEventNode.h
    Editor/Animation/UiAnimViewFindDlg.cpp
    Editor/Animation/UiAnimViewFindDlg.h
    Editor/Animation/UiAnimViewFindDlg.ui
    Editor/Animation/UiAnimViewKeyPropertiesDlg.cpp
    Editor/Animation/UiAnimViewKeyPropertiesDlg.h
    Editor/Animation/UiAnimViewNewSequenceDialog.cpp
    Editor/Animation/UiAnimViewNewSequenceDialog.h
    Editor/Animation/UiAnimViewNewSequenceDialog.ui
    Editor/Animation/UiAnimViewNode.cpp
    Editor/Animation/UiAnimViewNode.h
    Editor/Animation/UiAnimViewNodeFactories.cpp
    Editor/Animation/UiAnimViewNodeFactories.h
    Editor/Animation/UiAnimViewNodes.cpp
    Editor/Animation/UiAnimViewNodes.h
    Editor/Animation/UiAnimViewNodes.ui
    Editor/Animation/UiAnimViewSequence.cpp
    Editor/Animation/UiAnimViewSequence.h
    Editor/Animation/UiAnimViewSequenceManager.cpp
    Editor/Animation/UiAnimViewSequenceManager.h
    Editor/Animation/UiAnimViewSplineCtrl.cpp
    Editor/Animation/UiAnimViewSplineCtrl.h
    Editor/Animation/UiAnimViewTrack.cpp
    Editor/Animation/UiAnimViewTrack.h
    Editor/Animation/UiAnimViewTrackPropsDlg.ui
    Editor/Animation/UiAnimViewUndo.cpp
    Editor/Animation/UiAnimViewUndo.h
    Editor/Animation/UiAVCustomizeTrackColorsDialog.ui
    Editor/Animation/UiAVCustomizeTrackColorsDlg.cpp
    Editor/Animation/UiAVCustomizeTrackColorsDlg.h
    Editor/Animation/UiAVEventsDialog.cpp
    Editor/Animation/UiAVEventsDialog.h
    Editor/Animation/UiAVEventsDialog.ui
    Editor/Animation/UiAVSequenceProps.cpp
    Editor/Animation/UiAVSequenceProps.h
    Editor/Animation/UiAVSequenceProps.ui
    Editor/Animation/UiAVTrackEventKeyUIControls.cpp
    Editor/Animation/UiAVTrackEventKeyUIControls.h
    Editor/Animation/Util/UiEditorUtils.cpp
    Editor/Commands/CommandCanvasPropertiesChange.cpp
    Editor/Commands/CommandCanvasPropertiesChange.h
    Editor/Commands/CommandCanvasSize.cpp
    Editor/Commands/CommandCanvasSize.h
    Editor/Commands/CommandCanvasSizeToolbarIndex.cpp
    Editor/Commands/CommandCanvasSizeToolbarIndex.h
    Editor/Commands/CommandHierarchyItemCreate.cpp
    Editor/Commands/CommandHierarchyItemCreate.h
    Editor/Commands/CommandHierarchyItemCreateFromData.cpp
    Editor/Commands/CommandHierarchyItemCreateFromData.h
    Editor/Commands/CommandHierarchyItemDelete.cpp
    Editor/Commands/CommandHierarchyItemDelete.h
    Editor/Commands/CommandHierarchyItemRename.cpp
    Editor/Commands/CommandHierarchyItemRename.h
    Editor/Commands/CommandHierarchyItemReparent.cpp
    Editor/Commands/CommandHierarchyItemReparent.h
    Editor/Commands/CommandHierarchyItemToggleIsExpanded.cpp
    Editor/Commands/CommandHierarchyItemToggleIsExpanded.h
    Editor/Commands/CommandHierarchyItemToggleIsSelectable.cpp
    Editor/Commands/CommandHierarchyItemToggleIsSelectable.h
    Editor/Commands/CommandHierarchyItemToggleIsVisible.cpp
    Editor/Commands/CommandHierarchyItemToggleIsVisible.h
    Editor/Commands/CommandPropertiesChange.cpp
    Editor/Commands/CommandPropertiesChange.h
    Editor/Dialogs/SpriteBorderEditor/SlicerEdit.cpp
    Editor/Dialogs/SpriteBorderEditor/SlicerEdit.h
    Editor/Dialogs/SpriteBorderEditor/SlicerManipulator.cpp
    Editor/Dialogs/SpriteBorderEditor/SlicerManipulator.h
    Editor/Dialogs/SpriteBorderEditor/SlicerView.cpp
    Editor/Dialogs/SpriteBorderEditor/SlicerView.h
    Editor/Dialogs/SpriteBorderEditor/SpriteBorderEditor.cpp
    Editor/Dialogs/SpriteBorderEditor/SpriteBorderEditor.h
    Editor/Dialogs/SpriteBorderEditor/SpriteBorderEditorCommon.cpp
    Editor/Dialogs/SpriteBorderEditor/SpriteBorderEditorCommon.h
    Editor/Helpers/AssetDropHelpers.cpp
    Editor/Helpers/AssetDropHelpers.h
    Editor/Helpers/CanvasHelpers.cpp
    Editor/Helpers/CanvasHelpers.h
    Editor/Helpers/ComponentAssetHelpers.h
    Editor/Helpers/ComponentHelpers.cpp
    Editor/Helpers/ComponentHelpers.h
    Editor/Helpers/EntityHelpers.cpp
    Editor/Helpers/EntityHelpers.h
    Editor/Helpers/FileHelpers.cpp
    Editor/Helpers/FileHelpers.h
    Editor/Helpers/GuideHelpers.cpp
    Editor/Helpers/GuideHelpers.h
    Editor/Helpers/HierarchyHelpers.cpp
    Editor/Helpers/HierarchyHelpers.h
    Editor/Helpers/QtHelpers.cpp
    Editor/Helpers/QtHelpers.h
    Editor/Helpers/RecentFiles.cpp
    Editor/Helpers/RecentFiles.h
    Editor/Helpers/SelectionHelpers.cpp
    Editor/Helpers/SelectionHelpers.h
    Editor/Helpers/SerializeHelpers.cpp
    Editor/Helpers/SerializeHelpers.h
    Editor/Helpers/SliceMenuHelpers.cpp
    Editor/Helpers/SliceMenuHelpers.h
    Editor/Helpers/ViewportHelpers.cpp
    Editor/Helpers/ViewportHelpers.h
    Editor/LyShineEditorSystemComponent.cpp
    Editor/LyShineEditorSystemComponent.h
    Editor/Toolbar/AlignToolbarSection.cpp
    Editor/Toolbar/AlignToolbarSection.h
    Editor/Toolbar/CanvasSizeToolbarSection.cpp
    Editor/Toolbar/CanvasSizeToolbarSection.h
    Editor/Toolbar/CoordinateSystemToolbarSection.cpp
    Editor/Toolbar/CoordinateSystemToolbarSection.h
    Editor/Toolbar/EnterPreviewToolbar.cpp
    Editor/Toolbar/EnterPreviewToolbar.h
    Editor/Toolbar/MainToolbar.cpp
    Editor/Toolbar/MainToolbar.h
    Editor/Toolbar/ModeToolbar.cpp
    Editor/Toolbar/ModeToolbar.h
    Editor/Toolbar/NewElementToolbarSection.cpp
    Editor/Toolbar/NewElementToolbarSection.h
    Editor/Toolbar/PreviewToolbar.cpp
    Editor/Toolbar/PreviewToolbar.h
    Editor/UiEditorEntityContext.cpp
    Editor/UiEditorEntityContext.h
    Editor/UiEditorEntityContextBus.h
    Editor/UiEditorInternalBus.h
    Editor/Undo/UndoStack.cpp
    Editor/Undo/UndoStack.h
    Editor/Undo/UndoStackExecutionScope.cpp
    Editor/Undo/UndoStackExecutionScope.h
    Editor/Widgets/AnchorWidget/AnchorPresets.cpp
    Editor/Widgets/AnchorWidget/AnchorPresets.h
    Editor/Widgets/AnchorWidget/AnchorPresetsWidget.cpp
    Editor/Widgets/AnchorWidget/AnchorPresetsWidget.h
    Editor/Widgets/ComponentButton.cpp
    Editor/Widgets/ComponentButton.h
    Editor/Widgets/FindEntityWidget/FindEntityItemModel.cpp
    Editor/Widgets/FindEntityWidget/FindEntityItemModel.h
    Editor/Widgets/FindEntityWidget/FindEntitySortFilterProxyModel.cpp
    Editor/Widgets/FindEntityWidget/FindEntitySortFilterProxyModel.h
    Editor/Widgets/FindEntityWidget/FindEntityWidget.cpp
    Editor/Widgets/FindEntityWidget/FindEntityWidget.h
    Editor/Widgets/HierarchyWidget/HierarchyClipboard.cpp
    Editor/Widgets/HierarchyWidget/HierarchyClipboard.h
    Editor/Widgets/HierarchyWidget/HierarchyHeader.cpp
    Editor/Widgets/HierarchyWidget/HierarchyHeader.h
    Editor/Widgets/HierarchyWidget/HierarchyItem.cpp
    Editor/Widgets/HierarchyWidget/HierarchyItem.h
    Editor/Widgets/HierarchyWidget/HierarchyMenu.cpp
    Editor/Widgets/HierarchyWidget/HierarchyMenu.h
    Editor/Widgets/HierarchyWidget/HierarchyWidget.cpp
    Editor/Widgets/HierarchyWidget/HierarchyWidget.h
    Editor/Widgets/HierarchyWidget/TreeWidgetItemList.h
    Editor/Widgets/PivotWidget/PivotPresets.cpp
    Editor/Widgets/PivotWidget/PivotPresets.h
    Editor/Widgets/PivotWidget/PivotPresetsWidget.cpp
    Editor/Widgets/PivotWidget/PivotPresetsWidget.h
    Editor/Widgets/PresetButton.cpp
    Editor/Widgets/PresetButton.h
    Editor/Widgets/PreviewActionWidget/PreviewActionLog.cpp
    Editor/Widgets/PreviewActionWidget/PreviewActionLog.h
    Editor/Widgets/PropertiesWidget/PropertiesContainer.cpp
    Editor/Widgets/PropertiesWidget/PropertiesContainer.h
    Editor/Widgets/PropertiesWidget/PropertiesWidget.cpp
    Editor/Widgets/PropertiesWidget/PropertiesWidget.h
    Editor/Widgets/PropertiesWidget/PropertiesWrapper.cpp
    Editor/Widgets/PropertiesWidget/PropertiesWrapper.h
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerAnchor.cpp
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerAnchor.h
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerCanvasAsset.cpp
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerCanvasAsset.h
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerChar.cpp
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerChar.h
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerDirectory.cpp
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerDirectory.h
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerEntityIdComboBox.cpp
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerEntityIdComboBox.h
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerLayoutPadding.cpp
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerLayoutPadding.h
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerOffset.cpp
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerOffset.h
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerPivot.cpp
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerPivot.h
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlers.cpp
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlers.h
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerSprite.cpp
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerSprite.h
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerUiParticleColorKeyframe.cpp
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerUiParticleColorKeyframe.h
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerUiParticleFloatKeyframe.cpp
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerUiParticleFloatKeyframe.h
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerVec.cpp
    Editor/Widgets/PropertiesWidget/PropertyHandlers/PropertyHandlerVec.h
    Editor/Widgets/PropertiesWidget/PropertyHandlers/UIVectorPropertyHandlerBase.h
    Editor/Widgets/ViewportWidget/DragInteraction/ViewportAddGuideInteraction.cpp
    Editor/Widgets/ViewportWidget/DragInteraction/ViewportAddGuideInteraction.h
    Editor/Widgets/ViewportWidget/DragInteraction/ViewportDragInteraction.cpp
    Editor/Widgets/ViewportWidget/DragInteraction/ViewportDragInteraction.h
    Editor/Widgets/ViewportWidget/DragInteraction/ViewportMoveGuideInteraction.cpp
    Editor/Widgets/ViewportWidget/DragInteraction/ViewportMoveGuideInteraction.h
    Editor/Widgets/ViewportWidget/DragInteraction/ViewportMoveInteraction.cpp
    Editor/Widgets/ViewportWidget/DragInteraction/ViewportMoveInteraction.h
    Editor/Widgets/ViewportWidget/Interaction/ViewportAlign.cpp
    Editor/Widgets/ViewportWidget/Interaction/ViewportAlign.h
    Editor/Widgets/ViewportWidget/Interaction/ViewportAnchor.cpp
    Editor/Widgets/ViewportWidget/Interaction/ViewportAnchor.h
    Editor/Widgets/ViewportWidget/Interaction/ViewportInteraction.cpp
    Editor/Widgets/ViewportWidget/Interaction/ViewportInteraction.h
    Editor/Widgets/ViewportWidget/Interaction/ViewportNudge.cpp
    Editor/Widgets/ViewportWidget/Interaction/ViewportNudge.h
    Editor/Widgets/ViewportWidget/Interaction/ViewportPivot.cpp
    Editor/Widgets/ViewportWidget/Interaction/ViewportPivot.h
    Editor/Widgets/ViewportWidget/Interaction/ViewportSnap.cpp
    Editor/Widgets/ViewportWidget/Interaction/ViewportSnap.h
    Editor/Widgets/ViewportWidget/RulerWidget/RulerWidget.cpp
    Editor/Widgets/ViewportWidget/RulerWidget/RulerWidget.h
    Editor/Widgets/ViewportWidget/ViewportCanvasBackground.cpp
    Editor/Widgets/ViewportWidget/ViewportCanvasBackground.h
    Editor/Widgets/ViewportWidget/ViewportElement.cpp
    Editor/Widgets/ViewportWidget/ViewportElement.h
    Editor/Widgets/ViewportWidget/ViewportHighlight.cpp
    Editor/Widgets/ViewportWidget/ViewportHighlight.h
    Editor/Widgets/ViewportWidget/ViewportIcon.cpp
    Editor/Widgets/ViewportWidget/ViewportIcon.h
    Editor/Widgets/ViewportWidget/ViewportWidget.cpp
    Editor/Widgets/ViewportWidget/ViewportWidget.h
    Editor/Windows/EditorCommon.cpp
    Editor/Windows/EditorCommon.h
    Editor/Windows/EditorWindow/AssetTreeEntry.cpp
    Editor/Windows/EditorWindow/AssetTreeEntry.h
    Editor/Windows/EditorWindow/EditorMenu.cpp
    Editor/Windows/EditorWindow/EditorWindow.cpp
    Editor/Windows/EditorWindow/EditorWindow.h
    Editor/Windows/EditorWindow/UiCanvasEditor.qrc
    Editor/Windows/EditorWindow/UiSliceManager.cpp
    Editor/Windows/EditorWindow/UiSliceManager.h
    Editor/Windows/PreviewAnimationWindow/PreviewAnimationList.cpp
    Editor/Windows/PreviewAnimationWindow/PreviewAnimationList.h
)
