set(FILES
    Source/${Name}ModuleInterface.cpp
    Source/${Name}ModuleInterface.h
    Source/Clients/${Name}SystemComponent.cpp
    Source/Clients/${Name}SystemComponent.h
    Source/Components/${Name}ComponentController.cpp
    Source/Components/${Name}ComponentController.h
    Source/Components/${Name}Component.cpp
    Source/Components/${Name}Component.h
)
