set(FILES
    Source/${Name}ModuleInterface.cpp
    Source/${Name}ModuleInterface.h
    Source/Clients/${Name}SystemComponent.cpp
    Source/Clients/${Name}SystemComponent.h
    Source/Components/ExampleComponentController.cpp
    Source/Components/ExampleComponentController.h
    Source/Components/ExampleComponent.cpp
    Source/Components/ExampleComponent.h
)
