#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Source/ComponentDescriptors.cpp
    Source/ComponentDescriptors.h
    Tests/PhysXComponentBusTests.cpp
    Tests/PhysXGenericTestFixture.h
    Tests/PhysXGenericTestFixture.cpp
    Tests/PhysXTestCommon.h
    Tests/PhysXTestCommon.inl
    Tests/PhysXTestCommon.cpp
    Tests/PhysXTestEnvironment.h
    Tests/PhysXTestEnvironment.cpp
    Tests/PhysXGenericTest.cpp
    Tests/PhysXMaterialTest.cpp
    Tests/PhysXSpecificTest.cpp
    Tests/PhysXForceRegionTest.cpp
    Tests/PhysXCollisionFilteringTest.cpp
    Tests/PhysXJointsTest.cpp
    Tests/PhysXSceneTests.cpp
    Tests/PhysXSceneQueryTests.cpp
    Tests/PhysXSystemTests.cpp
    Tests/PhysXTestFixtures.h
    Tests/PhysXTestFixtures.cpp
    Tests/PhysXTestUtil.h
    Tests/PhysXTestUtil.cpp
    Tests/PhysXMultithreadingTest.cpp
    Tests/PhysXScriptTest.cpp
    Tests/CharacterControllerTests.cpp
    Tests/CharacterGameplayControllerTests.cpp
    Tests/RagdollConfiguration.h
    Tests/RagdollTestData.h
    Tests/RagdollTests.cpp
    Tests/Benchmarks/PhysXBenchmarksUtilities.cpp
    Tests/Benchmarks/PhysXBenchmarksUtilities.h
    Tests/Benchmarks/PhysXBenchmarksCommon.h
    Tests/Benchmarks/PhysXBenchmarksCommon.cpp
    Tests/Benchmarks/PhysXBenchmarkWashingMachine.h
    Tests/Benchmarks/PhysXBenchmarkWashingMachine.cpp
    Tests/Benchmarks/PhysXCharactersBenchmarks.cpp
    Tests/Benchmarks/PhysXCharactersRagdollBenchmarks.cpp
    Tests/Benchmarks/PhysXGenericBenchmarks.cpp
    Tests/Benchmarks/PhysXSceneQueryBenchmarks.cpp
    Tests/Benchmarks/PhysXRigidBodyBenchmarks.cpp
    Tests/Benchmarks/PhysXJointBenchmarks.cpp
)
