#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
Tests/Artifact/TestImpactNativeTargetDescriptorCompilerTest.cpp
Tests/Artifact/TestImpactNativeTargetDescriptorFactoryTest.cpp
Tests/Artifact/TestImpactModuleCoverageFactoryTest.cpp
Tests/Artifact/TestImpactTestEnumerationSuiteFactoryTest.cpp
Tests/Artifact/TestImpactTestRunSuiteFactoryTest.cpp
Tests/Artifact/TestImpactNativeTestTargetMetaMapFactoryTest.cpp
Tests/Artifact/TestImpactDependencyGraphDataFactoryTest.cpp
Tests/Process/TestImpactProcessSchedulerTest.cpp
Tests/Dependency/TestImpactDynamicDependencyMapTest.cpp
Tests/Dependency/TestImpactSourceDependencyTest.cpp
Tests/Dependency/TestImpactSourceCoveringTestsListTest.cpp
Tests/Dependency/TestImpactSourceCoveringTestsSerializerTest.cpp
Tests/Dependency/TestImpactTestSelectorAndPrioritizerTest.cpp
Tests/Process/TestImpactProcessTest.cpp
Tests/Target/TestImpactBuildTargetTest.cpp
Tests/TestRunner/TestImpactTestEnumeratorTest.cpp
Tests/TestRunner/TestImpactTestEumerationSerializerTest.cpp
Tests/TestRunner/TestImpactTestRunSerializerTest.cpp
Tests/TestRunner/TestImpactTestRunnerTest.cpp
Tests/TestRunner/TestImpactInstrumentedTestRunnerTest.cpp
Tests/TestRunner/TestImpactPythonTestRunnerTest.cpp
Tests/TestRunner/TestImpactTestCoverageTest.cpp
Tests/TestEngine/TestImpactNativeTestEngineTest.cpp
Tests/TestEngine/TestImpactNativeTestJobInfoGeneratorTest.cpp
Tests/TestEngine/TestImpactPythonTestEngineTest.cpp
Tests/TestImpactRuntimeTestMain.cpp
Tests/TestImpactExceptionTest.cpp
Tests/TestImpactTestJobRunnerCommon.h
Tests/TestImpactTestUtils.cpp
Tests/TestImpactTestUtils.h
Tests/TestImpactMicroRepo.cpp
Tests/TestImpactMicroRepo.h
Tests/TestImpactRuntimeTest.cpp
Tests/TestImpactRepoPathTest.cpp
Tests/TestImpactRuntimeUtilsTest.cpp
Tests/TestImpactChangeListSerializerTest.cpp
)
