/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */
#pragma once

#define AZ_TRAIT_ATOM_SHADERBUILDER_DXC UNUSED_TRAIT
#define AZ_TRAIT_ATOM_AZSL_SHADER_HEADER UNUSED_TRAIT
#define AZ_TRAIT_ATOM_AZSL_PLATFORM_HEADER UNUSED_TRAIT
#define AZ_TRAIT_ATOM_MOBILE_AZSL_SHADER_HEADER UNUSED_TRAIT
#define AZ_TRAIT_ATOM_MOBILE_AZSL_PLATFORM_HEADER UNUSED_TRAIT
#define AZ_TRAIT_ATOM_VULKAN_DISABLE_DUAL_SOURCE_BLENDING 1
#define AZ_TRAIT_ATOM_VULKAN_LAYER_LUNARG_STD_VALIDATION_SUPPORT 0
#define AZ_TRAIT_ATOM_VULKAN_RECREATE_SWAPCHAIN_WHEN_SUBOPTIMAL 0
#define AZ_TRAIT_ATOM_VULKAN_SWAPCHAIN_SCALING_FLAGS AZ::RHI::ScalingFlags::Stretch
