#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    AzNetworkingModule.cpp
    ConnectionLayer/ConnectionMetrics.cpp
    ConnectionLayer/ConnectionMetrics.inl
    ConnectionLayer/IConnection.inl
    ConnectionLayer/SequenceGenerator.inl
    DataStructures/ByteBuffer.inl
    DataStructures/FixedSizeBitset.inl
    DataStructures/FixedSizeBitsetView.inl
    DataStructures/FixedSizeVectorBitset.inl
    DataStructures/RingBufferBitset.inl
    DataStructures/TimeoutQueue.cpp
    DataStructures/TimeoutQueue.inl
    Framework/NetworkingSystemComponent.cpp
    Serialization/DeltaSerializer.cpp
    Serialization/DeltaSerializer.inl
    Serialization/HashSerializer.cpp
    Serialization/ISerializer.inl
    Serialization/NetworkInputSerializer.cpp
    Serialization/NetworkOutputSerializer.cpp
    Serialization/NetworkOutputSerializer.inl
    Serialization/StringifySerializer.cpp
    Serialization/TrackChangedSerializer.inl
    TcpTransport/TcpConnection.cpp
    TcpTransport/TcpConnection.inl
    TcpTransport/TcpConnectionSet.cpp
    TcpTransport/TcpPacketHeader.cpp
    TcpTransport/TcpPacketHeader.inl
    TcpTransport/TcpRingBuffer.inl
    TcpTransport/TcpRingBufferImpl.cpp
    TcpTransport/TcpRingBufferImpl.inl
    TcpTransport/TcpSocket.cpp
    TcpTransport/TcpSocket.inl
    TcpTransport/TcpSocketManager_Epoll.cpp
    TcpTransport/TcpSocketManager_None.cpp
    TcpTransport/TcpSocketManager_Select.cpp
    TcpTransport/TlsSocket.cpp
    TcpTransport/TcpListenThread.cpp
    TcpTransport/TcpNetworkInterface.cpp
    UdpTransport/DtlsEndpoint.cpp
    UdpTransport/DtlsSocket.cpp
    UdpTransport/UdpConnection.cpp
    UdpTransport/UdpConnection.inl
    UdpTransport/UdpConnectionSet.cpp
    UdpTransport/UdpFragmentQueue.cpp
    UdpTransport/UdpNetworkInterface.cpp
    UdpTransport/UdpPacketHeader.cpp
    UdpTransport/UdpPacketHeader.inl
    UdpTransport/UdpPacketIdWindow.cpp
    UdpTransport/UdpPacketIdWindow.inl
    UdpTransport/UdpPacketTracker.cpp
    UdpTransport/UdpPacketTracker.inl
    UdpTransport/UdpReaderThread.cpp
    UdpTransport/UdpReliableQueue.cpp
    UdpTransport/UdpSocket.cpp
    UdpTransport/UdpSocket.inl
    Utilities/CidrAddress.cpp
    Utilities/EncryptionCommon.cpp
    Utilities/IpAddress.cpp
    Utilities/IpAddress.inl
    Utilities/NetworkCommon.cpp
    Utilities/NetworkCommon.inl
    Utilities/QuantizedValues.inl
    Utilities/TimedThread.cpp
)
