#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Tests/Buffer/BufferTests.cpp
    Tests/Common/AssetManagerTestFixture.cpp
    Tests/Common/AssetManagerTestFixture.h
    Tests/Common/ErrorMessageFinder.cpp
    Tests/Common/ErrorMessageFinder.h
    Tests/Common/ErrorMessageFinderTests.cpp
    Tests/Common/JsonTestUtils.cpp
    Tests/Common/JsonTestUtils.h
    Tests/Common/RPITestFixture.cpp
    Tests/Common/RPITestFixture.h
    Tests/Common/SerializeTester.h
    Tests/Common/ShaderAssetTestUtils.cpp
    Tests/Common/ShaderAssetTestUtils.h
    Tests/Common/TestUtils.h
    Tests/Common/TestFeatureProcessors.h
    Tests/Image/StreamingImageTests.cpp
    Tests/Material/LuaMaterialFunctorTests.cpp
    Tests/Material/MaterialVersionUpdateTests.cpp
    Tests/Material/MaterialTypeAssetTests.cpp
    Tests/Material/MaterialTypeSourceDataTests.cpp
    Tests/Material/MaterialAssetTestUtils.cpp
    Tests/Material/MaterialAssetTestUtils.h
    Tests/Material/MaterialPropertySerializerTests.cpp
    Tests/Material/MaterialAssetTests.cpp
    Tests/Material/MaterialSourceDataTests.cpp
    Tests/Material/MaterialFunctorTests.cpp
    Tests/Material/MaterialFunctorSourceDataSerializerTests.cpp
    Tests/Material/MaterialPropertyIdTests.cpp
    Tests/Material/MaterialPropertyValueSourceDataTests.cpp
    Tests/Material/MaterialTests.cpp
    Tests/Model/ModelTests.cpp
    Tests/Model/SkinJointIdPaddingTests.cpp
    Tests/Pass/PassTests.cpp
    Tests/Shader/ShaderTests.cpp
    Tests/ShaderResourceGroup/ShaderResourceGroupBufferTests.cpp
    Tests/ShaderResourceGroup/ShaderResourceGroupConstantBufferTests.cpp
    Tests/ShaderResourceGroup/ShaderResourceGroupImageTests.cpp
    Tests/ShaderResourceGroup/ShaderResourceGroupGeneralTests.cpp
    Tests/System/CullingTests.cpp
    Tests/System/FeatureProcessorFactoryTests.cpp
    Tests/System/GpuQueryTests.cpp
    Tests/System/RenderPipelineTests.cpp
    Tests/System/SceneTests.cpp
    Tests/System/ViewTests.cpp
    Tests/Utils/AssetUtilsTests.cpp
)
