#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Source/AABB.h
    Source/Algorithms.cpp
    Source/Algorithms.h
    Source/Algorithms.inl
    Source/Array2D.h
    Source/Array2D.inl
    Source/Attribute.cpp
    Source/Attribute.h
    Source/AttributeAllocator.h
    Source/AttributeBool.cpp
    Source/AttributeBool.h
    Source/AttributeColor.h
    Source/AttributeCreateFunctions.cpp
    Source/AttributeFactory.cpp
    Source/AttributeFactory.h
    Source/AttributeFloat.cpp
    Source/AttributeFloat.h
    Source/AttributeInt32.cpp
    Source/AttributeInt32.h
    Source/AttributePointer.h
    Source/AttributeQuaternion.h
    Source/AttributeString.h
    Source/AttributeVector2.h
    Source/AttributeVector3.h
    Source/AttributeVector4.h
    Source/AzCoreConversions.h
    Source/BoundingSphere.h
    Source/Color.cpp
    Source/Color.h
    Source/Command.cpp
    Source/Command.h
    Source/CommandGroup.cpp
    Source/CommandGroup.h
    Source/CommandLine.cpp
    Source/CommandLine.h
    Source/MCoreCommandManager.cpp
    Source/MCoreCommandManager.h
    Source/CommandManagerCallback.h
    Source/CommandSyntax.cpp
    Source/CommandSyntax.h
    Source/Compare.h
    Source/Compare.inl
    Source/CompressedFloat.h
    Source/CompressedFloat.inl
    Source/CompressedQuaternion.h
    Source/CompressedQuaternion.inl
    Source/CompressedVector.h
    Source/CompressedVector.inl
    Source/Config.h
    Source/DelaunayTriangulator.h
    Source/DelaunayTriangulator.cpp
    Source/DiskFile.cpp
    Source/DiskFile.h
    Source/Distance.cpp
    Source/Distance.h
    Source/DualQuaternion.cpp
    Source/DualQuaternion.h
    Source/DualQuaternion.inl
    Source/Endian.h
    Source/Endian.inl
    Source/FastMath.cpp
    Source/FastMath.h
    Source/FastMath.inl
    Source/File.h
    Source/FileSystem.cpp
    Source/FileSystem.h
    Source/IDGenerator.cpp
    Source/IDGenerator.h
    Source/LogManager.cpp
    Source/LogManager.h
    Source/Macros.h
    Source/MCoreSystem.cpp
    Source/MCoreSystem.h
    Source/MemoryCategoriesCore.h
    Source/MemoryFile.cpp
    Source/MemoryFile.h
    Source/MemoryManager.cpp
    Source/MemoryManager.h
    Source/MemoryObject.cpp
    Source/MemoryObject.h
    Source/MemoryTracker.cpp
    Source/MemoryTracker.h
    Source/MultiThreadManager.h
    Source/PlaneEq.h
    Source/Random.cpp
    Source/Random.h
    Source/Ray.cpp
    Source/Ray.h
    Source/StaticAllocator.cpp
    Source/StaticAllocator.h
    Source/StaticString.h
    Source/StandardHeaders.h
    Source/Stream.h
    Source/StringConversions.cpp
    Source/StringConversions.h
    Source/StringIdPool.cpp
    Source/StringIdPool.h
    Source/ReflectionSerializer.cpp
    Source/ReflectionSerializer.h
    Source/Vector.h
)
