/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */

#pragma once

#include <AssetBuilderSDK/AssetBuilderBusses.h>
#include <Atom/RPI.Reflect/Material/MaterialTypeAsset.h>
#include <Atom/RPI.Edit/Material/MaterialPipelineSourceData.h>
#include <AzCore/JSON/document.h>

namespace AZ
{
    namespace RPI
    {
        class MaterialTypeSourceData;

        class MaterialTypeBuilder final
            : public AssetBuilderSDK::AssetBuilderCommandBus::Handler
        {
        public:
            AZ_TYPE_INFO(MaterialTypeBuilder, "{0D2D104F-9CC6-456E-88D9-24BCDA6C0465}");

            static const char* MaterialPipelineJobKey;
            static const char* FinalMaterialTypeJobKey;

            MaterialTypeBuilder() = default;
            ~MaterialTypeBuilder();

            // Asset Builder Callback Functions
            void CreateJobs(const AssetBuilderSDK::CreateJobsRequest& request, AssetBuilderSDK::CreateJobsResponse& response) const;
            void ProcessJob(const AssetBuilderSDK::ProcessJobRequest& request, AssetBuilderSDK::ProcessJobResponse& response) const;

            // AssetBuilderSDK::AssetBuilderCommandBus interface
            void ShutDown() override;

            /// Register to builder and listen to builder command
            void RegisterBuilder();

        private:

            //! These job functions operate on .materialtype files in the "abstract" format (see MaterialTypeSourceData), by matching them with each material pipeline.
            //! This will produce an intermediate .materialtype file that uses the "direct" format, which the "Final" stage job (below) will process.
            void CreatePipelineJobs(const AssetBuilderSDK::CreateJobsRequest& request, AssetBuilderSDK::CreateJobsResponse& response, const MaterialTypeSourceData& materialTypeSourceData) const;
            void ProcessPipelineJob(const AssetBuilderSDK::ProcessJobRequest& request, AssetBuilderSDK::ProcessJobResponse& response) const;

            //! These job functions operate on .materialtype files in the "direct" format (see MaterialTypeSourceData), which includes a full list of shaders.
            //! The .materialtype file could be hand-authored in a source folder, or it could be an intermediate .materialtype that was generated by the "Pipeline" stage job (above).
            //! In either case, it will produce a final MaterialTypeAsset in the cache.
            void CreateFinalJobs(const AssetBuilderSDK::CreateJobsRequest& request, AssetBuilderSDK::CreateJobsResponse& response, const MaterialTypeSourceData& materialTypeSourceData) const;
            void ProcessFinalJob(const AssetBuilderSDK::ProcessJobRequest& request, AssetBuilderSDK::ProcessJobResponse& response) const;

            AZStd::string GetFilenameStem(const AZStd::string& filePath) const;

            enum class MaterialTypeProductSubId : u32
            {
                MaterialTypeAsset = 0,
                AllPropertiesMaterialSourceFile = 1
            };

            bool ShouldOutputAllPropertiesMaterial() const;
            AZStd::string GetBuilderSettingsFingerprint() const;

            void LoadMaterialPipelines();
            
            bool m_isShuttingDown = false;

            AZStd::map<AZStd::string/*path*/, MaterialPipelineSourceData> m_materialPipelines;
        };

    } // namespace RPI
} // namespace AZ
