#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#

set(FILES
    CryDXGL.cpp
    CryDXGL.hpp
    RenderCapabilities.cpp
    Definitions/CryDXGLGuid.hpp
    Definitions/CryDXGLLegacy.hpp
    Definitions/CryDXGLMisc.hpp
    Definitions/DXGL_D3D11.h
    Definitions/DXGL_D3D11Shader.h
    Definitions/DXGL_D3DCommon.h
    Definitions/DXGL_D3DCompiler.h
    Definitions/DXGL_D3DX11.h
    Definitions/DXGL_D3DX11tex.h
    Definitions/DXGL_ID3D11Device.h
    Definitions/DXGL_ID3D11DeviceContext.h
    Definitions/DXGL_IDXGIFactory1.h
    Definitions/DXGL_IDXGISwapChain.h
    Definitions/DXGL_dxgi.h
    Definitions/DXGL_dxgitype.h
    Definitions/ICryDXGLUnknown.hpp
    Implementation/AppleGPUInfoUtils.h
    Implementation/GLCommon.hpp
    Implementation/GLContext.cpp
    Implementation/GLContext.hpp
    Implementation/GLCryPlatform.hpp
    Implementation/GLDevice.cpp
    Implementation/GLDevice.hpp
    Implementation/GLFeatures.hpp
    Implementation/GLFormat.cpp
    Implementation/GLFormat.hpp
    Implementation/GLInstrument.hpp
    Implementation/GLPlatform.hpp
    Implementation/GLResource.cpp
    Implementation/GLResource.hpp
    Implementation/GLShader.cpp
    Implementation/GLShader.hpp
    Implementation/GLState.cpp
    Implementation/GLState.hpp
    Implementation/GLView.cpp
    Implementation/GLView.hpp
    Implementation/GLBlitFramebufferHelper.hpp
    Implementation/GLBlitFramebufferHelper.cpp
    Implementation/GLBlitShaders.hpp
    Implementation/GLADLoader.cpp
    Interfaces/CCryDXGLBase.cpp
    Interfaces/CCryDXGLBase.hpp
    Interfaces/CCryDXGLBlendState.cpp
    Interfaces/CCryDXGLBlendState.hpp
    Interfaces/CCryDXGLBlob.cpp
    Interfaces/CCryDXGLBlob.hpp
    Interfaces/CCryDXGLBuffer.cpp
    Interfaces/CCryDXGLBuffer.hpp
    Interfaces/CCryDXGLDepthStencilState.cpp
    Interfaces/CCryDXGLDepthStencilState.hpp
    Interfaces/CCryDXGLDepthStencilView.cpp
    Interfaces/CCryDXGLDepthStencilView.hpp
    Interfaces/CCryDXGLDevice.cpp
    Interfaces/CCryDXGLDevice.hpp
    Interfaces/CCryDXGLDeviceChild.cpp
    Interfaces/CCryDXGLDeviceChild.hpp
    Interfaces/CCryDXGLDeviceContext.cpp
    Interfaces/CCryDXGLDeviceContext.hpp
    Interfaces/CCryDXGLGIAdapter.cpp
    Interfaces/CCryDXGLGIAdapter.hpp
    Interfaces/CCryDXGLGIFactory.cpp
    Interfaces/CCryDXGLGIFactory.hpp
    Interfaces/CCryDXGLGIObject.cpp
    Interfaces/CCryDXGLGIObject.hpp
    Interfaces/CCryDXGLGIOutput.cpp
    Interfaces/CCryDXGLGIOutput.hpp
    Interfaces/CCryDXGLInputLayout.cpp
    Interfaces/CCryDXGLInputLayout.hpp
    Interfaces/CCryDXGLQuery.cpp
    Interfaces/CCryDXGLQuery.hpp
    Interfaces/CCryDXGLRasterizerState.cpp
    Interfaces/CCryDXGLRasterizerState.hpp
    Interfaces/CCryDXGLRenderTargetView.cpp
    Interfaces/CCryDXGLRenderTargetView.hpp
    Interfaces/CCryDXGLResource.cpp
    Interfaces/CCryDXGLResource.hpp
    Interfaces/CCryDXGLSamplerState.cpp
    Interfaces/CCryDXGLSamplerState.hpp
    Interfaces/CCryDXGLShader.cpp
    Interfaces/CCryDXGLShader.hpp
    Interfaces/CCryDXGLShaderReflection.cpp
    Interfaces/CCryDXGLShaderReflection.hpp
    Interfaces/CCryDXGLShaderResourceView.cpp
    Interfaces/CCryDXGLShaderResourceView.hpp
    Interfaces/CCryDXGLSwapChain.cpp
    Interfaces/CCryDXGLSwapChain.hpp
    Interfaces/CCryDXGLSwitchToRef.cpp
    Interfaces/CCryDXGLSwitchToRef.hpp
    Interfaces/CCryDXGLTexture1D.cpp
    Interfaces/CCryDXGLTexture1D.hpp
    Interfaces/CCryDXGLTexture2D.cpp
    Interfaces/CCryDXGLTexture2D.hpp
    Interfaces/CCryDXGLTexture3D.cpp
    Interfaces/CCryDXGLTexture3D.hpp
    Interfaces/CCryDXGLTextureBase.cpp
    Interfaces/CCryDXGLTextureBase.hpp
    Interfaces/CCryDXGLUnorderedAccessView.cpp
    Interfaces/CCryDXGLUnorderedAccessView.hpp
    Interfaces/CCryDXGLView.cpp
    Interfaces/CCryDXGLView.hpp
    Interfaces/DXEmulation.hpp
    ../../RenderDll_precompiled.cpp
)

# Prevent the following files from being grouped in UNITY builds
set(SKIP_UNITY_BUILD_INCLUSION_FILES
    Implementation/GLADLoader.cpp
    Implementation/GLBlitFramebufferHelper.hpp
    Implementation/GLBlitFramebufferHelper.cpp
    Implementation/GLShader.cpp
    Implementation/GLShader.hpp
)