#
# Copyright (c) Contributors to the Open 3D Engine Project. For complete copyright and license terms please see the LICENSE at the root of this distribution.
# 
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    3rdParty.cmake
    3rdPartyPackages.cmake
    CMakeFiles.cmake
    CommandExecution.cmake
    Configurations.cmake
    Dependencies.cmake
    Deployment.cmake
    EngineJson.cmake
    FileUtil.cmake
    Findo3de.cmake
    Gems.cmake
    GeneralSettings.cmake
    Install.cmake
    LyAutoGen.cmake
    LYPackage_S3Downloader.cmake
    LySet.cmake
    LYTestWrappers.cmake
    LYPython.cmake
    LYWrappers.cmake
    Monolithic.cmake
    OutputDirectory.cmake
    Packaging.cmake
    PAL.cmake
    PALTools.cmake
    Projects.cmake
    run_epbtest.cmake
    RuntimeDependencies.cmake
    SettingsRegistry.cmake
    UnitTest.cmake
    Version.cmake
)
