#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#

# Generated by O3DE

include(FindPackageHandleStandardArgs)

ly_add_target(

NAME @NAME_PLACEHOLDER@ UNKNOWN IMPORTED

@NAMESPACE_PLACEHOLDER@

@INCLUDE_DIRECTORIES_PLACEHOLDER@

@BUILD_DEPENDENCIES_PLACEHOLDER@

@RUNTIME_DEPENDENCIES_PLACEHOLDER@

@COMPILE_DEFINITIONS_PLACEHOLDER@
)

# The below if was generated from if (NOT HEADER_ONLY_PLACEHOLDER)
# HEADER_ONLY_PLACEHOLDER evaluates to TRUE or FALSE
if (NOT @HEADER_ONLY_PLACEHOLDER@)
    # Load information for each installed configuration.
    foreach(config @ALL_CONFIGS@)
        set(@NAME_PLACEHOLDER@_${config}_FOUND FALSE)
        include("${LY_ROOT_FOLDER}/cmake_autogen/@NAME_PLACEHOLDER@/@NAME_PLACEHOLDER@_${config}.cmake")
    endforeach()

    find_package_handle_standard_args(@NAME_PLACEHOLDER@
        "Could not find package @NAME_PLACEHOLDER@"
        @TARGET_CONFIG_FOUND_VARS_PLACEHOLDER@)
else()
    set(@NAME_PLACEHOLDER@_FOUND TRUE)
endif()