#
# All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
# its licensors.
#
# For complete copyright and license terms please see the LICENSE at the root of this
# distribution (the "License"). All use of this software is governed by the License,
# or, if provided, by the license below or the license accompanying this file. Do not
# remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#

set(FILES
    Cry3DEngine_precompiled.cpp
    Cry3DEngineTraits.h
    3dEngineLoad.cpp
    VolumeObjectDataCreate.cpp
    VolumeObjectRenderNode.cpp
    VolumeObjectDataCreate.h
    VolumeObjectRenderNode.h
    Ocean.cpp
    WaterVolumeRenderNode.cpp
    Ocean.h
    WaterVolumeRenderNode.h
    Environment/OceanEnvironmentBus.h
    StatObjPhys.cpp
    StatObjRend.cpp
    StatObjStream.cpp
    IndexedMesh.cpp
    StatObjConstr.cpp
    StatObjLoad.cpp
    StatObj_Jobs.cpp
    IndexedMesh.h
    StatObj.h
    ObjMan.cpp
    ObjManDraw.cpp
    ObjManDrawEntity.cpp
    ObjManShadows.cpp
    ObjManStreaming.cpp
    ObjMan.h
    ObjectsTree.cpp
    ObjectsTree_MT.cpp
    ObjectsTree_Jobs.cpp
    ObjectsTree_Serialize.cpp
    ObjectsTree.h
    ObjectsTree_Serialize_info.h
    cbuffer.h
    cbuffer.cpp
    CCullRenderer.cpp
    CCullRenderer.h
    CCullThread.cpp
    CCullThread.h
    CullBuffer.cpp
    CullBuffer.h
    CZBufferCuller.cpp
    CZBufferCuller.h
    VMath.hpp
    VMath_C.hpp
    VMath_NEON.hpp
    VMath_Prototypes.hpp
    VMath_SSE.hpp
    LightEntity.cpp
    LightEntity.h
    Material_Jobs.cpp
    MaterialHelpers.cpp
    MaterialHelpers.h
    Material.cpp
    Material.h
    MatMan.cpp
    MatMan.h
    SurfaceTypeManager.cpp
    SurfaceTypeManager.h
    PostProcessEffects.cpp
    RenderMeshMerger.cpp
    RenderMeshUtils.cpp
    RenderMeshMerger.h
    RenderMeshUtils.h
    SkyLightManager.cpp
    SkyLightNishita.cpp
    TimeOfDay.cpp
    SkyLightManager.h
    SkyLightNishita.h
    SkyLightNishita_info.h
    TimeOfDay.h
    EnvironmentPreset.h
    EnvironmentPreset.cpp
    ShadowCache.cpp
    ShadowCache.h
    PostEffectGroup.cpp
    PostEffectGroup.h
    VisAreaMan.cpp
    VisAreaCompile.cpp
    VisAreas.cpp
    VisAreaManCompile.cpp
    VisArea_Jobs.cpp
    BasicArea.cpp
    BasicArea.h
    VisAreaCompile_info.h
    VisAreas.h
    GeomCachePredictors.h
    DeferredCollisionEvent.cpp
    3DEngineMemory.cpp
    3DEngineMemory.h
    Cry3DEngineBase.cpp
    Cry3DEngineBase.h
    DeferredCollisionEvent.h
    resource.h
    Cry3DEngine_precompiled.h
    3dEngine.cpp
    3dEngine.h
    3dEngineOctreeCompile.cpp
    3DEngine_Jobs.cpp
    3DEngineLight.cpp
    3DEngineRender.cpp
    ClipVolume.cpp
    ClipVolume.h
    ClipVolumeManager.cpp
    ClipVolumeManager.h
    cvars.cpp
    cvars.h
    CloudRenderNode.cpp
    CloudsManager.cpp
    DistanceCloudRenderNode.cpp
    CloudRenderNode.h
    CloudsManager.h
    Cry_LegacyPhysUtils.h
    DistanceCloudRenderNode.h
    Decal.cpp
    DecalManager.cpp
    DecalRenderNode.cpp
    DecalManager.h
    DecalRenderNode.h
    FogVolumeRenderNode.cpp
    FogVolumeRenderNode_Jobs.cpp
    FogVolumeRenderNode.h
    PrismRenderNode.cpp
    PrismRenderNode.h
    OpticsManager.cpp
    OpticsManager.h
    GeomCache.cpp
    GeomCache.h
    GeomCacheRenderNode.cpp
    GeomCacheRenderNode.h
    GeomCacheManager.cpp
    GeomCacheManager.h
    GeomCacheDecoder.cpp
    GeomCacheDecoder.h
    GeomCacheMeshManager.h
    GeomCacheMeshManager.cpp
    Cry_LegacyPhysUtils.h
    Cry_LegacyPhysUtils.cpp
)
