#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

cmake_policy(SET CMP0012 NEW) # new policy for the if that evaluates a boolean out of "if(NOT ${same_location})"

function(ly_copy source_file target_directory)
    get_filename_component(target_filename "${source_file}" NAME)
    cmake_path(COMPARE "${source_file}" EQUAL "${target_directory}/${target_filename}" same_location)
    if(NOT ${same_location})
        file(LOCK ${target_directory}/${target_filename}.lock GUARD FUNCTION TIMEOUT 300)
        if("${source_file}" IS_NEWER_THAN "${target_directory}/${target_filename}")
            message(STATUS "Copying \"${source_file}\" to \"${target_directory}\"...")
            file(COPY "${source_file}" DESTINATION "${target_directory}" FILE_PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE FOLLOW_SYMLINK_CHAIN)
            file(TOUCH_NOCREATE ${target_directory}/${target_filename})
        endif()
    endif()    
endfunction()

ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_ar.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_bg.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_ca.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_cs.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_da.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_de.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_en.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_es.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_fa.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_fi.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_fr.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_gd.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_gl.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_he.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_ar.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_bg.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_ca.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_cs.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_da.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_de.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_en.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_es.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_fr.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_gl.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_hu.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_it.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_ja.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_ko.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_pl.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_ru.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_sk.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_sl.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_tr.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_uk.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_zh_CN.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_help_zh_TW.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_hu.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_it.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_ja.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_ko.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_lt.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_lv.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_pl.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_pt.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_ru.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_sk.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_sl.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_sv.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_tr.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_uk.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_zh_CN.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/translations/qt_zh_TW.qm" "C:/Users/lesaelr/o3de/bin/release/translations")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Core.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/iconengines/qsvgicon.dll" "C:/Users/lesaelr/o3de/bin/release/iconengines")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qgif.dll" "C:/Users/lesaelr/o3de/bin/release/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qicns.dll" "C:/Users/lesaelr/o3de/bin/release/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qico.dll" "C:/Users/lesaelr/o3de/bin/release/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qjpeg.dll" "C:/Users/lesaelr/o3de/bin/release/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qsvg.dll" "C:/Users/lesaelr/o3de/bin/release/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qtga.dll" "C:/Users/lesaelr/o3de/bin/release/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qtiff.dll" "C:/Users/lesaelr/o3de/bin/release/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qwbmp.dll" "C:/Users/lesaelr/o3de/bin/release/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/imageformats/qwebp.dll" "C:/Users/lesaelr/o3de/bin/release/imageformats")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/platforms/qminimal.dll" "C:/Users/lesaelr/o3de/bin/release/platforms")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/platforms/qwindows.dll" "C:/Users/lesaelr/o3de/bin/release/platforms")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Gui.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/styles/qwindowsvistastyle.dll" "C:/Users/lesaelr/o3de/bin/release/styles")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Widgets.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Svg.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Xml.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/plugins/bearer/qgenericbearer.dll" "C:/Users/lesaelr/o3de/bin/release/bearer")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Network.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/python/runtime/python-3.7.10-rev2-windows/python/python37.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/python/runtime/python-3.7.10-rev2-windows/python/python3.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/python/runtime/python-3.7.10-rev2-windows/python/python37.pdb" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/python/runtime/python-3.7.10-rev2-windows/python/python3.pdb" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/boost_filesystem-vc141-mt-x64-1_73.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/boost_thread-vc141-mt-x64-1_73.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/Half-2_5.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/heif.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/Iex-2_5.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/IlmImf-2_5.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/IlmThread-2_5.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/Imath-2_5.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/jpeg62.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/lzma.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/libpng16.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/tiff.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/zlib1.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/yaml-cpp.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/OpenColorIO.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/OpenImageIO.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/OpenImageIO.pyd" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/OpenImageIO_Util.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/iconvert.exe" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/idiff.exe" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/igrep.exe" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/iinfo.exe" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/maketx.exe" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/openimageio-2.1.16.0-rev2-windows/OpenImageIO/2.1.16.0/win_x64/bin/oiiotool.exe" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/ImGui.imguilib.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/AzQtComponents.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/EditorCore.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/Atom_RHI_DX12.Builders.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/Atom_RHI_DX12.Private.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/Atom_RHI_Metal.Builders.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/Atom_RHI_Metal.Private.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/Atom_RHI_Vulkan.Builders.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/Atom_RHI_Vulkan.Private.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/Atom_Feature_Common.Editor.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/Atom_RHI.Private.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/Atom_RPI.Editor.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/EditorCommon.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/AtomLyIntegration_CommonFeatures.Editor.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/lrelease.exe" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Core.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/LmbrCentral.Editor.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/GradientSignal.Editor.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/Camera.Editor.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/AtomToolsFramework.Editor.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/EditorPythonBindings.Editor.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Test.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/.o3de/3rdParty/packages/qt-5.15.2-rev4-windows/qt/bin/Qt5Test.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/QtForPython.Editor.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/Maestro.Editor.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/SceneCore.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/SceneData.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/SceneUI.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/SceneProcessing.Editor.dll" "C:/Users/lesaelr/o3de/bin/release")
ly_copy("C:/Users/lesaelr/o3de/bin/release/Registry/cmake_dependencies.shadermanagementconsole.setreg" "C:/Users/lesaelr/o3de/bin/release/Registry")


file(TOUCH C:/Users/lesaelr/o3de/runtime_dependencies/release/ShaderManagementConsole_release.stamp)
