#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    base.h
    Asset/AssetInternal/WeakAsset.h
    Asset/AssetCommon.cpp
    Asset/AssetCommon.h
    Asset/AssetContainer.cpp
    Asset/AssetContainer.h
    Asset/AssetDataStream.cpp
    Asset/AssetDataStream.h
    Asset/AssetJsonSerializer.cpp
    Asset/AssetJsonSerializer.h
    Asset/AssetManager_private.h
    Asset/AssetManager.cpp
    Asset/AssetManager.h
    Asset/AssetManagerBus.cpp
    Asset/AssetManagerBus.h
    Asset/AssetManagerComponent.cpp
    Asset/AssetManagerComponent.h
    Asset/AssetTypeInfoBus.cpp
    Asset/AssetTypeInfoBus.h
    Asset/AssetSerializer.cpp
    Asset/AssetSerializer.h
    Casting/lossy_cast.h
    Casting/numeric_cast.h
    Casting/numeric_cast_internal.h
    Component/Component.cpp
    Component/Component.h
    Component/ComponentBus.cpp
    Component/ComponentBus.h
    Component/Entity.cpp
    Component/Entity.h
    Component/EntityIdSerializer.cpp
    Component/EntityIdSerializer.h
    Component/EntitySerializer.cpp
    Component/EntitySerializer.h
    Component/EntityUtils.cpp
    Component/EntityUtils.h
    Component/NamedEntityId.cpp
    Component/NamedEntityId.h
    Component/TransformBus.cpp
    Component/TransformBus.h
    Console/ConsoleFunctor.cpp
    Console/ConsoleFunctor.h
    Console/ConsoleFunctor.inl
    Console/IConsole.h
    Console/IConsoleTypes.h
    Console/ILogger.h
    Date/DateFormat.cpp
    Date/DateFormat.h
    Debug/StackTracer.h
    Debug/Trace.cpp
    Debug/Trace.h
    Dependency/Dependency.h
    Dependency/Dependency.inl
    Dependency/Version.h
    Docs.h
    Debug/Budget.h
    Debug/Budget.cpp
    Debug/BudgetTracker.h
    Debug/BudgetTracker.cpp
    Debug/MemoryProfiler.h
    Debug/PerformanceCollector.h
    Debug/PerformanceCollector.cpp
    Debug/Profiler.cpp
    Debug/Profiler.h
    Debug/ProfilerBus.h
    Debug/ProfilerReflection.cpp
    Debug/ProfilerReflection.h
    Debug/Timer.h
    Debug/TraceMessageBus.cpp
    Debug/TraceMessageBus.h
    Debug/TraceReflection.cpp
    Debug/TraceReflection.h
    DOM/Backends/JSON/JsonSerializationUtils.cpp
    DOM/Backends/JSON/JsonSerializationUtils.h
    DOM/DomBackend.cpp
    DOM/DomBackend.h
    DOM/DomPath.cpp
    DOM/DomPath.h
    DOM/DomUtils.cpp
    DOM/DomUtils.h
    DOM/DomValue.cpp
    DOM/DomValue.h
    DOM/DomValueWriter.cpp
    DOM/DomValueWriter.h
    DOM/DomVisitor.cpp
    DOM/DomVisitor.h
    EBus/BusImpl.h
    EBus/EBus.h
    EBus/EBusEnvironment.cpp
    EBus/EBusSharedDispatchTraits.h
    EBus/Environment.h
    EBus/Event.h
    EBus/Event.inl
    EBus/EventSchedulerSystemComponent.cpp
    EBus/EventSchedulerSystemComponent.h
    EBus/IEventScheduler.h
    EBus/OrderedEvent.h
    EBus/OrderedEvent.inl
    EBus/Policies.h
    EBus/Results.h
    EBus/ScheduledEvent.cpp
    EBus/ScheduledEvent.h
    EBus/ScheduledEventHandle.cpp
    EBus/ScheduledEventHandle.h
    EBus/Internal/BusContainer.h
    EBus/Internal/CallstackEntry.h
    EBus/Internal/Debug.h
    EBus/Internal/Handlers.h
    EBus/Internal/StoragePolicies.h
    Instance/InstancePool.h
    Interface/Interface.h
    IO/CompressionBus.h
    IO/CompressionBus.cpp
    IO/FileIO.cpp
    IO/FileIO.h
    IO/FileReader.cpp
    IO/FileReader.h
    IO/OpenMode.h
    IO/OpenMode.cpp
    IO/Path/Path.cpp
    IO/Path/Path.h
    IO/Path/Path.inl
    IO/GenericStreams.cpp
    IO/GenericStreams.h
    IO/IStreamerTypes.h
    IO/IStreamerTypes.inl
    IO/IStreamerTypes.cpp
    IO/SystemFile.cpp
    IO/SystemFile.h
    IO/Streamer/FileRequest.h
    IO/Streamer/FileRequest.inl
    IO/Streamer/FileRequest.cpp
    IO/Streamer/RequestPath.h
    IO/Streamer/RequestPath.cpp
    IO/Streamer/Statistics.h
    IO/Streamer/Statistics.cpp
    IO/Streamer/StreamerContext.h
    IO/Streamer/StreamerContext.cpp
    JSON/rapidjson.h
    JSON/rapidjson.cpp
    Jobs/Job.cpp
    Jobs/Job.h
    Jobs/JobContext.cpp
    Jobs/JobContext.h
    Jobs/JobManager.cpp
    Jobs/JobManager.h
    Jobs/Internal/JobManagerBase.cpp
    Jobs/Internal/JobManagerBase.h
    Jobs/Internal/JobManagerWorkStealing.cpp
    Jobs/Internal/JobManagerWorkStealing.h
    Math/Aabb.cpp
    Math/Aabb.h
    Math/Aabb.inl
    Math/Color.cpp
    Math/Color.h
    Math/Color.inl
    Math/ColorSerializer.h
    Math/ColorSerializer.cpp
    Math/Crc.cpp
    Math/Crc.inl
    Math/Crc.h
    Math/Frustum.cpp
    Math/Frustum.h
    Math/Frustum.inl
    Math/MathReflection.cpp
    Math/MathReflection.h
    Math/MathScriptHelpers.cpp
    Math/MathScriptHelpers.h
    Math/Matrix3x3.cpp
    Math/Matrix3x3.h
    Math/Matrix3x3.inl
    Math/Matrix3x4.cpp
    Math/Matrix3x4.h
    Math/Matrix3x4.inl
    Math/Matrix4x4.cpp
    Math/Matrix4x4.h
    Math/Matrix4x4.inl
    Math/MatrixMxN.cpp
    Math/MatrixMxN.h
    Math/MatrixMxN.inl
    Math/MatrixUtils.h
    Math/MatrixUtils.cpp
    Math/Obb.cpp
    Math/Obb.h
    Math/Obb.inl
    Math/Plane.cpp
    Math/Plane.h
    Math/Plane.inl
    Math/Quaternion.cpp
    Math/Quaternion.inl
    Math/Quaternion.h
    Math/Sfmt.cpp
    Math/Sfmt.h
    Math/Transform.cpp
    Math/Transform.h
    Math/Transform.inl
    Math/TransformSerializer.cpp
    Math/TransformSerializer.h
    Math/Uuid.cpp
    Math/Uuid.h
    Math/Uuid.inl
    Math/UuidSerializer.h
    Math/UuidSerializer.cpp
    Math/Vector2.cpp
    Math/Vector2.h
    Math/Vector2.inl
    Math/Vector3.cpp
    Math/Vector3.h
    Math/Vector3.inl
    Math/VectorN.cpp
    Math/VectorN.h
    Math/VectorN.inl
    Math/Vector4.cpp
    Math/Vector4.h
    Math/Vector4.inl
    Math/MathMatrixSerializer.h
    Math/MathMatrixSerializer.cpp
    Math/MathVectorSerializer.h
    Math/MathVectorSerializer.cpp
    Memory/AllocationRecords.cpp
    Memory/AllocationRecords.h
    Memory/AllocatorBase.cpp
    Memory/AllocatorBase.h
    Memory/AllocatorInstance.h
    Memory/AllocatorManager.cpp
    Memory/AllocatorManager.h
    Memory/AllocatorTrackingRecorder.cpp
    Memory/AllocatorTrackingRecorder.h
    Memory/AllocatorWrapper.h
    Memory/ChildAllocatorSchema.h
    Memory/Config.h
    Memory/dlmalloc.inl
    Memory/HphaAllocator.cpp
    Memory/HphaAllocator.h
    Memory/IAllocator.h
    Memory/Memory_fwd.h
    Memory/Memory.cpp
    Memory/Memory.h
    Memory/nedmalloc.inl
    Memory/NewAndDelete.inl
    Memory/OSAllocator.cpp
    Memory/OSAllocator.h
    Memory/PoolAllocator.cpp
    Memory/PoolAllocator.h
    Memory/SimpleSchemaAllocator.h
    Memory/SystemAllocator.cpp
    Memory/SystemAllocator.h
    Name/Name.h
    Name/Name.cpp
    Name/Internal/NameData.h
    Name/Internal/NameData.cpp
    Name/NameDictionary.h
    Name/NameDictionary.cpp
    Name/NameJsonSerializer.h
    Name/NameJsonSerializer.cpp
    Name/NameSerializer.h
    Name/NameSerializer.cpp
    Outcome/Outcome.h
    Outcome/Internal/OutcomeImpl.h
    Platform.cpp
    Platform.h
    PlatformDef.h
    PlatformIncl.h
    Preprocessor/Enum.h
    Preprocessor/EnumReflectUtils.h
    Preprocessor/Sequences.h
    RTTI/AttributeReader.h
    RTTI/AzStdOnDemandPrettyName.inl
    RTTI/AzStdOnDemandReflection.inl
    RTTI/AzStdOnDemandReflectionSpecializations.cpp
    RTTI/AzStdOnDemandReflectionLuaFunctions.inl
    RTTI/BehaviorClassBuilder.cpp
    RTTI/BehaviorClassBuilder.inl
    RTTI/BehaviorContext.cpp
    RTTI/BehaviorContext.h
    RTTI/BehaviorContextUtilities.cpp
    RTTI/BehaviorContextUtilities.h
    RTTI/BehaviorEBusBuilder.cpp
    RTTI/BehaviorEBusBuilder.inl
    RTTI/BehaviorEBusEvent.cpp
    RTTI/BehaviorEBusEvent.inl
    RTTI/BehaviorEBusHandler.cpp
    RTTI/BehaviorEBusHandler.inl
    RTTI/BehaviorInterfaceProxy.h
    RTTI/BehaviorMethodImpl.cpp
    RTTI/BehaviorMethodImpl.inl
    RTTI/BehaviorObjectSignals.h
    RTTI/ChronoReflection.cpp
    RTTI/ChronoReflection.h
    RTTI/ReflectContext.h
    RTTI/ReflectContext.cpp
    RTTI/ReflectionManager.h
    RTTI/ReflectionManager.cpp
    RTTI/RTTI.h
    RTTI/RTTIMacros.h
    RTTI/TemplateInfo.h
    RTTI/TypeInfo.h
    RTTI/TypeInfo.cpp
    RTTI/TypeInfoSimple.h
    RTTI/TypeSafeIntegral.h
    Script/ScriptContext.h
    Script/ScriptContext.cpp
    Script/ScriptContextDebug.cpp
    Script/ScriptContextDebug.h
    Script/ScriptProperty.h
    Script/ScriptProperty.cpp
    Script/ScriptPropertyTable.h
    Script/ScriptPropertyTable.cpp
    ScriptCanvas/ScriptCanvasOnDemandNames.cpp
    ScriptCanvas/ScriptCanvasOnDemandNames.h
    Serialization/DataOverlay.h
    Serialization/DataOverlayInstanceMsgs.h
    Serialization/DataOverlayProviderMsgs.cpp
    Serialization/DataOverlayProviderMsgs.h
    Serialization/AZStdContainers.inl
    Serialization/AZStdAnyDataContainer.inl
    Serialization/DynamicSerializableField.cpp
    Serialization/DynamicSerializableField.h
    Serialization/EnumConstantJsonSerializer.cpp
    Serialization/EnumConstantJsonSerializer.h
    Serialization/EditContext.cpp
    Serialization/EditContext.h
    Serialization/EditContext.inl
    Serialization/EditContextConstants.inl
    Serialization/IdUtils.inl
    Serialization/IdUtils.h
    Serialization/Locale.h
    Serialization/Locale.cpp
    Serialization/Utils.h
    Serialization/SerializationUtils.cpp
    Serialization/ObjectStream.cpp
    Serialization/ObjectStream.h
    Serialization/PointerObject.h
    Serialization/PointerObject.cpp
    Serialization/SerializeContext.cpp
    Serialization/SerializeContext.h
    Serialization/SerializeContext_fwd.h
    Serialization/SerializeContextEnum.cpp
    Serialization/SerializeContextEnum.inl
    Serialization/DataPatch.h
    Serialization/DataPatch.cpp
    Serialization/DataPatchBus.h
    Serialization/DataPatchUpgradeManager.h
    Serialization/DataPatchUpgradeManager.cpp
    Serialization/Json/AnySerializer.h
    Serialization/Json/AnySerializer.cpp
    Serialization/Json/ArraySerializer.h
    Serialization/Json/ArraySerializer.cpp
    Serialization/Json/BaseJsonSerializer.h
    Serialization/Json/BaseJsonSerializer.cpp
    Serialization/Json/BasicContainerSerializer.h
    Serialization/Json/BasicContainerSerializer.cpp
    Serialization/Json/BoolSerializer.h
    Serialization/Json/BoolSerializer.cpp
    Serialization/Json/ByteStreamSerializer.h
    Serialization/Json/CastingHelpers.h
    Serialization/Json/DoubleSerializer.h
    Serialization/Json/DoubleSerializer.cpp
    Serialization/Json/IntSerializer.h
    Serialization/Json/IntSerializer.cpp
    Serialization/Json/JsonDeserializer.h
    Serialization/Json/JsonDeserializer.cpp
    Serialization/Json/JsonImporter.cpp
    Serialization/Json/JsonImporter.h
    Serialization/Json/JsonMerger.h
    Serialization/Json/JsonMerger.cpp
    Serialization/Json/JsonSerialization.h
    Serialization/Json/JsonSerialization.cpp
    Serialization/Json/JsonSerializationMetadata.h
    Serialization/Json/JsonSerializationMetadata.inl
    Serialization/Json/JsonSerializationResult.h
    Serialization/Json/JsonSerializationResult.cpp
    Serialization/Json/JsonSerializationSettings.h
    Serialization/Json/JsonSerializer.h
    Serialization/Json/JsonSerializer.cpp
    Serialization/Json/JsonStringConversionUtils.h
    Serialization/Json/JsonSystemComponent.h
    Serialization/Json/JsonSystemComponent.cpp
    Serialization/Json/JsonUtils.h
    Serialization/Json/JsonUtils.cpp
    Serialization/Json/MapSerializer.h
    Serialization/Json/MapSerializer.cpp
    Serialization/Json/PathSerializer.h
    Serialization/Json/PathSerializer.cpp
    Serialization/Json/PointerJsonSerializer.h
    Serialization/Json/PointerJsonSerializer.cpp
    Serialization/Json/RegistrationContext.h
    Serialization/Json/RegistrationContext.cpp
    Serialization/Json/SmartPointerSerializer.h
    Serialization/Json/SmartPointerSerializer.cpp
    Serialization/Json/StackedString.h
    Serialization/Json/StackedString.cpp
    Serialization/Json/StringSerializer.h
    Serialization/Json/StringSerializer.cpp
    Serialization/Json/TupleSerializer.h
    Serialization/Json/TupleSerializer.cpp
    Serialization/Json/UnorderedSetSerializer.h
    Serialization/Json/UnorderedSetSerializer.cpp
    Serialization/Json/UnsupportedTypesSerializer.h
    Serialization/Json/UnsupportedTypesSerializer.cpp
    Serialization/std/VariantReflection.inl
    Settings/ConfigurableStack.cpp
    Settings/ConfigurableStack.inl
    Settings/ConfigurableStack.h
    Statistics/RunningStatistic.cpp
    Statistics/RunningStatistic.h
    StringFunc/StringFunc.cpp
    StringFunc/StringFunc.h
    Utils/Utils.cpp
    Utils/Utils.h
)
