#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    AzCoreModule.h
    AzCoreModule.cpp
    Component/ComponentApplication.cpp
    Component/ComponentApplication.h
    Component/ComponentApplicationBus.cpp
    Component/ComponentApplicationBus.h
    Component/ComponentApplicationLifecycle.cpp
    Component/ComponentApplicationLifecycle.h
    Component/ComponentExport.h
    Component/EntityBus.h
    Component/EntityId.h
    Component/NonUniformScaleBus.cpp
    Component/NonUniformScaleBus.h
    Component/TickBus.cpp
    Component/TickBus.h
    Compression/compression.cpp
    Compression/Compression.h
    Compression/zstd_compression.cpp
    Compression/zstd_compression.h
    Console/Console.cpp
    Console/Console.h
    Console/ConsoleDataWrapper.h
    Console/ConsoleDataWrapper.inl
    Console/ConsoleTypeHelpers.h
    Console/ConsoleTypeHelpers.inl
    Console/LoggerSystemComponent.cpp
    Console/LoggerSystemComponent.h
    DOM/DomPatch.cpp
    DOM/DomPatch.h
    DOM/DomComparison.cpp
    DOM/DomComparison.h
    DOM/DomPrefixTree.h
    DOM/DomPrefixTree.inl
    DOM/Backends/JSON/JsonBackend.h
    IO/AnsiTerminalUtils.cpp
    IO/AnsiTerminalUtils.h
    IO/ByteContainerStream.h
    IO/Compressor.cpp
    IO/Compressor.h
    IO/CompressorStream.cpp
    IO/CompressorStream.h
    IO/CompressorZLib.cpp
    IO/CompressorZLib.h
    IO/CompressorZStd.cpp
    IO/CompressorZStd.h
    IO/IOUtils.cpp
    IO/IOUtils.h
    IO/IStreamer.h
    IO/IStreamerProfiler.h
    IO/Path/PathIterable.inl
    IO/Path/PathParser.inl
    IO/Path/PathReflect.cpp
    IO/Path/PathReflect.h
    IO/Path/Path_fwd.h
    IO/TextStreamWriters.h
    IO/Streamer/BlockCache.cpp
    IO/Streamer/BlockCache.h
    IO/Streamer/DedicatedCache.cpp
    IO/Streamer/DedicatedCache.h
    IO/Streamer/StorageDrive.cpp
    IO/Streamer/StorageDrive.h
    IO/Streamer/FileRange.h
    IO/Streamer/FileRange.cpp
    IO/Streamer/FullFileDecompressor.h
    IO/Streamer/FullFileDecompressor.cpp
    IO/Streamer/ReadSplitter.h
    IO/Streamer/ReadSplitter.cpp
    IO/Streamer/Scheduler.h
    IO/Streamer/Scheduler.cpp
    IO/Streamer/StreamerConfiguration.h
    IO/Streamer/StreamerConfiguration.cpp
    IO/Streamer/Streamer.cpp
    IO/Streamer/Streamer.h
    IO/Streamer/StreamerComponent.cpp
    IO/Streamer/StreamerComponent.h
    IO/Streamer/StreamStackEntry.h
    IO/Streamer/StreamStackEntry.cpp
    IPC/SharedMemory.cpp
    IPC/SharedMemory.h
    Jobs/Algorithms.h
    Jobs/Internal/JobNotify.h
    Jobs/JobCancelGroup.h
    Jobs/JobCompletion.h
    Jobs/JobCompletionSpin.h
    Jobs/JobEmpty.h
    Jobs/JobFunction.h
    Jobs/JobManagerBus.cpp
    Jobs/JobManagerBus.h
    Jobs/JobManagerComponent.cpp
    Jobs/JobManagerComponent.h
    Jobs/JobManagerDesc.h
    Jobs/MultipleDependentJob.h
    Jobs/task_group.h
    JSON/allocators.h
    JSON/cursorstreamwrapper.h
    JSON/document.h
    JSON/encodedstream.h
    JSON/encodings.h
    JSON/filereadstream.h
    JSON/filewritestream.h
    JSON/fwd.h
    JSON/istreamwrapper.h
    JSON/memorybuffer.h
    JSON/memorystream.h
    JSON/ostreamwrapper.h
    JSON/pointer.h
    JSON/prettywriter.h
    JSON/RapidJsonAllocator.h
    JSON/RapidjsonAllocatorAdapter.h
    JSON/reader.h
    JSON/schema.h
    JSON/stream.h
    JSON/stringbuffer.h
    JSON/writer.h
    JSON/error/en.h
    JSON/error/error.h
    Math/Capsule.h
    Math/Capsule.inl
    Math/DocsMath.h
    Math/Geometry2DUtils.cpp
    Math/Geometry2DUtils.h
    Math/Geometry3DUtils.cpp
    Math/Geometry3DUtils.h
    Math/Guid.h
    Math/Hemisphere.h
    Math/Hemisphere.inl
    Math/Internal/MathTypes.h
    Math/Internal/SimdMathVec1_neon.inl
    Math/Internal/SimdMathVec1_scalar.inl
    Math/Internal/SimdMathVec1_sse.inl
    Math/Internal/SimdMathVec2_neon.inl
    Math/Internal/SimdMathVec2_scalar.inl
    Math/Internal/SimdMathVec2_sse.inl
    Math/Internal/SimdMathVec3_neon.inl
    Math/Internal/SimdMathVec3_scalar.inl
    Math/Internal/SimdMathVec3_sse.inl
    Math/Internal/SimdMathVec4_neon.inl
    Math/Internal/SimdMathVec4_scalar.inl
    Math/Internal/SimdMathVec4_sse.inl
    Math/Internal/SimdMathCommon_neon.inl
    Math/Internal/SimdMathCommon_neonDouble.inl
    Math/Internal/SimdMathCommon_neonQuad.inl
    Math/Internal/SimdMathCommon_simd.inl
    Math/Internal/SimdMathCommon_sse.inl
    Math/Internal/VectorConversions.inl
    Math/Internal/VertexContainer.inl
    Math/InterpolationSample.h
    Math/IntersectPoint.h
    Math/IntersectSegment.inl
    Math/IntersectSegment.cpp
    Math/IntersectSegment.h
    Math/LineSegment.cpp
    Math/LineSegment.h
    Math/MathIntrinsics.h
    Math/MathUtils.cpp
    Math/MathUtils.h
    Math/MathStringConversions.h
    Math/MathStringConversions.cpp
    Math/PolygonPrism.h
    Math/PolygonPrism.cpp
    Math/Random.h
    Math/Ray.cpp
    Math/Ray.h
    Math/ShapeIntersection.cpp
    Math/ShapeIntersection.h
    Math/ShapeIntersection.inl
    Math/SimdMath.h
    Math/SimdMathVec1.h
    Math/SimdMathVec2.h
    Math/SimdMathVec3.h
    Math/SimdMathVec4.h
    Math/Sha1.h
    Math/Spline.cpp
    Math/Spline.h
    Math/Sphere.h
    Math/Sphere.inl
    Math/VectorConversions.h
    Math/VertexContainer.h
    Math/VertexContainer.cpp
    Math/VertexContainerInterface.h
    Math/PackedVector2.h
    Math/PackedVector3.h
    Math/PackedVector4.h
    Metrics/EventLoggerFactoryImpl.h
    Metrics/EventLoggerFactoryImpl.cpp
    Metrics/EventLoggerReflectUtils.cpp
    Metrics/EventLoggerReflectUtils.h
    Metrics/EventLoggerUtils.cpp
    Metrics/EventLoggerUtils.h
    Metrics/JsonTraceEventLogger.h
    Metrics/JsonTraceEventLogger.cpp
    Metrics/IEventLogger.h
    Metrics/IEventLogger.cpp
    Metrics/IEventLogger.inl
    Metrics/IEventLoggerFactory.h
    Module/EBusInstantiations.cpp
    Module/AZStdInstantiations.cpp
    Module/DynamicModuleHandle.cpp
    Module/DynamicModuleHandle.h
    Module/Module.cpp
    Module/Module.h
    Module/ModuleManagerBus.cpp
    Module/ModuleManagerBus.h
    Module/ModuleManager.cpp
    Module/ModuleManager.h
    Module/Internal/ModuleManagerSearchPathTool.h
    Module/Internal/ModuleManagerSearchPathTool.cpp
    NativeUI/NativeUISystemComponent.cpp
    NativeUI/NativeUISystemComponent.h
    NativeUI/NativeUIRequests.cpp
    NativeUI/NativeUIRequests.h
    PlatformId/PlatformDefaults.h
    PlatformId/PlatformDefaults.cpp
    PlatformId/PlatformId.h
    PlatformId/PlatformId.cpp
    Process/ProcessInfo.h
    Script/lua/lua.h
    Script/ScriptAsset.cpp
    Script/ScriptAsset.h
    Script/ScriptContextAttributes.h
    Script/ScriptSystemBus.cpp
    Script/ScriptSystemBus.h
    Script/ScriptSystemComponent.cpp
    Script/ScriptSystemComponent.h
    Script/ScriptTimePoint.cpp
    Script/ScriptTimePoint.h
    Script/ScriptPropertySerializer.h
    Script/ScriptPropertySerializer.cpp
    Script/ScriptPropertyWatcherBus.cpp
    Script/ScriptPropertyWatcherBus.h
    Script/ScriptDebug.cpp
    Script/ScriptDebug.h
    ScriptCanvas/ScriptCanvasAttributes.h
    Settings/CommandLine.cpp
    Settings/CommandLine.h
    Settings/CommandLineParser.cpp
    Settings/CommandLineParser.h
    Settings/ConfigParser.cpp
    Settings/ConfigParser.h
    Settings/SettingsRegistry.cpp
    Settings/SettingsRegistry.h
    Settings/SettingsRegistryConsoleUtils.cpp
    Settings/SettingsRegistryConsoleUtils.h
    Settings/SettingsRegistryImpl.cpp
    Settings/SettingsRegistryImpl.h
    Settings/SettingsRegistryMergeUtils.cpp
    Settings/SettingsRegistryMergeUtils.h
    Settings/SettingsRegistryOriginTracker.cpp
    Settings/SettingsRegistryOriginTracker.h
    Settings/SettingsRegistryScriptUtils.cpp
    Settings/SettingsRegistryScriptUtils.h
    Settings/SettingsRegistryVisitorUtils.cpp
    Settings/SettingsRegistryVisitorUtils.h
    Settings/TextParser.cpp
    Settings/TextParser.h
    Slice/SliceAsset.cpp
    Slice/SliceAsset.h
    Slice/SliceAssetHandler.cpp
    Slice/SliceAssetHandler.h
    Slice/SliceBus.cpp
    Slice/SliceBus.h
    Slice/SliceComponent.cpp
    Slice/SliceComponent.h
    Slice/SliceSystemComponent.h
    Slice/SliceSystemComponent.cpp
    Slice/SliceMetadataInfoBus.cpp
    Slice/SliceMetadataInfoBus.h
    Slice/SliceMetadataInfoComponent.h
    Slice/SliceMetadataInfoComponent.cpp
    Socket/AzSocket_fwd.h
    Socket/AzSocket.cpp
    Socket/AzSocket.h
    State/HSM.cpp
    State/HSM.h
    Statistics/NamedRunningStatistic.h
    Statistics/StatisticalProfiler.h
    Statistics/StatisticalProfilerProxy.h
    Statistics/StatisticalProfilerProxySystemComponent.cpp
    Statistics/StatisticalProfilerProxySystemComponent.h
    Statistics/StatisticsManager.h
    Task/Internal/Task.cpp
    Task/Internal/Task.inl
    Task/Internal/Task.h
    Task/Internal/TaskConfig.h
    Task/TaskDescriptor.h
    Task/TaskExecutor.cpp
    Task/TaskExecutor.h
    Task/TaskGraph.cpp
    Task/TaskGraph.h
    Task/TaskGraph.inl
    Task/TaskGraphSystemComponent.h
    Task/TaskGraphSystemComponent.cpp
    Threading/ThreadSafeDeque.h
    Threading/ThreadSafeDeque.inl
    Threading/ThreadSafeObject.h
    Threading/ThreadSafeObject.inl
    Threading/ThreadUtils.h
    Threading/ThreadUtils.cpp
    Time/ITime.h
    Time/TimeSystem.cpp
    Time/TimeSystem.h
    UserSettings/UserSettings.cpp
    UserSettings/UserSettings.h
    UserSettings/UserSettingsComponent.cpp
    UserSettings/UserSettingsComponent.h
    UserSettings/UserSettingsProvider.cpp
    UserSettings/UserSettingsProvider.h
    Utils/TypeHash.cpp
    Utils/TypeHash.h
    variadic.h
    XML/rapidxml.h
    XML/rapidxml_iterators.h
    XML/rapidxml_print.h
    XML/rapidxml_utils.h
)
