#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Asset/AssetInternal/WeakAsset.h
    Asset/AssetCommon.cpp
    Asset/AssetCommon.h
    Asset/AssetContainer.cpp
    Asset/AssetContainer.h
    Asset/AssetDataStream.cpp
    Asset/AssetDataStream.h
    Asset/AssetJsonSerializer.cpp
    Asset/AssetJsonSerializer.h
    Asset/AssetManager_private.h
    Asset/AssetManager.cpp
    Asset/AssetManager.h
    Asset/AssetManagerBus.cpp
    Asset/AssetManagerBus.h
    Asset/AssetManagerComponent.cpp
    Asset/AssetManagerComponent.h
    Asset/AssetSerializer.cpp
    Asset/AssetSerializer.h
    Asset/AssetTypeInfoBus.cpp
    Asset/AssetTypeInfoBus.h
    Component/ComponentApplication.cpp
    Component/ComponentApplication.h
    Component/ComponentApplicationBus.h
    Component/ComponentApplicationLifecycle.cpp
    Component/ComponentApplicationLifecycle.h
    Component/ComponentBus.cpp
    Component/ComponentBus.h
    Component/ComponentExport.h
    Component/Entity.cpp
    Component/Entity.h
    Component/EntityBus.h
    Component/EntityId.h
    Component/EntityIdSerializer.cpp
    Component/EntityIdSerializer.h
    Component/EntitySerializer.cpp
    Component/EntitySerializer.h
    Component/EntityUtils.cpp
    Component/EntityUtils.h
    Component/NamedEntityId.cpp
    Component/NamedEntityId.h
    Component/NonUniformScaleBus.cpp
    Component/NonUniformScaleBus.h
    Component/TickBus.h
    Component/TransformBus.h
    Compression/compression.cpp
    Compression/Compression.h
    Compression/zstd_compression.cpp
    Compression/zstd_compression.h
    Console/Console.cpp
    Console/Console.h
    Console/ConsoleDataWrapper.h
    Console/ConsoleDataWrapper.inl
    Console/ConsoleFunctor.cpp
    Console/ConsoleFunctor.h
    Console/ConsoleFunctor.inl
    Console/ConsoleTypeHelpers.h
    Console/ConsoleTypeHelpers.inl
    Console/IConsole.h
    Console/IConsoleTypes.h
    Console/ILogger.h
    Console/LoggerSystemComponent.cpp
    Console/LoggerSystemComponent.h
    Date/DateFormat.cpp
    Date/DateFormat.h
    Debug/Budget.h
    Debug/Budget.cpp
    Debug/BudgetTracker.h
    Debug/BudgetTracker.cpp
    Debug/MemoryProfiler.h
    Debug/PerformanceCollector.h
    Debug/PerformanceCollector.cpp
    Debug/Profiler.cpp
    Debug/Profiler.h
    Debug/ProfilerBus.h
    Debug/ProfilerReflection.cpp
    Debug/ProfilerReflection.h
    Debug/Timer.h
    Debug/TraceMessageBus.h
    Debug/TraceReflection.cpp
    Debug/TraceReflection.h
    DOM/DomBackend.cpp
    DOM/DomBackend.h
    DOM/DomPatch.cpp
    DOM/DomPatch.h
    DOM/DomPath.cpp
    DOM/DomPath.h
    DOM/DomUtils.cpp
    DOM/DomUtils.h
    DOM/DomValue.cpp
    DOM/DomValue.h
    DOM/DomVisitor.cpp
    DOM/DomVisitor.h
    DOM/DomComparison.cpp
    DOM/DomComparison.h
    DOM/DomPrefixTree.h
    DOM/DomPrefixTree.inl
    DOM/Backends/JSON/JsonBackend.h
    IO/AnsiTerminalUtils.cpp
    IO/AnsiTerminalUtils.h
    IO/ByteContainerStream.h
    IO/CompressionBus.h
    IO/CompressionBus.cpp
    IO/Compressor.cpp
    IO/Compressor.h
    IO/CompressorStream.cpp
    IO/CompressorStream.h
    IO/CompressorZLib.cpp
    IO/CompressorZLib.h
    IO/CompressorZStd.cpp
    IO/CompressorZStd.h
    IO/FileIO.cpp
    IO/FileIO.h
    IO/FileReader.cpp
    IO/FileReader.h
    IO/IOUtils.cpp
    IO/IOUtils.h
    IO/IStreamer.h
    IO/IStreamerProfiler.h
    IO/IStreamerTypes.h
    IO/IStreamerTypes.inl
    IO/IStreamerTypes.cpp
    IO/GenericStreams.cpp
    IO/GenericStreams.h
    IO/OpenMode.h
    IO/OpenMode.cpp
    IO/SystemFile.cpp
    IO/SystemFile.h
    IO/Path/Path.cpp
    IO/Path/Path.h
    IO/Path/Path.inl
    IO/Path/PathIterable.inl
    IO/Path/PathParser.inl
    IO/Path/PathReflect.cpp
    IO/Path/PathReflect.h
    IO/Path/Path_fwd.h
    IO/TextStreamWriters.h
    IO/Streamer/BlockCache.cpp
    IO/Streamer/BlockCache.h
    IO/Streamer/DedicatedCache.cpp
    IO/Streamer/DedicatedCache.h
    IO/Streamer/FileRequest.h
    IO/Streamer/FileRequest.inl
    IO/Streamer/FileRequest.cpp
    IO/Streamer/StorageDrive.cpp
    IO/Streamer/StorageDrive.h
    IO/Streamer/FileRange.h
    IO/Streamer/FileRange.cpp
    IO/Streamer/FullFileDecompressor.h
    IO/Streamer/FullFileDecompressor.cpp
    IO/Streamer/ReadSplitter.h
    IO/Streamer/ReadSplitter.cpp
    IO/Streamer/RequestPath.h
    IO/Streamer/RequestPath.cpp
    IO/Streamer/Scheduler.h
    IO/Streamer/Scheduler.cpp
    IO/Streamer/Statistics.h
    IO/Streamer/Statistics.cpp
    IO/Streamer/StreamerConfiguration.h
    IO/Streamer/StreamerConfiguration.cpp
    IO/Streamer/Streamer.cpp
    IO/Streamer/Streamer.h
    IO/Streamer/StreamerContext.h
    IO/Streamer/StreamerContext.cpp
    IO/Streamer/StreamerComponent.cpp
    IO/Streamer/StreamerComponent.h
    IO/Streamer/StreamStackEntry.h
    IO/Streamer/StreamStackEntry.cpp
    Jobs/Algorithms.h
    Jobs/Internal/JobManagerBase.cpp
    Jobs/Internal/JobManagerBase.h
    Jobs/Internal/JobManagerWorkStealing.cpp
    Jobs/Internal/JobManagerWorkStealing.h
    Jobs/Internal/JobNotify.h
    Jobs/Job.cpp
    Jobs/Job.h
    Jobs/JobCancelGroup.h
    Jobs/JobCompletion.h
    Jobs/JobCompletionSpin.h
    Jobs/JobContext.cpp
    Jobs/JobContext.h
    Jobs/JobEmpty.h
    Jobs/JobFunction.h
    Jobs/JobManager.cpp
    Jobs/JobManager.h
    Jobs/JobManagerBus.cpp
    Jobs/JobManagerBus.h
    Jobs/JobManagerComponent.cpp
    Jobs/JobManagerComponent.h
    Jobs/JobManagerDesc.h
    Jobs/MultipleDependentJob.h
    Jobs/task_group.h

    Module/EBusInstantiations.cpp
    Module/AZStdInstantiations.cpp

    Name/Name.h
    Name/Name.cpp
    Name/NameDictionary.h
    Name/NameDictionary.cpp
    Name/NameJsonSerializer.h
    Name/NameJsonSerializer.cpp
    Name/NameSerializer.h
    Name/NameSerializer.cpp
    Name/Internal/NameData.h
    Name/Internal/NameData.cpp
    Process/ProcessInfo.h
    Script/lua/lua.h
    Script/ScriptAsset.cpp
    Script/ScriptAsset.h
    Script/ScriptContext.h
    Script/ScriptContext.cpp
    Script/ScriptContextAttributes.h
    Script/ScriptContextDebug.cpp
    Script/ScriptContextDebug.h
    Script/ScriptSystemBus.cpp
    Script/ScriptSystemBus.h
    Script/ScriptSystemComponent.cpp
    Script/ScriptSystemComponent.h
    Script/ScriptTimePoint.cpp
    Script/ScriptTimePoint.h
    Script/ScriptPropertySerializer.h
    Script/ScriptPropertySerializer.cpp
    Script/ScriptPropertyTable.h
    Script/ScriptPropertyTable.cpp
    Script/ScriptPropertyWatcherBus.cpp
    Script/ScriptPropertyWatcherBus.h
    Script/ScriptDebug.cpp
    Script/ScriptDebug.h
    ScriptCanvas/ScriptCanvasAttributes.h
    ScriptCanvas/ScriptCanvasOnDemandNames.cpp
    ScriptCanvas/ScriptCanvasOnDemandNames.h
    Settings/CommandLine.cpp
    Settings/CommandLine.h
    Settings/CommandLineParser.cpp
    Settings/CommandLineParser.h
    Settings/ConfigParser.cpp
    Settings/ConfigParser.h
    Settings/ConfigurableStack.cpp
    Settings/ConfigurableStack.inl
    Settings/ConfigurableStack.h
    Settings/SettingsRegistry.cpp
    Settings/SettingsRegistry.h
    Settings/SettingsRegistryConsoleUtils.cpp
    Settings/SettingsRegistryConsoleUtils.h
    Settings/SettingsRegistryImpl.cpp
    Settings/SettingsRegistryImpl.h
    Settings/SettingsRegistryMergeUtils.cpp
    Settings/SettingsRegistryMergeUtils.h
    Settings/SettingsRegistryOriginTracker.cpp
    Settings/SettingsRegistryOriginTracker.h
    Settings/SettingsRegistryScriptUtils.cpp
    Settings/SettingsRegistryScriptUtils.h
    Settings/SettingsRegistryVisitorUtils.cpp
    Settings/SettingsRegistryVisitorUtils.h
    Settings/TextParser.cpp
    Settings/TextParser.h
    Slice/SliceAsset.cpp
    Slice/SliceAsset.h
    Slice/SliceAssetHandler.cpp
    Slice/SliceAssetHandler.h
    Slice/SliceBus.cpp
    Slice/SliceBus.h
    Slice/SliceComponent.cpp
    Slice/SliceComponent.h
    Slice/SliceSystemComponent.h
    Slice/SliceSystemComponent.cpp
    Slice/SliceMetadataInfoBus.cpp
    Slice/SliceMetadataInfoBus.h
    Slice/SliceMetadataInfoComponent.h
    Slice/SliceMetadataInfoComponent.cpp
    Socket/AzSocket_fwd.h
    Socket/AzSocket.cpp
    Socket/AzSocket.h
    State/HSM.cpp
    State/HSM.h
    Statistics/NamedRunningStatistic.h
    Statistics/RunningStatistic.cpp
    Statistics/RunningStatistic.h
    Statistics/StatisticalProfiler.h
    Statistics/StatisticalProfilerProxy.h
    Statistics/StatisticalProfilerProxySystemComponent.cpp
    Statistics/StatisticalProfilerProxySystemComponent.h
    Statistics/StatisticsManager.h
    StringFunc/StringFunc.cpp
    StringFunc/StringFunc.h
    Task/Internal/Task.cpp
    Task/Internal/Task.inl
    Task/Internal/Task.h
    Task/Internal/TaskConfig.h
    Task/TaskDescriptor.h
    Task/TaskExecutor.cpp
    Task/TaskExecutor.h
    Task/TaskGraph.cpp
    Task/TaskGraph.h
    Task/TaskGraph.inl
    Task/TaskGraphSystemComponent.h
    Task/TaskGraphSystemComponent.cpp
    Threading/ThreadSafeDeque.h
    Threading/ThreadSafeDeque.inl
    Threading/ThreadSafeObject.h
    Threading/ThreadSafeObject.inl
    Threading/ThreadUtils.h
    Threading/ThreadUtils.cpp
    Time/ITime.h
    Time/TimeSystem.cpp
    Time/TimeSystem.h
    UserSettings/UserSettings.cpp
    UserSettings/UserSettings.h
    UserSettings/UserSettingsComponent.cpp
    UserSettings/UserSettingsComponent.h
    UserSettings/UserSettingsProvider.cpp
    UserSettings/UserSettingsProvider.h
    Utils/TypeHash.cpp
    Utils/TypeHash.h
    Utils/Utils.cpp
    Utils/Utils.h
)
