#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Asset/AssetInternal/WeakAsset.h
    Asset/AssetCommon.cpp
    Asset/AssetCommon.h
    Asset/AssetContainer.cpp
    Asset/AssetContainer.h
    Asset/AssetDataStream.cpp
    Asset/AssetDataStream.h
    Asset/AssetJsonSerializer.cpp
    Asset/AssetJsonSerializer.h
    Asset/AssetManager_private.h
    Asset/AssetManager.cpp
    Asset/AssetManager.h
    Asset/AssetManagerBus.cpp
    Asset/AssetManagerBus.h
    Asset/AssetManagerComponent.cpp
    Asset/AssetManagerComponent.h
    Asset/AssetSerializer.cpp
    Asset/AssetSerializer.h
    Asset/AssetTypeInfoBus.cpp
    Asset/AssetTypeInfoBus.h
    Component/ComponentApplication.cpp
    Component/ComponentApplication.h
    Component/ComponentApplicationBus.h
    Component/ComponentApplicationLifecycle.cpp
    Component/ComponentApplicationLifecycle.h
    Component/ComponentBus.cpp
    Component/ComponentBus.h
    Component/ComponentExport.h
    Component/Entity.cpp
    Component/Entity.h
    Component/EntityBus.h
    Component/EntityId.h
    Component/EntityIdSerializer.cpp
    Component/EntityIdSerializer.h
    Component/EntitySerializer.cpp
    Component/EntitySerializer.h
    Component/EntityUtils.cpp
    Component/EntityUtils.h
    Component/NamedEntityId.cpp
    Component/NamedEntityId.h
    Component/NonUniformScaleBus.cpp
    Component/NonUniformScaleBus.h
    Component/TickBus.h
    Component/TransformBus.h
    Compression/compression.cpp
    Compression/Compression.h
    Compression/zstd_compression.cpp
    Compression/zstd_compression.h
    Console/Console.cpp
    Console/Console.h
    Console/ConsoleDataWrapper.h
    Console/ConsoleDataWrapper.inl
    Console/ConsoleFunctor.cpp
    Console/ConsoleFunctor.h
    Console/ConsoleFunctor.inl
    Console/ConsoleTypeHelpers.h
    Console/ConsoleTypeHelpers.inl
    Console/IConsole.h
    Console/IConsoleTypes.h
    Console/ILogger.h
    Console/LoggerSystemComponent.cpp
    Console/LoggerSystemComponent.h
    Date/DateFormat.cpp
    Date/DateFormat.h
    Debug/Budget.h
    Debug/Budget.cpp
    Debug/BudgetTracker.h
    Debug/BudgetTracker.cpp
    Debug/MemoryProfiler.h
    Debug/PerformanceCollector.h
    Debug/PerformanceCollector.cpp
    Debug/Profiler.cpp
    Debug/Profiler.h
    Debug/ProfilerBus.h
    Debug/ProfilerReflection.cpp
    Debug/ProfilerReflection.h
    Debug/Timer.h
    Debug/TraceMessageBus.h
    Debug/TraceReflection.cpp
    Debug/TraceReflection.h

    Module/EBusInstantiations.cpp
    Module/AZStdInstantiations.cpp

    Settings/CommandLine.cpp
    Settings/CommandLine.h
    Settings/CommandLineParser.cpp
    Settings/CommandLineParser.h
    Settings/ConfigParser.cpp
    Settings/ConfigParser.h
    Settings/ConfigurableStack.cpp
    Settings/ConfigurableStack.inl
    Settings/ConfigurableStack.h
    Settings/SettingsRegistry.cpp
    Settings/SettingsRegistry.h
    Settings/SettingsRegistryConsoleUtils.cpp
    Settings/SettingsRegistryConsoleUtils.h
    Settings/SettingsRegistryImpl.cpp
    Settings/SettingsRegistryImpl.h
    Settings/SettingsRegistryMergeUtils.cpp
    Settings/SettingsRegistryMergeUtils.h
    Settings/SettingsRegistryOriginTracker.cpp
    Settings/SettingsRegistryOriginTracker.h
    Settings/SettingsRegistryScriptUtils.cpp
    Settings/SettingsRegistryScriptUtils.h
    Settings/SettingsRegistryVisitorUtils.cpp
    Settings/SettingsRegistryVisitorUtils.h
    Settings/TextParser.cpp
    Settings/TextParser.h
)
