/*
 * Copyright (c) Contributors to the Open 3D Engine Project.
 * For complete copyright and license terms please see the LICENSE at the root of this distribution.
 *
 * SPDX-License-Identifier: Apache-2.0 OR MIT
 *
 */
#pragma once

#include <AzCore/base.h>

#if defined(AZ_MONOLITHIC_BUILD)

#define AZCORE_DECLARE_EBUS_SINGLE_ADDRESS(a)                       AZ_DECLARE_EBUS_EXTERN_SINGLE_ADDRESS(a)
#define AZCORE_INSTANTIATE_EBUS_SINGLE_ADDRESS(a)                   AZ_DECLARE_EBUS_INSTANTIATION_SINGLE_ADDRESS(a)
#define AZCORE_DECLARE_EBUS_EXTERN_MULTI_ADDRESS(a)                 AZ_DECLARE_EBUS_EXTERN_MULTI_ADDRESS(a)
#define AZCORE_INSTANTIATE_EBUS_MULTI_ADDRESS(a)                    AZ_DECLARE_EBUS_INSTANTIATION_MULTI_ADDRESS(a)
#define AZCORE_DECLARE_EBUS_EXTERN_SINGLE_ADDRESS_WITH_TRAITS(a, b) AZ_DECLARE_EBUS_EXTERN_SINGLE_ADDRESS_WITH_TRAITS(a, b)
#define AZCORE_INSTANTIATE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(a, b)    AZ_DECLARE_EBUS_INSTANTIATION_SINGLE_ADDRESS_WITH_TRAITS(a, b)
#define AZCORE_DECLARE_EBUS_EXTERN_MULTI_ADDRESS_WITH_TRAITS(a, b)  AZ_DECLARE_EBUS_EXTERN_MULTI_ADDRESS_WITH_TRAITS(a, b)
#define AZCORE_INSTANTIATE_EBUS_MULTI_ADDRESS_WITH_TRAITS(a, b)     AZ_DECLARE_EBUS_INSTANTIATION_MULTI_ADDRESS_WITH_TRAITS(a, b) 

#else

#define AZCORE_DECLARE_EBUS_SINGLE_ADDRESS(a)                       AZ_DECLARE_EBUS_EXTERN_SINGLE_ADDRESS(AZCORE_API, a) 
#define AZCORE_INSTANTIATE_EBUS_SINGLE_ADDRESS(a)                   AZ_DECLARE_EBUS_INSTANTIATION_SINGLE_ADDRESS(AZCORE_API, a)
#define AZCORE_DECLARE_EBUS_EXTERN_MULTI_ADDRESS(a)                 AZ_DECLARE_EBUS_EXTERN_MULTI_ADDRESS(AZCORE_API, a)
#define AZCORE_INSTANTIATE_EBUS_MULTI_ADDRESS(a)                    AZ_DECLARE_EBUS_INSTANTIATION_MULTI_ADDRESS(AZCORE_API, a)
#define AZCORE_DECLARE_EBUS_EXTERN_SINGLE_ADDRESS_WITH_TRAITS(a, b) AZ_DECLARE_EBUS_EXTERN_SINGLE_ADDRESS_WITH_TRAITS(AZCORE_API, a, b)
#define AZCORE_INSTANTIATE_EBUS_SINGLE_ADDRESS_WITH_TRAITS(a, b)    AZ_DECLARE_EBUS_INSTANTIATION_SINGLE_ADDRESS_WITH_TRAITS(AZCORE_API, a, b)
#define AZCORE_DECLARE_EBUS_EXTERN_MULTI_ADDRESS_WITH_TRAITS(a, b)  AZ_DECLARE_EBUS_EXTERN_MULTI_ADDRESS_WITH_TRAITS(AZCORE_API, a, b)
#define AZCORE_INSTANTIATE_EBUS_MULTI_ADDRESS_WITH_TRAITS(a, b)     AZ_DECLARE_EBUS_INSTANTIATION_MULTI_ADDRESS_WITH_TRAITS(AZCORE_API, a, b)

#endif //defined(AZ_MONOLITHIC_BUILD)
