#
# Copyright (c) Contributors to the Open 3D Engine Project. For complete copyright and license terms please see the LICENSE at the root of this distribution.
# 
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Main.cpp
    ArchiveTests.cpp
    AssetFileInfoListComparison.cpp
    AssetSeedManager.cpp
    AssetSystemMocks.h
    ComponentModeTests.cpp
    ComponentModeTestDoubles.h
    ComponentModeTestDoubles.cpp
    ComponentModeTestFixture.h
    ComponentModeTestFixture.cpp
    EditorTransformComponentSelectionTests.cpp
    EditorVertexSelectionTests.cpp
    EntityIdQLabelTests.cpp
    EntityInspectorTests.cpp
    FingerprintingTests.cpp
    LogLines.cpp
    ManipulatorBoundsTests.cpp
    ManipulatorCoreTests.cpp
    ManipulatorViewTests.cpp
    PlatformAddressedAssetCatalogTests.cpp
    PropertyIntCtrlCommonTests.h
    IntegerPrimtitiveTestConfig.h
    QtWidgetLimitsTests.cpp
    PropertyIntSliderCtrlTests.cpp
    PropertyIntSpinCtrlTests.cpp
    PropertyTreeEditorTests.cpp
    PythonBindingTests.cpp
    Slice.cpp
    SliceUpgradeTestsData.h
    SliceUpgradeTests.cpp
    SpinBoxTests.cpp
    ThumbnailerTests.cpp
    UndoStack.cpp
    PerforceComponentTests.cpp
    Prefab/Benchmark/PrefabBenchmarkFixture.cpp
    Prefab/Benchmark/PrefabBenchmarkFixture.h
    Prefab/Benchmark/PrefabCreateBenchmarks.cpp
    Prefab/Benchmark/PrefabInstantiateBenchmarks.cpp
    Prefab/Benchmark/PrefabLoadBenchmarks.cpp
    Prefab/Benchmark/PrefabUpdateInstancesBenchmarks.cpp
    Prefab/Benchmark/SpawnableCreateBenchmarks.cpp
    Prefab/Spawnable/SpawnableMetaDataTests.cpp
    Prefab/MockPrefabFileIOActionValidator.cpp
    Prefab/MockPrefabFileIOActionValidator.h
    Prefab/PrefabDuplicateTests.cpp
    Prefab/PrefabEntityAliasTests.cpp
    Prefab/PrefabInstanceToTemplatePropagatorTests.cpp
    Prefab/PrefabInstantiateTests.cpp
    Prefab/PrefabLoadTemplateTests.cpp
    Prefab/PrefabTestComponent.cpp
    Prefab/PrefabTestComponent.h
    Prefab/PrefabTestData.cpp
    Prefab/PrefabTestData.h
    Prefab/PrefabTestDataUtils.cpp
    Prefab/PrefabTestDataUtils.h
    Prefab/PrefabTestDomUtils.cpp
    Prefab/PrefabTestDomUtils.h
    Prefab/PrefabTestFixture.cpp
    Prefab/PrefabTestFixture.h
    Prefab/PrefabTestUndoFixture.cpp
    Prefab/PrefabTestUndoFixture.h
    Prefab/PrefabUndoLinkTests.cpp
    Prefab/PrefabUndoTests.cpp
    Prefab/PrefabTestUtils.h
    Prefab/PrefabUpdateInstancesTests.cpp
    Prefab/PrefabUpdateTemplateTests.cpp
    Prefab/PrefabUpdateWithPatchesTests.cpp
    Prefab/PrefabInstantiateTests.cpp
    Prefab/SpawnableCreateTests.cpp
    Prefab/SpawnableRemoveEditorInfoTests.cpp
    Prefab/SpawnableRemoveEditorInfoTestFixture.cpp
    Prefab/SpawnableRemoveEditorInfoTestFixture.h
    Prefab/SpawnableSortEntitiesTests.cpp
    Prefab/SpawnableSortEntitiesTestFixture.cpp
    Prefab/SpawnableSortEntitiesTestFixture.h
    Entity/EditorEntityContextComponentTests.cpp
    Entity/EditorEntityHelpersTests.cpp
    Entity/EditorEntitySearchComponentTests.cpp
    Entity/EditorEntitySelectionTests.cpp
    SliceStabilityTests/SliceStabilityTestFramework.h
    SliceStabilityTests/SliceStabilityTestFramework.cpp
    SliceStabilityTests/SliceStabilityCreateTests.cpp
    SliceStabilityTests/SliceStabilityPushTests.cpp
    SliceStabilityTests/SliceStabilityReParentTests.cpp
    ToolsComponents/EditorLayerComponentTests.cpp
    ToolsComponents/EditorTransformComponentTests.cpp
    UI/EntityPropertyEditorTests.cpp
    Viewport/ViewportScreenTests.cpp
    Viewport/ViewportUiClusterTests.cpp
    Viewport/ViewportUiDisplayTests.cpp
    Viewport/ViewportUiManagerTests.cpp
    Viewport/ClusterTests.cpp
    Viewport/ViewportUiWidgetManagerTests.cpp
    Visibility/EditorVisibilityTests.cpp
)
