#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    Source/RHI/AliasedHeap.cpp
    Source/RHI/AliasedHeap.h
    Source/RHI/Buffer.cpp
    Source/RHI/Buffer.h
    Source/RHI/BufferView.cpp
    Source/RHI/BufferView.h
    Source/RHI/BufferPool.cpp
    Source/RHI/BufferPool.h
    Source/RHI/CommandList.cpp
    Source/RHI/CommandList.h
    Source/RHI/CommandQueue.cpp
    Source/RHI/CommandQueue.h
    Source/RHI/Device.cpp
    Source/RHI/Device.h
    Source/RHI/DispatchRaysIndirectBuffer.h
    Source/RHI/Fence.cpp
    Source/RHI/Fence.h
    Source/RHI/FrameGraphCompiler.cpp
    Source/RHI/FrameGraphCompiler.h
    Source/RHI/FrameGraphExecuter.cpp
    Source/RHI/FrameGraphExecuter.h
    Source/RHI/Image.cpp
    Source/RHI/Image.h
    Source/RHI/ImagePool.cpp
    Source/RHI/ImagePool.h
    Source/RHI/ImageView.cpp
    Source/RHI/ImageView.h
    Source/RHI/PhysicalDevice.cpp
    Source/RHI/PhysicalDevice.h
    Source/RHI/PipelineState.cpp
    Source/RHI/PipelineState.h
    Source/RHI/PipelineLibrary.cpp
    Source/RHI/PipelineLibrary.h
    Source/RHI/Query.cpp
    Source/RHI/Query.h
    Source/RHI/QueryPool.cpp
    Source/RHI/QueryPool.h
    Source/RHI/Scope.cpp
    Source/RHI/Scope.h
    Source/RHI/ShaderResourceGroup.cpp
    Source/RHI/ShaderResourceGroup.h
    Source/RHI/ShaderResourceGroupPool.cpp
    Source/RHI/ShaderResourceGroupPool.h
    Source/RHI/StreamingImagePool.cpp
    Source/RHI/StreamingImagePool.h
    Source/RHI/SwapChain.cpp
    Source/RHI/SwapChain.h
    Source/RHI/SystemComponent.cpp
    Source/RHI/SystemComponent.h
    Source/RHI/TransientAttachmentPool.cpp
    Source/RHI/TransientAttachmentPool.h
    Source/RHI/RayTracingBufferPools.h
    Source/RHI/RayTracingBlas.cpp
    Source/RHI/RayTracingBlas.h
    Source/RHI/RayTracingTlas.cpp
    Source/RHI/RayTracingTlas.h
    Source/RHI/RayTracingPipelineState.cpp
    Source/RHI/RayTracingPipelineState.h
    Source/RHI/RayTracingShaderTable.cpp
    Source/RHI/RayTracingShaderTable.h
    Source/RHI/RayTracingCompactionQueryPool.h
    Source/RHI/RayTracingCompactionQueryPool.cpp
)
