#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

set(FILES
    source/models/AssetBundlerAbstractFileTableModel.h
    source/models/AssetBundlerAbstractFileTableModel.cpp
    source/models/AssetBundlerFileTableFilterModel.h
    source/models/AssetBundlerFileTableFilterModel.cpp
    source/models/AssetListFileTableModel.h
    source/models/AssetListFileTableModel.cpp
    source/models/AssetListTableModel.cpp
    source/models/AssetListTableModel.h
    source/models/BundleFileListModel.h
    source/models/BundleFileListModel.cpp
    source/models/RulesFileTableModel.h
    source/models/RulesFileTableModel.cpp
    source/models/SeedListFileTableModel.h
    source/models/SeedListFileTableModel.cpp
    source/models/SeedListTableModel.h
    source/models/SeedListTableModel.cpp
    source/ui/style/AssetBundler.qrc
    source/ui/style/AssetBundler.qss
    source/ui/style/AssetBundlerConfig.ini
    source/ui/style/AssetBundler-Icon-256x256@x2.ico
    source/ui/AddSeedDialog.h
    source/ui/AddSeedDialog.cpp
    source/ui/AddSeedDialog.ui
    source/ui/AssetBundlerTabWidget.h
    source/ui/AssetBundlerTabWidget.cpp
    source/ui/AssetListTabWidget.h
    source/ui/AssetListTabWidget.cpp
    source/ui/AssetListTabWidget.ui
    source/ui/BundleListTabWidget.h
    source/ui/BundleListTabWidget.cpp
    source/ui/BundleListTabWidget.ui
    source/ui/ComparisonDataWidget.h
    source/ui/ComparisonDataWidget.cpp
    source/ui/ComparisonDataWidget.ui
    source/ui/EditSeedDialog.h
    source/ui/EditSeedDialog.cpp
    source/ui/EditSeedDialog.ui
    source/ui/GenerateBundlesModal.h
    source/ui/GenerateBundlesModal.cpp
    source/ui/GenerateBundlesModal.ui
    source/ui/MainWindow.h
    source/ui/MainWindow.cpp
    source/ui/MainWindow.ui
    source/ui/NewFileDialog.h
    source/ui/NewFileDialog.cpp
    source/ui/NewFileDialog.ui
    source/ui/PlatformSelectionWidget.h
    source/ui/PlatformSelectionWidget.cpp
    source/ui/PlatformSelectionWidget.ui
    source/ui/RulesTabWidget.h
    source/ui/RulesTabWidget.cpp
    source/ui/RulesTabWidget.ui
    source/ui/SeedTabWidget.h
    source/ui/SeedTabWidget.cpp
    source/ui/SeedTabWidget.ui
    source/utils/GUIApplicationManager.h
    source/utils/GUIApplicationManager.cpp
    source/utils/AssetBundlerBuildTarget.cpp
)
