name: AR

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
        - main
        - development
        - AR-development

jobs:
    # Cache-LFS:
    #     runs-on: ubuntu-latest
    #     name: Update LFS data cache
    #     outputs:
    #       lfs_sha: ${{ steps.lfs_sha_recover.outputs.lfs_sha }}
    #     steps:
    
    #     - name: Checkout
    #       uses: actions/checkout@v4
    #       with:
    #         fetch-depth: 1
    #         lfs: false

#### Windows Build ####
    Windows-Profile:
        uses: ./.github/workflows/windows-build.yml
        with:
            compiler: msvc
            config: profile
            image: windows-2022
            platform: Windows
            type: profile
    
    Windows-Asset:
        needs: Windows-Profile
        uses: ./.github/workflows/windows-build.yml
        with:
            compiler: msvc
            config: profile
            image: windows-2022
            platform: Windows
            type: asset_profile

    Windows-Test:
        needs: Windows-Asset
        uses: ./.github/workflows/windows-build.yml
        with:
            compiler: msvc
            config: profile
            image: windows-2022
            platform: Windows
            type: test_cpu_profile

    Windows-Release:
        uses: ./.github/workflows/windows-build.yml
        with:
            compiler: msvc
            config: release
            image: windows-2022
            platform: Windows
            type: release

#### Linux Build ####
    Linux-Profile:
        uses: ./.github/workflows/linux-build.yml
        with:
            compiler: clang
            config: profile
            image: ubuntu-22.04
            platform: Linux
            type: profile

    Linux-Asset:
        needs: Linux-Profile
        uses: ./.github/workflows/linux-build.yml
        with:
            compiler: clang
            config: profile
            image: ubuntu-22.04
            platform: Linux
            type: asset_profile

    Linux-Test:
        needs: Linux-Asset
        uses: ./.github/workflows/linux-build.yml
        with:
            compiler: clang
            config: profile
            image: ubuntu-22.04
            platform: Linux
            type: test_profile
            desktop: true

#### Android Build ####
    Android-Profile:
        uses: ./.github/workflows/android-build.yml
        with:
            compiler: msvc
            config: profile
            image: windows-2022
            platform: Android
            type: profile

    Android-Asset:
        uses: ./.github/workflows/android-build.yml
        with:
            compiler: msvc
            config: asset_profile
            image: windows-2022
            platform: Android
            type: asset_profile
            
    Android-Gradle:
        uses: ./.github/workflows/android-build.yml
        with:
            compiler: msvc
            config: gradle
            image: windows-2022
            platform: Android
            type: gradle
