name: Windows Profile

on:
  workflow_dispatch:
  workflow_call:
  push:
    paths: '.github/workflows/windows-profile.yml'

jobs:
  Build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [msvc]
        config: [profile]
        image: [windows-2022]
        platform: [Windows]
        type: [profile]

    runs-on: ${{ matrix.image }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.1
        with:
          show-progress: false
          
      # - name: Git LFS fetch
      #   run: |
      #     git lfs install
      #     git lfs fetch --include "*.ico,*.bmp"
      #     git lfs checkout

      - name: Recover LFS Data
        uses: f3d-app/lfs-data-cache-action@v1
        with:
          workflow_label: 'consumer'
          lfs_sha: ${{ needs.Cache-LFS.outputs.lfs_sha }}

      - name: Setup 3p, user, and build folders
        run: |
          "3rdParty", "build", ".o3de" | % {New-Item "${{ github.workspace }}\$_" -ItemType 'Directory' -Force}
          ".o3de" | % {New-Item -Path $env:USERPROFILE\$_ -ItemType SymbolicLink -Target ${{ github.workspace }}\$_ -Force}

      - name: Setup ccache
        uses: Chocobo1/setup-ccache-action@v1.4.4
        continue-on-error: true
        if: always()
        with:
          windows_compile_environment: msvc
          prepend_symlinks_to_path: false
          store_cache: true
          restore_cache: false
          ccache_options: |
            max_size=5G
            cache_dir=${{ github.workspace }}\.ccache
      
      - name: Get last run
        uses: dawidd6/action-download-artifact@v6
        id: last-run-id
        with:
          workflow_search: true
          dry_run: true
          if_no_artifact_found: warn
    
      - name: Restore build cache
        uses: actions/download-artifact@v4.1.8
        continue-on-error: true
        if: always()
        with:
          name: O3DE-${{ matrix.platform }}-build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ steps.last-run-id.outputs.runID || vars.Windows_ARTIFACT_RUNID || github.run_id }}

      - name: Extract build
        continue-on-error: true
        run: |
          echo "Windows_ARTIFACT_RUNID: ${{ vars.Windows_ARTIFACT_RUNID }}"
          echo "Runid: ${{ github.run_id }}"
          echo "Last run id: ${{ fromJSON(steps.last-run-id.outputs.artifacts)[0].workflow_run.id }}"
          
          tar -xvpf ${{ github.workspace }}\cache.tar
          rm ${{ github.workspace }}\cache.tar
        
      - name: Configure environment
        run: |
          echo "Installing dependancies"
          echo "Getting python..."
          python\get_python.bat
          
      - name: Add msbuild to PATH
        uses: ilammy/msvc-dev-cmd@v1.13.0
          
      - name: Build ${{ matrix.type }}
        env:
          LY_3RDPARTY_PATH: ${{ github.workspace }}\3rdParty
        run: 
          python\python.cmd -u scripts\build\ci_build.py --platform ${{ matrix.platform }} --type ${{ matrix.type }} 
      
      - name: Compress artifacts
        continue-on-error: true
        if: (contains(github.ref, 'development') || contains(github.ref, ${{ vars.STABILIZATION_BRANCH }})) && always()
        run: |
          tar --format=posix -cvpf ${{ github.workspace }}\cache.tar `
            .o3de\Python `
            python `
            3rdParty\packages `
            AutomatedTesting `
            .ccache
  
      - name: Save artifacts
        uses: actions/upload-artifact@v4.4.3
        continue-on-error: true
        if: (contains(github.ref, 'development') || contains(github.ref, ${{ vars.STABILIZATION_BRANCH }})) && always()
        with:
          name: O3DE-${{ matrix.platform }}-build
          compression-level: 1
          path: |
            ${{ github.workspace }}\cache.tar
          
      - name: Set artifact runid variable
        continue-on-error: true
        if: (contains(github.ref, 'development') || contains(github.ref,  ${{ vars.STABILIZATION_BRANCH }})) && always()
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: gh variable set Windows_ARTIFACT_RUNID --body  ${{ github.run_id }}
