"""
Copyright (c) Contributors to the Open 3D Engine Project.
For complete copyright and license terms please see the LICENSE at the root of this distribution.

SPDX-License-Identifier: Apache-2.0 OR MIT
"""

TOOL_APPLICATION_MAIN_WINDOW_WIDTH: int = 920
TOOL_APPLICATION_MAIN_WINDOW_HEIGHT: int = 600

MAIN_PAGE_LAYOUT_MARGIN_LEFTRIGHT: int = 10
MAIN_PAGE_LAYOUT_MARGIN_TOPBOTTOM: int = 15

INTERACTION_COMPONENT_HEIGHT: int = 25

"""error page related constants"""
ERROR_PAGE_LAYOUT_MARGIN_LEFTRIGHT: int = 25
ERROR_PAGE_LAYOUT_MARGIN_TOPBOTTOM: int = 20
ERROR_PAGE_LAYOUT_SPACING: int = 15

ERROR_PAGE_MAIN_WINDOW_WIDTH: int = 100
ERROR_PAGE_MAIN_WINDOW_HEIGHT: int = 75

ERROR_PAGE_NOTIFICATION_AREA_HEIGHT: int = 30
ERROR_PAGE_FOOTER_AREA_HEIGHT: int = 45

OK_BUTTON_WIDTH: int = 90

"""view edit page related constants"""
VIEW_EDIT_PAGE_HEADER_AREA_HEIGHT: int = 65
VIEW_EDIT_PAGE_CENTER_AREA_HEIGHT: int = 500
VIEW_EDIT_PAGE_FOOTER_AREA_HEIGHT: int = 50

VIEW_EDIT_PAGE_MARGIN_TOPBOTTOM: int = 10

# header area
CONFIG_FILE_LABEL_WIDTH: int = 65
CONFIG_FILE_COMBOBOX_WIDTH: int = 250
CONFIG_LOCATION_LABEL_WIDTH: int = 100
CONFIG_LOCATION_TEXT_WIDTH: int = 180
HEADER_AREA_SEPARATOR_WIDTH: int = 5

# center area
TABLE_VIEW_PAGE_INTERACTION_AREA_HEIGHT: int = 40

ADD_ROW_BUTTON_WIDTH: int = 90
DELETE_ROW_BUTTON_WIDTH: int = 90
IMPORT_RESOURCES_COMBOBOX_WIDTH: int = 180
TABLE_VIEW_PAGE_SEARCH_FILTER_WIDGET_WIDTH: int = 370

TABLE_VIEW_PAGE_TABLE_VIEW_AREA_HEIGHT: int = 450

RESOURCE_TABLE_HEADER_CELL_MAXIMUM: int = 450
RESOURCE_TABLE_HEADER_CELL_MINIMUM: int = 40

RESOURCE_TABLE_KEYNAME_COLUMN_WIDTH: int = 100
RESOURCE_TABLE_TYPE_COLUMN_WIDTH: int = 150
RESOURCE_TABLE_NAME_OR_ID_COLUMN_WIDTH: int = 370
RESOURCE_TABLE_ACCOUNTID_COLUMN_WIDTH: int = 100
RESOURCE_TABLE_REGION_COLUMN_WIDTH: int = 100

# footer area
SAVE_CHANGES_BUTTON_WIDTH: int = 90
CREATE_NEW_BUTTON_WIDTH: int = 90
RESCAN_BUTTON_WIDTH: int = 90
CANCEL_BUTTON_WIDTH: int = 90

"""import resources page related constants"""
IMPORT_RESOURCES_PAGE_HEADER_AREA_HEIGHT: int = 65
IMPORT_RESOURCES_PAGE_SEARCH_AREA_HEIGHT: int = 50
IMPORT_RESOURCES_PAGE_VIEW_AREA_HEIGHT: int = 500
IMPORT_RESOURCES_PAGE_FOOTER_AREA_HEIGHT: int = 50

IMPORT_RESOURCES_PAGE_MARGIN_TOPBOTTOM: int = 10

# back area
BACK_BUTTON_WIDTH: int = 100

# search area
TYPED_RESOURCES_LABEL_WIDTH: int = 125
TYPED_RESOURCES_COMBOBOX_WIDTH: int = 150
SEARCH_BUTTON_WIDTH: int = 90
IMPORT_BUTTON_WIDTH: int = 90
IMPORT_RESOURCES_PAGE_SEARCH_FILTER_WIDGET_WIDTH: int = 300

# tree view area
IMPORT_RESOURCES_PAGE_TREE_VIEW_HEIGHT: int = 450

RESOURCE_STACK_HEADER_CELL_MAXIMUM: int = 500
RESOURCE_STACK_HEADER_CELL_MINIMUM: int = 300
