"""
All or portions of this file Copyright (c) Amazon.com, Inc. or its affiliates or
its licensors.

For complete copyright and license terms please see the LICENSE at the root of this
distribution (the "License"). All use of this software is governed by the License,
or, if provided, by the license below or the license accompanying this file. Do not
remove or modify any license notices. This file is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
"""

TOOL_APPLICATION_MAIN_WINDOW_WIDTH: int = 920
TOOL_APPLICATION_MAIN_WINDOW_HEIGHT: int = 600

MAIN_PAGE_LAYOUT_MARGIN_LEFTRIGHT: int = 10
MAIN_PAGE_LAYOUT_MARGIN_TOPBOTTOM: int = 20

INTERACTION_COMPONENT_HEIGHT: int = 25
ICON_FRONT_SIZE: int = 12

"""view edit page related constants"""
VIEW_EDIT_PAGE_HEADER_FOOTER_AREA_HEIGHT: int = 75
VIEW_EDIT_PAGE_CENTER_AREA_HEIGHT: int = 450

VIEW_EDIT_PAGE_WIDGET_SUBCOMPONENT_Y: int = 25

# header area
CONFIG_FILE_LABEL_X: int = 25
CONFIG_FILE_LABEL_WIDTH: int = 60

CONFIG_FILE_COMBOBOX_X: int = 95
CONFIG_FILE_COMBOBOX_WIDTH: int = 200

CONFIG_LOCATION_LABEL_X: int = 620
CONFIG_LOCATION_LABEL_WIDTH: int = 80

CONFIG_LOCATION_TEXT_X: int = 705
CONFIG_LOCATION_TEXT_WIDTH: int = 150

CONFIG_LOCATION_BUTTON_X: int = 860

# center area
NOTIFICATION_PAGE_PROMPT_HEIGHT: int = 100
NOTIFICATION_PAGE_PROMPT_BUTTON_WIDTH: int = 75

TABLE_VIEW_PAGE_INTERACTION_AREA_HEIGHT: int = 40

ADD_ROW_BUTTON_X: int = 10
ADD_ROW_BUTTON_WIDTH: int = 75

DELETE_ROW_BUTTON_X: int = 90
DELETE_ROW_BUTTON_WIDTH: int = 75

IMPORT_RESOURCES_LABEL_X: int = 185
IMPORT_RESOURCES_LABEL_WIDTH: int = 40

IMPORT_RESOURCES_COMBOBOX_X: int = 225
IMPORT_RESOURCES_COMBOBOX_WIDTH: int = 150

TABLE_VIEW_PAGE_SEARCH_FILTER_WIDGET_X: int = 565
TABLE_VIEW_PAGE_SEARCH_FILTER_WIDGET_WIDTH: int = 300

TABLE_VIEW_PAGE_TABLE_VIEW_AREA_HEIGHT: int = 400

RESOURCE_TABLE_HEADER_CELL_MAXIMUM: int = 450
RESOURCE_TABLE_HEADER_CELL_MINIMUM: int = 40

RESOURCE_TABLE_KEYNAME_COLUMN_WIDTH: int = 100
RESOURCE_TABLE_TYPE_COLUMN_WIDTH: int = 150
RESOURCE_TABLE_NAME_OR_ID_COLUMN_WIDTH: int = 370
RESOURCE_TABLE_ACCOUNTID_COLUMN_WIDTH: int = 100
RESOURCE_TABLE_REGION_COLUMN_WIDTH: int = 100

# footer area
SAVE_CHANGES_BUTTON_X: int = 710
SAVE_CHANGES_BUTTON_WIDTH: int = 85

CANCEL_BUTTON_X: int = 800
CANCEL_BUTTON_WIDTH: int = 75


"""import resources page related constants"""
IMPORT_RESOURCES_PAGE_HEADER_AREA_HEIGHT: int = 55
IMPORT_RESOURCES_PAGE_SEARCH_AREA_HEIGHT: int = 55
IMPORT_RESOURCES_PAGE_VIEW_AREA_HEIGHT: int = 450

IMPORT_RESOURCES_PAGE_WIDGET_SUBCOMPONENT_Y: int = 15

BACK_BUTTON_WIDTH: int = 100

TYPED_RESOURCES_LABEL_X: int = 10
TYPED_RESOURCES_LABEL_WIDTH: int = 100

TYPED_RESOURCES_COMBOBOX_X: int = 115
TYPED_RESOURCES_COMBOBOX_WIDTH: int = 150

SEARCH_BUTTON_WIDTH: int = 80
IMPORT_BUTTON_WIDTH: int = 80

TYPED_RESOURCES_SEARCH_BUTTON_X: int = 310
TYPED_RESOURCES_IMPORT_BUTTON_X: int = 395

CFN_STACKS_SEARCH_BUTTON_X: int = 10
CFN_STACKS_IMPORT_BUTTON_X: int = 95

IMPORT_RESOURCES_PAGE_SEARCH_FILTER_WIDGET_X: int = 565
IMPORT_RESOURCES_PAGE_SEARCH_FILTER_WIDGET_WIDTH: int = 300

IMPORT_RESOURCES_PAGE_TREE_VIEW_X: int = 50
IMPORT_RESOURCES_PAGE_TREE_VIEW_WIDTH: int = 800
IMPORT_RESOURCES_PAGE_TREE_VIEW_HEIGHT: int = 400

RESOURCE_STACK_HEADER_CELL_MAXIMUM: int = 400
RESOURCE_STACK_HEADER_CELL_MINIMUM: int = 200
